// Команда contractgen — генератор Go-кода и производных файлов из YAML- и
// JSON-источников contracts/ (AD-20, AD-40, AD-17; FR-110, FR-111; критерии О7, О8).
//
// Источники → результат:
//
//	contracts/events/catalog.yaml     → backend/internal/contracts/catalog/catalog_gen.go
//	contracts/errors.yaml             → backend/internal/contracts/errcodes/errcodes_gen.go
//	contracts/statuses.yaml           → backend/internal/contracts/statuses/statuses_gen.go
//	contracts/constants.yaml          → backend/internal/contracts/constants/constants_gen.go
//	contracts/events/upcasters/*.yaml → backend/internal/contracts/upcast/upcast_gen.go
//	contracts/events/**.v*.json       → backend/internal/contracts/events/registry_gen.go (тип+версия → Go-тип data)
//	contracts/bpmn-ext/ant.json       → backend/internal/contracts/bpmnext/bpmnext_gen.go,
//	                                    contracts/bpmn-ext/ant.xsd, docs/bpmn-ext-properties.md
//	contracts/**.json                 → backend/internal/contracts/schemas/** (копия для встраивания в бинарник)
//
// Go-типы данных событий и прочих JSON Schema генерирует go-jsonschema
// (deploy/scripts/generate-go.sh); contractgen дополняет их тем, чего
// go-jsonschema не умеет. Запуск — из каталога backend/tools:
//
//	go run ./contractgen -root ../..
//
// Детерминизм: всё сортируется, время и окружение в результат не попадают —
// повторный запуск даёт побайтно тот же вывод (make check: перегенерация +
// git diff --exit-code).
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"slices"
	"strconv"
	"strings"
	"unicode"

	"go.yaml.in/yaml/v3"
)

var root string

func main() {
	flag.StringVar(&root, "root", "../..", "корень репозитория")
	flag.Parse()
	steps := []struct {
		name string
		fn   func() error
	}{
		{"catalog", genCatalog},
		{"errcodes", genErrors},
		{"statuses", genStatuses},
		{"constants", genConstants},
		{"upcast", genUpcasters},
		{"events registry", genEventRegistry},
		{"bpmnext", genBPMN},
		{"schemas", copySchemas},
		{"docs", genDocs},
	}
	for _, s := range steps {
		if err := s.fn(); err != nil {
			fmt.Fprintf(os.Stderr, "contractgen: %s: %v\n", s.name, err)
			os.Exit(1)
		}
	}
}

// ---------------------------------------------------------------- общее ----

func path(p string) string { return filepath.Join(root, p) }

func readYAML(p string, v any) error {
	b, err := os.ReadFile(path(p))
	if err != nil {
		return err
	}
	return yaml.Unmarshal(b, v)
}

func header(src, pkg string) string {
	return "// Code generated by backend/tools/contractgen; DO NOT EDIT.\n" +
		"// Источник: " + src + " (make generate). Руками не править (AD-20).\n\n"
}

func writeGo(rel string, src string) error {
	out, err := format.Source([]byte(src))
	if err != nil {
		return fmt.Errorf("%s: gofmt: %w\n%s", rel, err, src)
	}
	return writeFile(rel, out)
}

func writeFile(rel string, b []byte) error {
	p := path(rel)
	if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
		return err
	}
	return os.WriteFile(p, b, 0o644)
}

// camel: "item.item.registered" → "ItemItemRegistered", "NS_ANT" → "NsAnt".
func camel(s string) string {
	var b strings.Builder
	up := true
	for _, r := range s {
		if r == '.' || r == '_' || r == '-' || r == '/' || r == ' ' {
			up = true
			continue
		}
		if up {
			b.WriteRune(unicode.ToUpper(r))
			up = false
			continue
		}
		b.WriteRune(r)
	}
	out := b.String()
	if out != "" && unicode.IsDigit(rune(out[0])) {
		out = "N" + out
	}
	return out
}

// lowerAfterFirst: "NS_ANT" → "NsAnt" (для констант в верхнем регистре).
func constName(s string) string {
	parts := strings.Split(strings.ToLower(s), "_")
	for i, p := range parts {
		if p != "" {
			parts[i] = strings.ToUpper(p[:1]) + p[1:]
		}
	}
	return strings.Join(parts, "")
}

func q(s string) string { return strconv.Quote(s) }

func comment(s string) string {
	s = strings.TrimSpace(s)
	if s == "" {
		return ""
	}
	lines := strings.Split(s, "\n")
	for i, l := range lines {
		if l = strings.TrimSpace(l); l == "" {
			lines[i] = "//"
		} else {
			lines[i] = "// " + l
		}
	}
	return strings.Join(lines, "\n") + "\n"
}

// -------------------------------------------------------------- catalog ----

type catalogFile struct {
	CatalogVersion int                  `yaml:"catalog_version"`
	Modules        yaml.Node            `yaml:"modules"`
	Roles          yaml.Node            `yaml:"roles"`
	Streams        yaml.Node            `yaml:"streams"`
	Families       map[string]familyDef `yaml:"families"`
	Exceptions     map[string]string    `yaml:"emitter_exceptions"`
	Types          map[string]typeDef   `yaml:"types"`
}

type familyDef struct {
	Owner string `yaml:"owner"`
	Title string `yaml:"title"`
}

type typeDef struct {
	Title          string   `yaml:"title"`
	Emitter        string   `yaml:"emitter"`
	Role           string   `yaml:"role"`
	Kind           string   `yaml:"kind"`
	Stream         string   `yaml:"stream"`
	Axis           string   `yaml:"axis"`
	ActionClass    string   `yaml:"action_class"`
	Critical       bool     `yaml:"critical"`
	CAGroup        *string  `yaml:"ca_group"`
	GuardRelevant  bool     `yaml:"guard_relevant"`
	PublishStage   bool     `yaml:"publish_stage"`
	Provenance     []string `yaml:"provenance"`
	Versions       []int    `yaml:"versions"`
	CurrentVersion int      `yaml:"current_version"`
}

// orderedMap — пары ключ → строка из узла YAML в порядке файла.
func orderedMap(n yaml.Node) [][2]string {
	var out [][2]string
	for i := 0; i+1 < len(n.Content); i += 2 {
		out = append(out, [2]string{n.Content[i].Value, n.Content[i+1].Value})
	}
	return out
}

func genCatalog() error {
	var c catalogFile
	if err := readYAML("contracts/events/catalog.yaml", &c); err != nil {
		return err
	}
	var b strings.Builder
	b.WriteString(header("contracts/events/catalog.yaml", "catalog"))
	b.WriteString(`// Пакет catalog — каталог типов записей журнала (AD-40, AD-2, AD-27, AD-28, AD-30, AD-39):
// для каждого типа — единственный модуль-эмитент, вид записи, поток, ось статуса,
// класс действия, критичность, пометки guard_relevant и publish_stage.
//
// Слой: сгенерированные контракты — чистые данные; доступны домену (AD-1).
// Проверка «модуль эмитит чужой тип» опирается на Emitter (kernel.NewReaction,
// tools/emitcheck, проверка openapi.yaml).
package catalog

// Version — версия каталога.
`)
	fmt.Fprintf(&b, "const Version = %d\n\n", c.CatalogVersion)
	b.WriteString(`// Type — тип записи журнала ` + "`семейство.сущность.действие`" + `.
type Type string

// Kind — вид записи (AD-2).
type Kind string

// Виды записей.
const (
	KindFact     Kind = "fact"
	KindReaction Kind = "reaction"
	KindDecision Kind = "decision"
	KindService  Kind = "service"
)

// ActionClass — класс действия (AD-27); record — не действие.
type ActionClass string

// Классы действий.
const (
	ClassRecord       ActionClass = "record"
	ClassProtective   ActionClass = "protective"
	ClassPermissive   ActionClass = "permissive"
	ClassIrreversible ActionClass = "irreversible"
)

// Info — строка каталога для одного типа записи.
type Info struct {
	Type           Type
	Title          string
	Family         string
	Emitter        string
	Role           string
	Kind           Kind
	Stream         string
	Axis           string
	ActionClass    ActionClass
	Critical       bool
	CAGroup        string
	GuardRelevant  bool
	PublishStage   bool
	Provenance     []string
	Versions       []int
	CurrentVersion int
}

`)
	names := make([]string, 0, len(c.Types))
	for n := range c.Types {
		names = append(names, n)
	}
	slices.Sort(names)
	b.WriteString("// Типы записей каталога.\nconst (\n")
	for _, n := range names {
		t := c.Types[n]
		b.WriteString(comment(t.Title))
		fmt.Fprintf(&b, "%s Type = %s\n", camel(n), q(n))
	}
	b.WriteString(")\n\n")
	b.WriteString("// types — строки каталога, отсортированные по Type (для двоичного поиска).\nvar types = [...]Info{\n")
	for _, n := range names {
		t := c.Types[n]
		fam := strings.SplitN(n, ".", 2)[0]
		ca := ""
		if t.CAGroup != nil {
			ca = *t.CAGroup
		}
		fmt.Fprintf(&b, "{Type: %s, Title: %s, Family: %s, Emitter: %s, Role: %s, Kind: %s, Stream: %s, Axis: %s, ActionClass: %s, Critical: %v, CAGroup: %s, GuardRelevant: %v, PublishStage: %v, Provenance: %s, Versions: %s, CurrentVersion: %d},\n",
			camel(n), q(t.Title), q(fam), q(t.Emitter), q(t.Role), q(t.Kind), q(t.Stream), q(t.Axis), q(t.ActionClass), t.Critical, q(ca), t.GuardRelevant, t.PublishStage, strSlice(t.Provenance), intSlice(t.Versions), t.CurrentVersion)
	}
	b.WriteString("}\n\n")
	// Семейства.
	fams := make([]string, 0, len(c.Families))
	for f := range c.Families {
		fams = append(fams, f)
	}
	slices.Sort(fams)
	b.WriteString("// FamilyInfo — семейство типов и его модуль-владелец схемы (AD-40).\ntype FamilyInfo struct {\n\tFamily string\n\tOwner  string\n\tTitle  string\n}\n\n")
	b.WriteString("// families — семейства, отсортированные по имени.\nvar families = [...]FamilyInfo{\n")
	for _, f := range fams {
		fmt.Fprintf(&b, "{Family: %s, Owner: %s, Title: %s},\n", q(f), q(c.Families[f].Owner), q(c.Families[f].Title))
	}
	b.WriteString("}\n\n")
	// Модули, роли, потоки.
	b.WriteString("// ModuleInfo — модуль системы и его ответственность.\ntype ModuleInfo struct {\n\tName  string\n\tTitle string\n}\n\n")
	b.WriteString("// Modules — модули в порядке каталога.\nvar Modules = [...]ModuleInfo{\n")
	for _, kv := range orderedMap(c.Modules) {
		fmt.Fprintf(&b, "{Name: %s, Title: %s},\n", q(kv[0]), q(kv[1]))
	}
	b.WriteString("}\n\n")
	b.WriteString("// Roles — роли процесса, в которых исполняются функции-эмитенты (AD-40).\nvar Roles = [...]ModuleInfo{\n")
	for _, kv := range orderedMap(c.Roles) {
		fmt.Fprintf(&b, "{Name: %s, Title: %s},\n", q(kv[0]), q(kv[1]))
	}
	b.WriteString("}\n\n")
	b.WriteString("// Streams — виды потоков (AD-39).\nvar Streams = [...]ModuleInfo{\n")
	for _, kv := range orderedMap(c.Streams) {
		fmt.Fprintf(&b, "{Name: %s, Title: %s},\n", q(kv[0]), q(kv[1]))
	}
	b.WriteString("}\n\n")
	b.WriteString(`// Lookup возвращает строку каталога для типа.
func Lookup(t Type) (Info, bool) {
	lo, hi := 0, len(types)
	for lo < hi {
		m := (lo + hi) / 2
		if types[m].Type < t {
			lo = m + 1
		} else {
			hi = m
		}
	}
	if lo < len(types) && types[lo].Type == t {
		return types[lo], true
	}
	return Info{}, false
}

// All возвращает все строки каталога, отсортированные по типу.
func All() []Info { return types[:] }

// Families возвращает семейства, отсортированные по имени.
func Families() []FamilyInfo { return families[:] }

// Family возвращает семейство по имени.
func Family(name string) (FamilyInfo, bool) {
	for _, f := range families {
		if f.Family == name {
			return f, true
		}
	}
	return FamilyInfo{}, false
}

// EmittedBy сообщает, что тип t эмитит модуль module (AD-40: один эмитент на тип).
func EmittedBy(t Type, module string) bool {
	i, ok := Lookup(t)
	return ok && i.Emitter == module
}
`)
	return writeGo("backend/internal/contracts/catalog/catalog_gen.go", b.String())
}

func strSlice(ss []string) string {
	if len(ss) == 0 {
		return "nil"
	}
	parts := make([]string, len(ss))
	for i, s := range ss {
		parts[i] = q(s)
	}
	return "[]string{" + strings.Join(parts, ", ") + "}"
}

func intSlice(ns []int) string {
	if len(ns) == 0 {
		return "nil"
	}
	parts := make([]string, len(ns))
	for i, n := range ns {
		parts[i] = strconv.Itoa(n)
	}
	return "[]int{" + strings.Join(parts, ", ") + "}"
}

// --------------------------------------------------------------- errors ----

type errorsFile struct {
	Version           int                 `yaml:"version"`
	ProblemTypePrefix string              `yaml:"problem_type_prefix"`
	Codes             map[string]errorDef `yaml:"codes"`
}

type errorDef struct {
	Status     int      `yaml:"status"`
	Title      string   `yaml:"title"`
	Detail     string   `yaml:"detail"`
	UIKey      string   `yaml:"ui_key"`
	Quarantine bool     `yaml:"quarantine"`
	Severity   string   `yaml:"severity"`
	Guard      bool     `yaml:"guard"`
	Aliases    []string `yaml:"aliases"`
}

func genErrors() error {
	var f errorsFile
	if err := readYAML("contracts/errors.yaml", &f); err != nil {
		return err
	}
	var b strings.Builder
	b.WriteString(header("contracts/errors.yaml", "errcodes"))
	b.WriteString(`// Пакет errcodes — каталог кодов ошибок RFC 9457 (FR-28, AD-39, «Соглашения/Ошибки API»):
// код → HTTP-статус, заголовок, шаблон пояснения, ключ текста интерфейса, карантин,
// признак отказа доменного гарда.
//
// Слой: сгенерированные контракты — чистые данные; доступны домену (AD-1).
package errcodes

// Code — код ошибки ` + "`‹семейство›.‹причина›`" + `.
type Code string

// Info — строка каталога ошибок.
type Info struct {
	Code       Code
	Status     int
	Title      string
	Detail     string
	UIKey      string
	Quarantine bool
	Severity   string
	Guard      bool
	Aliases    []string
}

`)
	fmt.Fprintf(&b, "// ProblemTypePrefix — префикс URI типа проблемы.\nconst ProblemTypePrefix = %s\n\n", q(f.ProblemTypePrefix))
	names := make([]string, 0, len(f.Codes))
	for n := range f.Codes {
		names = append(names, n)
	}
	slices.Sort(names)
	b.WriteString("// Коды ошибок.\nconst (\n")
	for _, n := range names {
		b.WriteString(comment(f.Codes[n].Title))
		fmt.Fprintf(&b, "%s Code = %s\n", camel(n), q(n))
	}
	b.WriteString(")\n\nvar codes = [...]Info{\n")
	for _, n := range names {
		e := f.Codes[n]
		sev := e.Severity
		if sev == "" {
			sev = "error"
		}
		fmt.Fprintf(&b, "{Code: %s, Status: %d, Title: %s, Detail: %s, UIKey: %s, Quarantine: %v, Severity: %s, Guard: %v, Aliases: %s},\n",
			camel(n), e.Status, q(e.Title), q(e.Detail), q(e.UIKey), e.Quarantine, q(sev), e.Guard, strSlice(e.Aliases))
	}
	b.WriteString(`}

// Lookup возвращает строку каталога для кода.
func Lookup(c Code) (Info, bool) {
	lo, hi := 0, len(codes)
	for lo < hi {
		m := (lo + hi) / 2
		if codes[m].Code < c {
			lo = m + 1
		} else {
			hi = m
		}
	}
	if lo < len(codes) && codes[lo].Code == c {
		return codes[lo], true
	}
	return Info{}, false
}

// All возвращает все коды, отсортированные по коду.
func All() []Info { return codes[:] }
`)
	return writeGo("backend/internal/contracts/errcodes/errcodes_gen.go", b.String())
}

// ------------------------------------------------------------- statuses ----

type statusFile struct {
	Version      int       `yaml:"version"`
	Palette      yaml.Node `yaml:"palette"`
	Axes         yaml.Node `yaml:"axes"`
	Dictionaries yaml.Node `yaml:"dictionaries"`
}

type statusDict struct {
	Title     string `yaml:"title"`
	Owner     string `yaml:"owner"`
	ChangedBy string `yaml:"changed_by"`
	Values    []struct {
		Code  string `yaml:"code"`
		Label string `yaml:"label"`
		Tone  string `yaml:"tone"`
	} `yaml:"values"`
}

func genStatuses() error {
	var f statusFile
	if err := readYAML("contracts/statuses.yaml", &f); err != nil {
		return err
	}
	var b strings.Builder
	b.WriteString(header("contracts/statuses.yaml", "statuses"))
	b.WriteString(`// Пакет statuses — словарь статусов изделия (PRD §3b, AD-30, NFR-UI-3): шесть осей
// с модулем-владельцем и дополнительные словари; одно перечисление на весь продукт.
//
// Слой: сгенерированные контракты — чистые данные; доступны домену (AD-1).
package statuses

// Value — значение оси или словаря: код, текст интерфейса, тон цвета.
type Value struct {
	Code  string
	Label string
	Tone  string
}

// Dictionary — ось статуса или словарь.
type Dictionary struct {
	Name   string
	Title  string
	Owner  string
	Values []Value
}

`)
	// Палитра.
	b.WriteString("// Palette — тон → цвет по умолчанию.\nvar Palette = [...][2]string{\n")
	for i := 0; i+1 < len(f.Palette.Content); i += 2 {
		var p struct {
			Color string `yaml:"color"`
		}
		if err := f.Palette.Content[i+1].Decode(&p); err != nil {
			return err
		}
		fmt.Fprintf(&b, "{%s, %s},\n", q(f.Palette.Content[i].Value), q(p.Color))
	}
	b.WriteString("}\n\n")
	emit := func(node yaml.Node, varName, what string) error {
		var all []string
		for i := 0; i+1 < len(node.Content); i += 2 {
			name := node.Content[i].Value
			var d statusDict
			if err := node.Content[i+1].Decode(&d); err != nil {
				return err
			}
			tn := camel(name)
			b.WriteString(comment(d.Title + " (" + what + ")."))
			fmt.Fprintf(&b, "type %s string\n\n", tn)
			fmt.Fprintf(&b, "// Значения %s.\nconst (\n", name)
			vals := make([]string, 0, len(d.Values))
			for _, v := range d.Values {
				b.WriteString(comment(v.Label))
				fmt.Fprintf(&b, "%s%s %s = %s\n", tn, camel(v.Code), tn, q(v.Code))
				vals = append(vals, fmt.Sprintf("{Code: %s, Label: %s, Tone: %s}", q(v.Code), q(v.Label), q(v.Tone)))
			}
			b.WriteString(")\n\n")
			all = append(all, fmt.Sprintf("{Name: %s, Title: %s, Owner: %s, Values: []Value{%s}}", q(name), q(d.Title), q(d.Owner), strings.Join(vals, ", ")))
		}
		fmt.Fprintf(&b, "// %s — %s в порядке файла.\nvar %s = [...]Dictionary{\n%s,\n}\n\n", varName, what, varName, strings.Join(all, ",\n"))
		return nil
	}
	if err := emit(f.Axes, "Axes", "ось статуса"); err != nil {
		return err
	}
	if err := emit(f.Dictionaries, "Dictionaries", "словарь"); err != nil {
		return err
	}
	return writeGo("backend/internal/contracts/statuses/statuses_gen.go", b.String())
}

// ------------------------------------------------------------ constants ----

func genConstants() error {
	var n yaml.Node
	if err := readYAML("contracts/constants.yaml", &n); err != nil {
		return err
	}
	doc := n.Content[0]
	var b strings.Builder
	b.WriteString(header("contracts/constants.yaml", "constants"))
	b.WriteString("// Пакет constants — константы контракта v1: NS_ANT, URI расширения BPMN, шаблоны\n// payloadType и QR, формат цепочки (AD-3, AD-10, AD-17, AD-44).\n//\n// Слой: сгенерированные контракты — чистые данные; доступны домену (AD-1).\npackage constants\n\nconst (\n")
	for i := 0; i+1 < len(doc.Content); i += 2 {
		k, v := doc.Content[i], doc.Content[i+1]
		b.WriteString(comment(strings.TrimLeft(k.HeadComment, "# ")))
		switch v.Tag {
		case "!!int":
			fmt.Fprintf(&b, "%s = %s\n", constName(k.Value), v.Value)
		default:
			fmt.Fprintf(&b, "%s = %s\n", constName(k.Value), q(v.Value))
		}
	}
	b.WriteString(")\n")
	src := b.String()
	// Комментарии YAML — многострочные с «# » в начале строк.
	src = strings.ReplaceAll(src, "\n// # ", "\n// ")
	src = regexp.MustCompile(`(?m)^// #\s?`).ReplaceAllString(src, "// ")
	return writeGo("backend/internal/contracts/constants/constants_gen.go", src)
}

// ------------------------------------------------------------ upcasters ----

type upcasterFile struct {
	From      int         `yaml:"from"`
	To        int         `yaml:"to"`
	EventType string      `yaml:"event_type"`
	Remove    []string    `yaml:"remove"`
	Map       []upcastMap `yaml:"map"`
	Set       yaml.Node   `yaml:"set"`
}

type upcastMap struct {
	From    string    `yaml:"from"`
	Cases   yaml.Node `yaml:"cases"`
	Default yaml.Node `yaml:"default"`
}

func goValue(n *yaml.Node) string {
	switch n.Tag {
	case "!!int":
		return "int64(" + n.Value + ")"
	case "!!bool":
		return n.Value
	case "!!null":
		return "nil"
	default:
		return q(n.Value)
	}
}

func assigns(n yaml.Node) []string {
	var out []string
	for i := 0; i+1 < len(n.Content); i += 2 {
		out = append(out, fmt.Sprintf("setPath(out, %s, %s)", q(n.Content[i].Value), goValue(n.Content[i+1])))
	}
	return out
}

func genUpcasters() error {
	files, err := filepath.Glob(path("contracts/events/upcasters/*.yaml"))
	if err != nil {
		return err
	}
	slices.Sort(files)
	var b strings.Builder
	b.WriteString(header("contracts/events/upcasters/*.yaml", "upcast"))
	b.WriteString(`// Пакет upcast — повышатели версий данных событий (AD-20, FR-110): чистые функции
// над разобранным JSON-объектом поля data. Журнал хранит исходный конверт без
// изменений; повышение применяют при чтении воркер, воспроизведение и верификатор.
// Чего нет в старой версии — «unknown»; смысл не додумывается (FR-123).
//
// Слой: сгенерированные контракты — чистые функции без ввода-вывода; доступны домену.
package upcast

import (
	"fmt"
	"strings"
)

// Step — один шаг повышения типа from → from+1.
type Step struct {
	EventType string
	From, To  int
	Fn        func(map[string]any) map[string]any
}

`)
	var reg []string
	for _, f := range files {
		raw, err := os.ReadFile(f)
		if err != nil {
			return err
		}
		var u upcasterFile
		if err := yaml.Unmarshal(raw, &u); err != nil {
			return fmt.Errorf("%s: %w", f, err)
		}
		fn := fmt.Sprintf("%sV%dToV%d", camel(u.EventType), u.From, u.To)
		rel, _ := filepath.Rel(root, f)
		fmt.Fprintf(&b, "// %s — %s v%d → v%d (%s).\nfunc %s(in map[string]any) map[string]any {\n\tout := clone(in)\n", fn, u.EventType, u.From, u.To, rel, fn)
		for _, m := range u.Map {
			fmt.Fprintf(&b, "\tswitch v, _ := getPath(in, %s).(string); v {\n", q(m.From))
			for i := 0; i+1 < len(m.Cases.Content); i += 2 {
				fmt.Fprintf(&b, "\tcase %s:\n", q(m.Cases.Content[i].Value))
				for _, a := range assigns(*m.Cases.Content[i+1]) {
					b.WriteString("\t\t" + a + "\n")
				}
			}
			b.WriteString("\tdefault:\n")
			for _, a := range assigns(m.Default) {
				b.WriteString("\t\t" + a + "\n")
			}
			b.WriteString("\t}\n")
		}
		for _, r := range u.Remove {
			fmt.Fprintf(&b, "\tdeletePath(out, %s)\n", q(r))
		}
		for _, a := range assigns(u.Set) {
			b.WriteString("\t" + a + "\n")
		}
		b.WriteString("\treturn out\n}\n\n")
		reg = append(reg, fmt.Sprintf("{EventType: %s, From: %d, To: %d, Fn: %s}", q(u.EventType), u.From, u.To, fn))
	}
	fmt.Fprintf(&b, "// steps — все шаги повышения, по типу и версии.\nvar steps = [...]Step{\n%s,\n}\n\n", strings.Join(reg, ",\n"))
	b.WriteString(`// Steps возвращает все шаги повышения.
func Steps() []Step { return steps[:] }

// Upcast повышает data типа eventType с версии from до версии to цепочкой шагов.
// Нет шага — ошибка (приём: карантин ingest.unknown_schema_version, AD-20).
func Upcast(eventType string, from, to int, data map[string]any) (map[string]any, error) {
	for v := from; v < to; v++ {
		found := false
		for _, s := range steps {
			if s.EventType == eventType && s.From == v {
				data = s.Fn(data)
				found = true
				break
			}
		}
		if !found {
			return nil, fmt.Errorf("upcast: нет повышателя %s v%d → v%d", eventType, v, v+1)
		}
	}
	return data, nil
}

func clone(in map[string]any) map[string]any {
	out := make(map[string]any, len(in))
	for k, v := range in {
		if m, ok := v.(map[string]any); ok {
			v = clone(m)
		}
		out[k] = v
	}
	return out
}

func split(p string) []string { return strings.Split(strings.TrimPrefix(p, "/"), "/") }

func getPath(m map[string]any, p string) any {
	parts := split(p)
	var cur any = m
	for _, k := range parts {
		mm, ok := cur.(map[string]any)
		if !ok {
			return nil
		}
		cur = mm[k]
	}
	return cur
}

func setPath(m map[string]any, p string, v any) {
	parts := split(p)
	for _, k := range parts[:len(parts)-1] {
		next, ok := m[k].(map[string]any)
		if !ok {
			next = map[string]any{}
			m[k] = next
		}
		m = next
	}
	m[parts[len(parts)-1]] = v
}

func deletePath(m map[string]any, p string) {
	parts := split(p)
	for _, k := range parts[:len(parts)-1] {
		next, ok := m[k].(map[string]any)
		if !ok {
			return
		}
		m = next
	}
	delete(m, parts[len(parts)-1])
}
`)
	return writeGo("backend/internal/contracts/upcast/upcast_gen.go", b.String())
}

// ------------------------------------------------------- events registry ----

var schemaFile = regexp.MustCompile(`^([a-z_]+\.[a-z_]+\.[a-z_]+)\.v([0-9]+)\.json$`)

func genEventRegistry() error {
	var entries []string
	err := filepath.WalkDir(path("contracts/events"), func(p string, d fs.DirEntry, err error) error {
		if err != nil || d.IsDir() {
			return err
		}
		m := schemaFile.FindStringSubmatch(d.Name())
		if m == nil || strings.Contains(p, "/examples/") {
			return nil
		}
		raw, err := os.ReadFile(p)
		if err != nil {
			return err
		}
		var s struct {
			Title string `json:"title"`
		}
		if err := json.Unmarshal(raw, &s); err != nil {
			return fmt.Errorf("%s: %w", p, err)
		}
		entries = append(entries, fmt.Sprintf("{Type: %s, Version: %s, New: func() any { return new(%s) }}", q(m[1]), m[2], goTypeName(s.Title)))
		return nil
	})
	if err != nil {
		return err
	}
	slices.Sort(entries)
	var b strings.Builder
	b.WriteString(header("contracts/events/‹семейство›/‹тип›.v‹N›.json", "events"))
	b.WriteString(`package events

// DataType — тип и мажорная версия данных события и конструктор Go-типа поля data.
type DataType struct {
	Type    string
	Version int
	New     func() any
}

// dataTypes — все пары «тип, версия», отсортированные.
var dataTypes = [...]DataType{
`)
	b.WriteString(strings.Join(entries, ",\n"))
	b.WriteString(`,
}

// DataTypes возвращает все пары «тип, версия».
func DataTypes() []DataType { return dataTypes[:] }

// NewData возвращает указатель на пустое значение Go-типа поля data для типа и версии.
func NewData(eventType string, version int) (any, bool) {
	for _, d := range dataTypes {
		if d.Type == eventType && d.Version == version {
			return d.New(), true
		}
	}
	return nil, false
}
`)
	return writeGo("backend/internal/contracts/events/registry_gen.go", b.String())
}

// goTypeName повторяет правило go-jsonschema (--capitalization ID URL UUID JSON
// HTTP): слово заголовка, совпадающее с аббревиатурой, пишется заглавными.
func goTypeName(title string) string {
	words := regexp.MustCompile(`[A-Z][a-z0-9]*|[a-z0-9]+`).FindAllString(title, -1)
	for i, w := range words {
		switch strings.ToUpper(w) {
		case "ID", "URL", "UUID", "JSON", "HTTP":
			words[i] = strings.ToUpper(w)
		}
	}
	return strings.Join(words, "")
}

// ----------------------------------------------------------------- BPMN ----

type moddle struct {
	Name        string       `json:"name"`
	URI         string       `json:"uri"`
	Prefix      string       `json:"prefix"`
	Description string       `json:"description"`
	Types       []moddleType `json:"types"`
}

type moddleType struct {
	Name        string       `json:"name"`
	SuperClass  []string     `json:"superClass"`
	Description string       `json:"description"`
	Properties  []moddleProp `json:"properties"`
}

type moddleProp struct {
	Name        string `json:"name"`
	Type        string `json:"type"`
	IsAttr      bool   `json:"isAttr"`
	IsMany      bool   `json:"isMany"`
	IsBody      bool   `json:"isBody"`
	Description string `json:"description"`
}

func lowerFirst(s string) string { return strings.ToLower(s[:1]) + s[1:] }

func genBPMN() error {
	raw, err := os.ReadFile(path("contracts/bpmn-ext/ant.json"))
	if err != nil {
		return err
	}
	var m moddle
	if err := json.Unmarshal(raw, &m); err != nil {
		return err
	}
	// Go-структуры.
	var b strings.Builder
	b.WriteString(header("contracts/bpmn-ext/ant.json (дескриптор moddle)", "bpmnext"))
	b.WriteString(comment("Пакет bpmnext — Go-структуры XML расширения BPMN " + m.URI + " (AD-17, FR-12, FR-156).\n" + m.Description + "\n\nСлой: сгенерированные контракты — чистые данные; доступны домену (AD-1)."))
	b.WriteString("package bpmnext\n\nimport \"encoding/xml\"\n\n")
	fmt.Fprintf(&b, "// Namespace — пространство имён расширения.\nconst Namespace = %s\n\n// Prefix — префикс расширения в XML.\nconst Prefix = %s\n\n", q(m.URI), q(m.Prefix))
	var ext []string
	for _, t := range m.Types {
		el := lowerFirst(t.Name)
		b.WriteString(comment(t.Name + " — элемент ant:" + el + ". " + t.Description))
		fmt.Fprintf(&b, "type %s struct {\n\tXMLName xml.Name `xml:\"%s %s\"`\n", t.Name, m.URI, el)
		for _, p := range t.Properties {
			b.WriteString(comment(p.Description))
			goT := "string"
			switch p.Type {
			case "Boolean":
				goT = "*bool"
			case "Integer":
				goT = "*int64"
			}
			switch {
			case p.IsAttr:
				fmt.Fprintf(&b, "\t%s %s `xml:\"%s,attr,omitempty\"`\n", camel(p.Name), goT, p.Name)
			case p.IsBody:
				fmt.Fprintf(&b, "\t%s string `xml:\",chardata\"`\n", camel(p.Name))
			default:
				fmt.Fprintf(&b, "\t%s %s `xml:\"%s %s,omitempty\"`\n", camel(p.Name), goT, m.URI, p.Name)
			}
		}
		b.WriteString("}\n\n")
		ext = append(ext, fmt.Sprintf("\t%s []%s `xml:\"%s %s\"`\n", t.Name, t.Name, m.URI, el))
	}
	b.WriteString("// ExtensionElements — наши элементы внутри bpmn:extensionElements узла; чужие элементы пропускаются.\ntype ExtensionElements struct {\n")
	b.WriteString(strings.Join(ext, ""))
	b.WriteString("}\n")
	if err := writeGo("backend/internal/contracts/bpmnext/bpmnext_gen.go", b.String()); err != nil {
		return err
	}
	// XSD.
	var x strings.Builder
	x.WriteString(`<?xml version="1.0" encoding="UTF-8"?>
<!-- СГЕНЕРИРОВАНО backend/tools/contractgen из contracts/bpmn-ext/ant.json — руками не править (AD-20). -->
`)
	fmt.Fprintf(&x, "<xs:schema xmlns:xs=\"http://www.w3.org/2001/XMLSchema\" targetNamespace=\"%s\" xmlns:%s=\"%s\" elementFormDefault=\"qualified\" attributeFormDefault=\"unqualified\">\n", m.URI, m.Prefix, m.URI)
	fmt.Fprintf(&x, "  <xs:annotation><xs:documentation xml:lang=\"ru\">%s</xs:documentation></xs:annotation>\n", xmlEsc(m.Description))
	for _, t := range m.Types {
		el := lowerFirst(t.Name)
		fmt.Fprintf(&x, "  <xs:element name=\"%s\">\n    <xs:annotation><xs:documentation xml:lang=\"ru\">%s</xs:documentation></xs:annotation>\n    <xs:complexType>\n", el, xmlEsc(t.Description))
		var elems, attrs []moddleProp
		for _, p := range t.Properties {
			if p.IsAttr {
				attrs = append(attrs, p)
			} else {
				elems = append(elems, p)
			}
		}
		if len(elems) > 0 {
			x.WriteString("      <xs:sequence>\n")
			for _, p := range elems {
				fmt.Fprintf(&x, "        <xs:element name=\"%s\" type=\"%s\" minOccurs=\"0\">\n          <xs:annotation><xs:documentation xml:lang=\"ru\">%s</xs:documentation></xs:annotation>\n        </xs:element>\n", p.Name, xsdType(p.Type), xmlEsc(p.Description))
			}
			x.WriteString("      </xs:sequence>\n")
		}
		for _, p := range attrs {
			fmt.Fprintf(&x, "      <xs:attribute name=\"%s\" type=\"%s\" use=\"optional\">\n        <xs:annotation><xs:documentation xml:lang=\"ru\">%s</xs:documentation></xs:annotation>\n      </xs:attribute>\n", p.Name, xsdType(p.Type), xmlEsc(p.Description))
		}
		x.WriteString("    </xs:complexType>\n  </xs:element>\n")
	}
	x.WriteString("</xs:schema>\n")
	if err := writeFile("contracts/bpmn-ext/ant.xsd", []byte(x.String())); err != nil {
		return err
	}
	// Таблица документации.
	var d strings.Builder
	d.WriteString("<!-- СГЕНЕРИРОВАНО backend/tools/contractgen из contracts/bpmn-ext/ant.json — руками не править (AD-20). -->\n\n")
	fmt.Fprintf(&d, "# Свойства расширения BPMN `%s`\n\n%s\n\nЭлементы пишутся внутри `bpmn:extensionElements` узла с префиксом `%s:`. Допустимые значения и обязательность — `contracts/bpmn-ext/rules.yaml`; XSD — `contracts/bpmn-ext/ant.xsd`.\n\n", m.URI, m.Description, m.Prefix)
	for _, t := range m.Types {
		fmt.Fprintf(&d, "## `%s:%s`\n\n%s\n\n| Свойство | Тип | Где | Описание |\n|---|---|---|---|\n", m.Prefix, lowerFirst(t.Name), t.Description)
		for _, p := range t.Properties {
			where := "атрибут"
			if !p.IsAttr {
				where = "вложенный элемент"
			}
			fmt.Fprintf(&d, "| `%s` | %s | %s | %s |\n", p.Name, p.Type, where, strings.ReplaceAll(p.Description, "|", "\\|"))
		}
		d.WriteString("\n")
	}
	return writeFile("docs/bpmn-ext-properties.md", []byte(d.String()))
}

func xsdType(t string) string {
	switch t {
	case "Boolean":
		return "xs:boolean"
	case "Integer":
		return "xs:integer"
	default:
		return "xs:string"
	}
}

func xmlEsc(s string) string {
	var b bytes.Buffer
	_ = xmlEscape(&b, s)
	return b.String()
}

func xmlEscape(b *bytes.Buffer, s string) error {
	r := strings.NewReplacer("&", "&amp;", "<", "&lt;", ">", "&gt;", "\"", "&quot;")
	_, err := b.WriteString(r.Replace(s))
	return err
}

// -------------------------------------------------------------- schemas ----

// copySchemas копирует JSON Schema контрактов в backend/internal/contracts/schemas,
// чтобы встроить их в бинарник (go:embed не выходит за каталог пакета): приём
// проверяет тела теми же схемами (AD-20), операции Huma отдают исходную схему.
func copySchemas() error {
	dst := path("backend/internal/contracts/schemas")
	if err := os.RemoveAll(filepath.Join(dst, "contracts")); err != nil {
		return err
	}
	var files []string
	err := filepath.WalkDir(path("contracts"), func(p string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		rel, _ := filepath.Rel(path("contracts"), p)
		if d.IsDir() {
			if rel == "scripts" || strings.HasPrefix(rel, "crypto/test-vectors") || rel == "events/examples" {
				return filepath.SkipDir
			}
			return nil
		}
		if strings.HasSuffix(p, ".json") && !strings.HasSuffix(p, "package.json") && !strings.HasSuffix(p, "package-lock.json") {
			files = append(files, rel)
		}
		return nil
	})
	if err != nil {
		return err
	}
	slices.Sort(files)
	for _, rel := range files {
		b, err := os.ReadFile(path("contracts/" + rel))
		if err != nil {
			return err
		}
		if err := writeFile("backend/internal/contracts/schemas/contracts/"+rel, b); err != nil {
			return err
		}
	}
	var g strings.Builder
	g.WriteString(header("contracts/**/*.json", "schemas"))
	g.WriteString(`// Пакет schemas — JSON Schema контрактов, встроенные в бинарник (AD-20): приём
// проверяет сырые тела теми же схемами (santhosh-tekuri/jsonschema, эпик 06),
// операции Huma отдают исходную схему типов событий. Каталог contracts/ здесь —
// копия, которую делает make generate; руками не править.
package schemas

import "embed"

// FS — копия contracts/**/*.json; пути — от корня contracts (например,
// "contracts/events/common/envelope.v1.json").
//
//go:embed contracts
var FS embed.FS

// BaseURI — префикс $id схем; путь после него совпадает с путём в FS после "contracts/".
const BaseURI = "https://ant.invalid/contracts/"

// Files — перечень встроенных файлов, отсортированный.
var Files = [...]string{
`)
	for _, f := range files {
		fmt.Fprintf(&g, "\t%s,\n", q("contracts/"+f))
	}
	g.WriteString("}\n")
	return writeGo("backend/internal/contracts/schemas/schemas_gen.go", g.String())
}

// genDocs — заголовки пакетов, которые генерирует go-jsonschema (у его файлов
// нет комментария пакета; NFR-DOC-3: заголовок у каждого пакета).
func genDocs() error {
	docs := []struct{ pkg, src, text string }{
		{"events", "contracts/events", "Go-типы поля data всех типов записей журнала и общих определений (конверт, defs, сообщение SSE) — из JSON Schema contracts/events (AD-20, AD-40, FR-27). Реестр «тип + версия → Go-тип» — registry_gen.go."},
		{"crypto", "contracts/crypto", "Go-типы криптоформатов: конверт DSSE (AD-10), контрольная точка хранителя (AD-8)."},
		{"journal", "contracts/journal", "Go-тип записи журнала (AD-44): открытые поля, звено цепочки, обязательство; им пользуются все, включая верификатор."},
		{"procs", "contracts/internal", "Go-типы контрактов собственных процессов (AD-46): сообщения агента токена, сменный рапорт, отчёт верификатора, телеметрия stand-ов."},
		{"normative", "contracts/normative", "Go-типы файлов затравки нормативного слоя (/normative): политика, классификатор, карта реакций, шаблоны документов, справочники (AD-17, AD-31)."},
		{"problem", "contracts/problem.schema.json", "Go-тип тела ошибки RFC 9457 problem+json с расширениями ant (FR-28)."},
	}
	for _, d := range docs {
		src := header(d.src, d.pkg) + comment("Пакет "+d.pkg+" — "+d.text+"\n\nСлой: сгенерированные контракты — чистые данные; доступны домену (AD-1).") + "package " + d.pkg + "\n"
		if err := writeGo("backend/internal/contracts/"+d.pkg+"/doc_gen.go", src); err != nil {
			return err
		}
	}
	return nil
}
