// Code generated by backend/tools/contractgen; DO NOT EDIT.
// Источник: contracts/events (make generate). Руками не править (AD-20).

// Пакет events — Go-типы поля data всех типов записей журнала и общих определений (конверт, defs, сообщение SSE) — из JSON Schema contracts/events (AD-20, AD-40, FR-27). Реестр «тип + версия → Go-тип» — registry_gen.go.
//
// Слой: сгенерированные контракты — чистые данные; доступны домену (AD-1).
package events
