// Code generated by backend/tools/contractgen; DO NOT EDIT.
// Источник: contracts/events/common/defs.v1.json#/definitions/timestamp (make generate). Руками не править (AD-20).

package events

import (
	"bytes"
	"errors"
	"fmt"
	"time"
)

// TimestampLayout — формат момента времени в контрактах: RFC 3339 UTC, ровно
// три знака после секунд (YYYY-MM-DDTHH:MM:SS.mmmZ; соглашение спайна «Время»).
const TimestampLayout = "2006-01-02T15:04:05.000Z"

// NewTimestamp приводит момент к UTC и отбрасывает доли меньше миллисекунды —
// так он будет записан в JSON.
func NewTimestamp(t time.Time) Timestamp { return Timestamp(t.UTC().Truncate(time.Millisecond)) }

// ParseTimestamp разбирает строку строго по TimestampLayout.
func ParseTimestamp(s string) (Timestamp, error) {
	t, err := time.Parse(TimestampLayout, s)
	if err != nil {
		return Timestamp{}, fmt.Errorf("время %q: ожидается YYYY-MM-DDTHH:MM:SS.mmmZ: %w", s, err)
	}
	return Timestamp(t), nil
}

// Time возвращает момент как time.Time.
func (t Timestamp) Time() time.Time { return time.Time(t) }

// IsZero — нулевой момент (для omitzero).
func (t Timestamp) IsZero() bool { return time.Time(t).IsZero() }

// String — момент в формате TimestampLayout.
func (t Timestamp) String() string { return time.Time(t).UTC().Format(TimestampLayout) }

// MarshalJSON пишет момент строкой TimestampLayout в UTC; доли меньше
// миллисекунды отбрасываются.
func (t Timestamp) MarshalJSON() ([]byte, error) {
	u := time.Time(t).UTC()
	if y := u.Year(); y < 0 || y > 9999 {
		return nil, errors.New("events.Timestamp.MarshalJSON: год вне диапазона [0,9999]")
	}
	b := make([]byte, 0, len(TimestampLayout)+2)
	b = append(b, '"')
	b = u.AppendFormat(b, TimestampLayout)
	return append(b, '"'), nil
}

// UnmarshalJSON разбирает строку строго по TimestampLayout (как pattern схемы);
// null не меняет значение (соглашение encoding/json).
func (t *Timestamp) UnmarshalJSON(b []byte) error {
	if bytes.Equal(b, []byte("null")) {
		return nil
	}
	if len(b) < 2 || b[0] != '"' || b[len(b)-1] != '"' {
		return fmt.Errorf("events.Timestamp.UnmarshalJSON: ожидается строка, получено %s", b)
	}
	v, err := ParseTimestamp(string(b[1 : len(b)-1]))
	if err != nil {
		return err
	}
	*t = v
	return nil
}
