// СГЕНЕРИРОВАНО contracts/scripts/gen-ts.mjs (make generate) — руками не править (AD-20).
// Источник: contracts/events/catalog.yaml

/** Каталог типов записей журнала (AD-40): эмитент, вид, поток, ось статуса, класс действия, критичность. */
export const eventCatalog = {
  "access.account.activated": {
    "title": "Учётная запись активирована",
    "emitter": "access",
    "kind": "decision",
    "stream": "person",
    "axis": "none",
    "actionClass": "permissive",
    "critical": true,
    "caGroup": "authority",
    "currentVersion": 1
  },
  "access.assignment.cleared": {
    "title": "Назначение на пост снято",
    "emitter": "access",
    "kind": "decision",
    "stream": "workplace",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "access.assignment.set": {
    "title": "Назначение на пост",
    "emitter": "access",
    "kind": "decision",
    "stream": "workplace",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "access.person.registered": {
    "title": "Сотрудник заведён",
    "emitter": "access",
    "kind": "decision",
    "stream": "person",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "access.qualification.granted": {
    "title": "Квалификация или аттестация выдана",
    "emitter": "access",
    "kind": "decision",
    "stream": "person",
    "axis": "none",
    "actionClass": "permissive",
    "critical": true,
    "caGroup": "authority",
    "currentVersion": 1
  },
  "access.qualification.revoked": {
    "title": "Квалификация отозвана",
    "emitter": "access",
    "kind": "decision",
    "stream": "person",
    "axis": "none",
    "actionClass": "protective",
    "critical": true,
    "caGroup": "authority",
    "currentVersion": 1
  },
  "access.token.presence_changed": {
    "title": "Токен вставлен или извлечён",
    "emitter": "access",
    "kind": "fact",
    "stream": "workplace",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "access.workplace.admitted": {
    "title": "Допуск к рабочему месту открыт",
    "emitter": "access",
    "kind": "decision",
    "stream": "workplace",
    "axis": "none",
    "actionClass": "permissive",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "access.workplace.released": {
    "title": "Сеанс рабочего места завершён сотрудником",
    "emitter": "access",
    "kind": "decision",
    "stream": "workplace",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "access.workplace.revoked": {
    "title": "Допуск к рабочему месту снят автоматически",
    "emitter": "access",
    "kind": "reaction",
    "stream": "workplace",
    "axis": "none",
    "actionClass": "protective",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "access.zone.passed": {
    "title": "Проход через точку СКУД",
    "emitter": "access",
    "kind": "fact",
    "stream": "person",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "analyzer.check.recorded": {
    "title": "Проверка анализатора",
    "emitter": "vision",
    "kind": "fact",
    "stream": "analyzer_passport",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "analyzer.passport.admitted": {
    "title": "Паспорт допуска введён в действие",
    "emitter": "vision",
    "kind": "decision",
    "stream": "analyzer_passport",
    "axis": "none",
    "actionClass": "permissive",
    "critical": true,
    "caGroup": "control_change",
    "currentVersion": 1
  },
  "analyzer.passport.reinstated": {
    "title": "Анализатор возвращён в работу",
    "emitter": "vision",
    "kind": "decision",
    "stream": "analyzer_passport",
    "axis": "none",
    "actionClass": "permissive",
    "critical": true,
    "caGroup": "control_change",
    "currentVersion": 1
  },
  "analyzer.passport.retired": {
    "title": "Паспорт допуска выведен",
    "emitter": "vision",
    "kind": "decision",
    "stream": "analyzer_passport",
    "axis": "none",
    "actionClass": "record",
    "critical": true,
    "caGroup": "control_change",
    "currentVersion": 1
  },
  "analyzer.passport.suspended": {
    "title": "Паспорт допуска приостановлен",
    "emitter": "vision",
    "kind": "reaction",
    "stream": "analyzer_passport",
    "axis": "none",
    "actionClass": "protective",
    "critical": true,
    "caGroup": "control_change",
    "currentVersion": 1
  },
  "binding.link.assigned": {
    "title": "Привязка задана человеком",
    "emitter": "crossitem",
    "kind": "decision",
    "stream": "item",
    "axis": "none",
    "actionClass": "record",
    "critical": true,
    "caGroup": "protected_data",
    "currentVersion": 1
  },
  "binding.link.resolved": {
    "title": "Событие привязано к изделию",
    "emitter": "crossitem",
    "kind": "reaction",
    "stream": "item",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "cad.assembly.imported": {
    "title": "Условная сборка импортирована",
    "emitter": "cad",
    "kind": "fact",
    "stream": "reference",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "decision.concession.revoked": {
    "title": "Разрешение на отклонение отозвано",
    "emitter": "nonconformity",
    "kind": "decision",
    "stream": "concession",
    "axis": "none",
    "actionClass": "protective",
    "critical": true,
    "caGroup": "nc_decision",
    "currentVersion": 1
  },
  "decision.containment.applied": {
    "title": "Сдерживание применено правилом",
    "emitter": "nonconformity",
    "kind": "reaction",
    "stream": "item",
    "axis": "containment",
    "actionClass": "protective",
    "critical": true,
    "caGroup": "product_decision",
    "currentVersion": 1
  },
  "decision.containment.released": {
    "title": "Сдерживание снято",
    "emitter": "nonconformity",
    "kind": "decision",
    "stream": "item",
    "axis": "containment",
    "actionClass": "permissive",
    "critical": true,
    "caGroup": "product_decision",
    "currentVersion": 1
  },
  "decision.containment.set": {
    "title": "Сдерживание установлено человеком",
    "emitter": "nonconformity",
    "kind": "decision",
    "stream": "item",
    "axis": "containment",
    "actionClass": "protective",
    "critical": true,
    "caGroup": "product_decision",
    "currentVersion": 1
  },
  "decision.disposition.applied": {
    "title": "Решение по изделию применено правилом",
    "emitter": "nonconformity",
    "kind": "reaction",
    "stream": "item",
    "axis": "disposition",
    "actionClass": "permissive",
    "critical": true,
    "caGroup": "nc_decision",
    "currentVersion": 1
  },
  "decision.disposition.set": {
    "title": "Решение по изделию принято",
    "emitter": "nonconformity",
    "kind": "decision",
    "stream": "item",
    "axis": "disposition",
    "actionClass": "irreversible",
    "critical": true,
    "caGroup": "nc_decision",
    "currentVersion": 1
  },
  "decision.disposition.verified": {
    "title": "Исполнение решения проверено",
    "emitter": "nonconformity",
    "kind": "decision",
    "stream": "item",
    "axis": "none",
    "actionClass": "permissive",
    "critical": true,
    "caGroup": "product_decision",
    "currentVersion": 1
  },
  "decision.item.isolated": {
    "title": "Изделие изолировано",
    "emitter": "nonconformity",
    "kind": "decision",
    "stream": "item",
    "axis": "none",
    "actionClass": "protective",
    "critical": true,
    "caGroup": "product_decision",
    "currentVersion": 1
  },
  "decision.lot.resolved": {
    "title": "Решение по партии на входном контроле",
    "emitter": "nonconformity",
    "kind": "decision",
    "stream": "lot",
    "axis": "none",
    "actionClass": "permissive",
    "critical": true,
    "caGroup": "product_decision",
    "currentVersion": 1
  },
  "decision.nonconformity.closed": {
    "title": "Несоответствие закрыто по изделию",
    "emitter": "nonconformity",
    "kind": "decision",
    "stream": "item",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "decision.nonconformity.confirmed": {
    "title": "Несоответствие подтверждено",
    "emitter": "nonconformity",
    "kind": "decision",
    "stream": "item",
    "axis": "none",
    "actionClass": "protective",
    "critical": true,
    "caGroup": "product_decision",
    "currentVersion": 1
  },
  "decision.nonconformity.drafted": {
    "title": "Черновик карточки несоответствия",
    "emitter": "nonconformity",
    "kind": "reaction",
    "stream": "item",
    "axis": "none",
    "actionClass": "protective",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "decision.nonconformity.registered": {
    "title": "Несоответствие зарегистрировано правилом",
    "emitter": "nonconformity",
    "kind": "reaction",
    "stream": "item",
    "axis": "none",
    "actionClass": "protective",
    "critical": true,
    "caGroup": "product_decision",
    "currentVersion": 1
  },
  "decision.presentation.resolved": {
    "title": "Решение на точке предъявления",
    "emitter": "nonconformity",
    "kind": "decision",
    "stream": "item",
    "axis": "none",
    "actionClass": "permissive",
    "critical": true,
    "caGroup": "product_decision",
    "currentVersion": 1
  },
  "decision.process_hold.released": {
    "title": "Остановка точки процесса снята",
    "emitter": "nonconformity",
    "kind": "decision",
    "stream": "equipment",
    "axis": "none",
    "actionClass": "permissive",
    "critical": true,
    "caGroup": "product_decision",
    "currentVersion": 1
  },
  "decision.process_hold.set": {
    "title": "Остановка точки процесса установлена",
    "emitter": "nonconformity",
    "kind": "decision",
    "stream": "equipment",
    "axis": "none",
    "actionClass": "protective",
    "critical": true,
    "caGroup": "product_decision",
    "currentVersion": 1
  },
  "decision.recheck.requested": {
    "title": "Назначена дополнительная проверка",
    "emitter": "nonconformity",
    "kind": "decision",
    "stream": "item",
    "axis": "containment",
    "actionClass": "protective",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "decision.rework_limit.waived": {
    "title": "Разрешено превысить лимит доработок",
    "emitter": "nonconformity",
    "kind": "decision",
    "stream": "item",
    "axis": "none",
    "actionClass": "permissive",
    "critical": true,
    "caGroup": "nc_decision",
    "currentVersion": 1
  },
  "decision.signal.rejected": {
    "title": "Сигнал отклонён",
    "emitter": "nonconformity",
    "kind": "decision",
    "stream": "item",
    "axis": "none",
    "actionClass": "permissive",
    "critical": true,
    "caGroup": "product_decision",
    "currentVersion": 1
  },
  "document.paper.status_changed": {
    "title": "Статус бумажного экземпляра",
    "emitter": "documents",
    "kind": "fact",
    "stream": "document",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "document.route.closed": {
    "title": "Маршрут подписей закрыт",
    "emitter": "documents",
    "kind": "reaction",
    "stream": "document",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "document.signature.recorded": {
    "title": "Подпись документа записана",
    "emitter": "documents",
    "kind": "decision",
    "stream": "document",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "document.version.annulled": {
    "title": "Версия документа аннулирована",
    "emitter": "documents",
    "kind": "decision",
    "stream": "document",
    "axis": "none",
    "actionClass": "record",
    "critical": true,
    "caGroup": "protected_data",
    "currentVersion": 1
  },
  "document.version.drafted": {
    "title": "Версия документа сформирована",
    "emitter": "documents",
    "kind": "reaction",
    "stream": "document",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "document.version.requested": {
    "title": "Запрошено оформление документа",
    "emitter": "documents",
    "kind": "decision",
    "stream": "document",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "equipment.cycle.summarized": {
    "title": "Сводка параметров за цикл",
    "emitter": "machinelogs",
    "kind": "fact",
    "stream": "equipment",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "equipment.deviation.detected": {
    "title": "Отклонение оборудования выделено",
    "emitter": "machinelogs",
    "kind": "fact",
    "stream": "equipment",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "equipment.program.changed": {
    "title": "Программа оборудования сменилась",
    "emitter": "machinelogs",
    "kind": "fact",
    "stream": "equipment",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "equipment.state.changed": {
    "title": "Состояние оборудования изменилось (v1)",
    "emitter": "machinelogs",
    "kind": "fact",
    "stream": "equipment",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 2
  },
  "equipment.tool.changed": {
    "title": "Инструмент установлен или заменён",
    "emitter": "machinelogs",
    "kind": "fact",
    "stream": "equipment",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "equipment.violation.window_resolved": {
    "title": "Окно нарушения режима определено",
    "emitter": "machinelogs",
    "kind": "reaction",
    "stream": "equipment",
    "axis": "none",
    "actionClass": "protective",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "erp.lot.received": {
    "title": "Партия поступила",
    "emitter": "erp",
    "kind": "fact",
    "stream": "lot",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "erp.nomenclature.synced": {
    "title": "Справочник номенклатуры получен",
    "emitter": "erp",
    "kind": "fact",
    "stream": "reference",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "erp.order.received": {
    "title": "Получено производственное задание",
    "emitter": "erp",
    "kind": "fact",
    "stream": "order",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "erp.posting.compensation_decided": {
    "title": "Решение об исправлении отправленного",
    "emitter": "erp",
    "kind": "decision",
    "stream": "erp_message",
    "axis": "none",
    "actionClass": "record",
    "critical": true,
    "caGroup": "protected_data",
    "currentVersion": 1
  },
  "erp.posting.quarantined": {
    "title": "Исходящее сообщение в карантине",
    "emitter": "erp",
    "kind": "service",
    "stream": "erp_message",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "erp.posting.requested": {
    "title": "Учётное сообщение сформировано",
    "emitter": "erp",
    "kind": "reaction",
    "stream": "erp_message",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "erp.posting.resend_requested": {
    "title": "Переотправка запрошена администратором",
    "emitter": "erp",
    "kind": "decision",
    "stream": "erp_message",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "erp.posting.responded": {
    "title": "Ответ учётной системы",
    "emitter": "erp",
    "kind": "fact",
    "stream": "erp_message",
    "axis": "erp_accounting",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "federation.extract.received": {
    "title": "Выписка паспорта партнёра принята",
    "emitter": "federation",
    "kind": "fact",
    "stream": "lot",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "federation.message.acknowledged": {
    "title": "Партнёр подтвердил получение",
    "emitter": "federation",
    "kind": "fact",
    "stream": "partner",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "federation.message.sent": {
    "title": "Межзаводское сообщение отправлено",
    "emitter": "federation",
    "kind": "service",
    "stream": "partner",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "federation.partner.registered": {
    "title": "Партнёр зарегистрирован",
    "emitter": "federation",
    "kind": "decision",
    "stream": "partner",
    "axis": "none",
    "actionClass": "permissive",
    "critical": true,
    "caGroup": "admin_security",
    "currentVersion": 1
  },
  "genealogy.group.dissolved": {
    "title": "Временная группа расформирована",
    "emitter": "crossitem",
    "kind": "fact",
    "stream": "group",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "genealogy.group.formed": {
    "title": "Временная группа сформирована",
    "emitter": "crossitem",
    "kind": "fact",
    "stream": "group",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "genealogy.link.added": {
    "title": "Связь генеалогии добавлена",
    "emitter": "crossitem",
    "kind": "reaction",
    "stream": "item",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "genealogy.lot.issued": {
    "title": "Партия выдана в производство",
    "emitter": "crossitem",
    "kind": "fact",
    "stream": "lot",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "genealogy.lot.registered": {
    "title": "Партия принята на входной контроль",
    "emitter": "crossitem",
    "kind": "fact",
    "stream": "lot",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "incident.action.assigned": {
    "title": "Мера назначена",
    "emitter": "analysis",
    "kind": "decision",
    "stream": "incident",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "incident.action.evaluated": {
    "title": "Результативность меры оценена",
    "emitter": "analysis",
    "kind": "decision",
    "stream": "incident",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "incident.action.implemented": {
    "title": "Мера внедрена",
    "emitter": "analysis",
    "kind": "decision",
    "stream": "incident",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "incident.analysis.scoped": {
    "title": "Решено, нужен ли полный разбор",
    "emitter": "analysis",
    "kind": "decision",
    "stream": "incident",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "incident.cause.concluded": {
    "title": "Вывод о причине",
    "emitter": "analysis",
    "kind": "decision",
    "stream": "incident",
    "axis": "none",
    "actionClass": "irreversible",
    "critical": true,
    "caGroup": "cause",
    "currentVersion": 1
  },
  "incident.hypothesis.computed": {
    "title": "Гипотезы и обстоятельства пересчитаны",
    "emitter": "analysis",
    "kind": "reaction",
    "stream": "item",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "incident.hypothesis.recorded": {
    "title": "Гипотеза причины записана человеком",
    "emitter": "analysis",
    "kind": "decision",
    "stream": "incident",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "incident.incident.closed": {
    "title": "Инцидент закрыт",
    "emitter": "analysis",
    "kind": "decision",
    "stream": "incident",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "incident.incident.opened": {
    "title": "Инцидент открыт",
    "emitter": "analysis",
    "kind": "reaction",
    "stream": "incident",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "incident.item.assessed": {
    "title": "Изделие в области проверено",
    "emitter": "analysis",
    "kind": "decision",
    "stream": "incident",
    "axis": "none",
    "actionClass": "permissive",
    "critical": true,
    "caGroup": "risk_scope",
    "currentVersion": 1
  },
  "incident.membership.changed": {
    "title": "Статус изделия в инциденте изменён",
    "emitter": "analysis",
    "kind": "reaction",
    "stream": "item",
    "axis": "incident",
    "actionClass": "protective",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "incident.operator_error.confirmed": {
    "title": "Ошибка исполнителя подтверждена",
    "emitter": "analysis",
    "kind": "decision",
    "stream": "incident",
    "axis": "none",
    "actionClass": "irreversible",
    "critical": true,
    "caGroup": "cause",
    "currentVersion": 1
  },
  "incident.scope.computed": {
    "title": "Новая версия области риска вычислена",
    "emitter": "analysis",
    "kind": "reaction",
    "stream": "incident",
    "axis": "none",
    "actionClass": "protective",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "incident.scope.expanded": {
    "title": "Область риска расширена человеком",
    "emitter": "analysis",
    "kind": "decision",
    "stream": "incident",
    "axis": "none",
    "actionClass": "protective",
    "critical": true,
    "caGroup": "risk_scope",
    "currentVersion": 1
  },
  "incident.scope.narrowed": {
    "title": "Область риска сужена",
    "emitter": "analysis",
    "kind": "decision",
    "stream": "incident",
    "axis": "none",
    "actionClass": "permissive",
    "critical": true,
    "caGroup": "risk_scope",
    "currentVersion": 1
  },
  "incident.suggestion.recorded": {
    "title": "Предложение записано",
    "emitter": "analysis",
    "kind": "fact",
    "stream": "global",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "ingest.anomaly.flagged": {
    "title": "Флаг аномалии входа",
    "emitter": "ingest",
    "kind": "service",
    "stream": "item",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "ingest.import.completed": {
    "title": "Импорт журнала завершён",
    "emitter": "ingest",
    "kind": "service",
    "stream": "source",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "ingest.message.quarantined": {
    "title": "Сообщение помещено в карантин",
    "emitter": "ingest",
    "kind": "service",
    "stream": "source",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "ingest.message.reprocessed": {
    "title": "Сообщение из карантина переобработано",
    "emitter": "ingest",
    "kind": "decision",
    "stream": "source",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "ingest.source.loss_suspected": {
    "title": "Возможна потеря данных источника",
    "emitter": "ingest",
    "kind": "reaction",
    "stream": "source",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "inspection.point.mode_changed": {
    "title": "Режим точки контроля изменён",
    "emitter": "quality",
    "kind": "fact",
    "stream": "equipment",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "inspection.result.recorded": {
    "title": "Результат контроля записан",
    "emitter": "quality",
    "kind": "fact",
    "stream": "item",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "item.assembly.recorded": {
    "title": "Компонент включён в сборку",
    "emitter": "item",
    "kind": "fact",
    "stream": "item",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "item.carrier.applied": {
    "title": "Носитель идентификатора нанесён",
    "emitter": "item",
    "kind": "fact",
    "stream": "item",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "item.carrier.removed": {
    "title": "Носитель снят",
    "emitter": "item",
    "kind": "fact",
    "stream": "item",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "item.carrier.verified": {
    "title": "Носитель проверен считыванием",
    "emitter": "item",
    "kind": "fact",
    "stream": "item",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "item.identification.confirmed": {
    "title": "Идентификация подтверждена человеком",
    "emitter": "item",
    "kind": "decision",
    "stream": "item",
    "axis": "none",
    "actionClass": "permissive",
    "critical": true,
    "caGroup": "protected_data",
    "currentVersion": 1
  },
  "item.identification.questioned": {
    "title": "Идентификация изделия под сомнением",
    "emitter": "item",
    "kind": "reaction",
    "stream": "item",
    "axis": "none",
    "actionClass": "protective",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "item.intervention.closed": {
    "title": "Вмешательство закрыто",
    "emitter": "item",
    "kind": "decision",
    "stream": "item",
    "axis": "none",
    "actionClass": "permissive",
    "critical": true,
    "caGroup": "product_decision",
    "currentVersion": 1
  },
  "item.intervention.opened": {
    "title": "Вмешательство в собранное изделие открыто",
    "emitter": "item",
    "kind": "decision",
    "stream": "item",
    "axis": "none",
    "actionClass": "protective",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "item.item.registered": {
    "title": "Изделие зарегистрировано и запущено в работу",
    "emitter": "item",
    "kind": "decision",
    "stream": "item",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "item.presentation.recorded": {
    "title": "Изделие предъявлено",
    "emitter": "item",
    "kind": "fact",
    "stream": "item",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "item.release.recorded": {
    "title": "Изделие сдано на склад готовой продукции",
    "emitter": "item",
    "kind": "fact",
    "stream": "item",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "journal.anchor.destroyed": {
    "title": "Ключ-якорь уничтожен",
    "emitter": "journal",
    "kind": "service",
    "stream": "global",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "journal.build.changed": {
    "title": "Сменилась сборка доменного пакета",
    "emitter": "journal",
    "kind": "service",
    "stream": "global",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "journal.checkpoint.recorded": {
    "title": "Контрольная точка хранителя",
    "emitter": "journal",
    "kind": "service",
    "stream": "global",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "journal.genesis.recorded": {
    "title": "Блок генезиса",
    "emitter": "journal",
    "kind": "service",
    "stream": "global",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "journal.restore.recorded": {
    "title": "Акт восстановления",
    "emitter": "journal",
    "kind": "decision",
    "stream": "global",
    "axis": "none",
    "actionClass": "record",
    "critical": true,
    "caGroup": "admin_security",
    "currentVersion": 1
  },
  "journal.segment.opened": {
    "title": "Открыт новый сегмент цепочки",
    "emitter": "journal",
    "kind": "service",
    "stream": "global",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "key.profile.registered": {
    "title": "Криптопрофиль зарегистрирован",
    "emitter": "signing",
    "kind": "service",
    "stream": "global",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "key.registration.recorded": {
    "title": "Ключ зарегистрирован актом",
    "emitter": "signing",
    "kind": "decision",
    "stream": "key",
    "axis": "none",
    "actionClass": "permissive",
    "critical": true,
    "caGroup": "admin_security",
    "currentVersion": 1
  },
  "key.revocation.recorded": {
    "title": "Ключ отозван",
    "emitter": "signing",
    "kind": "decision",
    "stream": "key",
    "axis": "none",
    "actionClass": "protective",
    "critical": true,
    "caGroup": "admin_security",
    "currentVersion": 1
  },
  "material.object.stored": {
    "title": "Материал помещён в хранилище",
    "emitter": "materials",
    "kind": "service",
    "stream": "global",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "mes.hold.requested": {
    "title": "Блокировка передаётся в MES",
    "emitter": "mes",
    "kind": "reaction",
    "stream": "erp_message",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "mes.hold.responded": {
    "title": "Ответ MES на блокировку",
    "emitter": "mes",
    "kind": "fact",
    "stream": "erp_message",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "mes.job.received": {
    "title": "Получено задание MES",
    "emitter": "mes",
    "kind": "fact",
    "stream": "order",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "normative.version.activated": {
    "title": "Версия процесса введена в действие",
    "emitter": "process",
    "kind": "decision",
    "stream": "process_version",
    "axis": "none",
    "actionClass": "irreversible",
    "critical": true,
    "caGroup": "control_change",
    "currentVersion": 1
  },
  "normative.version.loaded": {
    "title": "Стартовая версия нормативного слоя загружена",
    "emitter": "process",
    "kind": "service",
    "stream": "process_version",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "normative.version.retired": {
    "title": "Версия выведена",
    "emitter": "process",
    "kind": "decision",
    "stream": "process_version",
    "axis": "none",
    "actionClass": "record",
    "critical": true,
    "caGroup": "control_change",
    "currentVersion": 1
  },
  "normative.version.submitted": {
    "title": "Версия отправлена на утверждение",
    "emitter": "process",
    "kind": "decision",
    "stream": "process_version",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "obligation.due.cleared": {
    "title": "Срок снят",
    "emitter": "notifications",
    "kind": "reaction",
    "stream": "item",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "obligation.due.reached": {
    "title": "Наступил срок",
    "emitter": "notifications",
    "kind": "service",
    "stream": "item",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "obligation.due.set": {
    "title": "Срок установлен",
    "emitter": "notifications",
    "kind": "reaction",
    "stream": "item",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "obligation.escalation.raised": {
    "title": "Эскалация",
    "emitter": "notifications",
    "kind": "reaction",
    "stream": "item",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "operation.message.thrown": {
    "title": "Достигнуто событие-сообщение процесса",
    "emitter": "process",
    "kind": "reaction",
    "stream": "item",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "operation.movement.received": {
    "title": "Изделие принято на новом месте",
    "emitter": "process",
    "kind": "fact",
    "stream": "item",
    "axis": "position",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "operation.movement.sent": {
    "title": "Изделие отправлено",
    "emitter": "process",
    "kind": "fact",
    "stream": "item",
    "axis": "position",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "operation.precondition.failed": {
    "title": "Нарушено предусловие операции",
    "emitter": "process",
    "kind": "reaction",
    "stream": "item",
    "axis": "none",
    "actionClass": "protective",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "operation.run.finished": {
    "title": "Операция завершена",
    "emitter": "process",
    "kind": "fact",
    "stream": "item",
    "axis": "position",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "operation.run.interval_resolved": {
    "title": "Интервал выполнения операции определён",
    "emitter": "process",
    "kind": "reaction",
    "stream": "item",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "operation.run.paused": {
    "title": "Операция приостановлена",
    "emitter": "process",
    "kind": "fact",
    "stream": "item",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "operation.run.resumed": {
    "title": "Операция возобновлена",
    "emitter": "process",
    "kind": "fact",
    "stream": "item",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "operation.run.started": {
    "title": "Операция начата",
    "emitter": "process",
    "kind": "fact",
    "stream": "item",
    "axis": "position",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "operator.action.observed": {
    "title": "Действие исполнителя замечено (OperatorVision)",
    "emitter": "access",
    "kind": "fact",
    "stream": "item",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "operator.check.skipped": {
    "title": "Пропущена обязательная проверка",
    "emitter": "access",
    "kind": "fact",
    "stream": "item",
    "axis": "none",
    "actionClass": "record",
    "critical": true,
    "caGroup": "control_change",
    "currentVersion": 1
  },
  "operator.deviation.reported": {
    "title": "Исполнитель сообщил об отклонении",
    "emitter": "access",
    "kind": "fact",
    "stream": "item",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "operator.inspection.requested": {
    "title": "Исполнитель запросил контроль",
    "emitter": "access",
    "kind": "fact",
    "stream": "item",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "operator.mode.changed": {
    "title": "Исполнитель сменил режим оборудования",
    "emitter": "access",
    "kind": "fact",
    "stream": "item",
    "axis": "none",
    "actionClass": "record",
    "critical": true,
    "caGroup": "control_change",
    "currentVersion": 1
  },
  "operator.override.performed": {
    "title": "Ручное вмешательство в автоматику",
    "emitter": "access",
    "kind": "fact",
    "stream": "item",
    "axis": "none",
    "actionClass": "record",
    "critical": true,
    "caGroup": "control_change",
    "currentVersion": 1
  },
  "operator.step.confirmed": {
    "title": "Шаг подтверждён исполнителем",
    "emitter": "access",
    "kind": "fact",
    "stream": "item",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "ops.integration.degraded": {
    "title": "Интеграция в режиме degraded",
    "emitter": "ops",
    "kind": "service",
    "stream": "source",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "ops.processing.failed": {
    "title": "Сбой обработки изделия",
    "emitter": "ops",
    "kind": "service",
    "stream": "item",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "ops.processing.retried": {
    "title": "Повтор обработки запрошен",
    "emitter": "ops",
    "kind": "decision",
    "stream": "item",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "ops.source.disabled": {
    "title": "Источник отключён",
    "emitter": "ops",
    "kind": "decision",
    "stream": "source",
    "axis": "none",
    "actionClass": "protective",
    "critical": true,
    "caGroup": "admin_security",
    "currentVersion": 1
  },
  "ops.source.enabled": {
    "title": "Источник включён",
    "emitter": "ops",
    "kind": "decision",
    "stream": "source",
    "axis": "none",
    "actionClass": "permissive",
    "critical": true,
    "caGroup": "admin_security",
    "currentVersion": 1
  },
  "policy.audit.parameters_set": {
    "title": "Параметры аудита установлены",
    "emitter": "access",
    "kind": "decision",
    "stream": "policy",
    "axis": "none",
    "actionClass": "record",
    "critical": true,
    "caGroup": "admin_security",
    "currentVersion": 1
  },
  "policy.authority.granted": {
    "title": "Полномочие выдано",
    "emitter": "access",
    "kind": "decision",
    "stream": "policy",
    "axis": "none",
    "actionClass": "permissive",
    "critical": true,
    "caGroup": "authority",
    "currentVersion": 1
  },
  "policy.authority.revoked": {
    "title": "Полномочие отозвано",
    "emitter": "access",
    "kind": "decision",
    "stream": "policy",
    "axis": "none",
    "actionClass": "protective",
    "critical": true,
    "caGroup": "authority",
    "currentVersion": 1
  },
  "policy.role.assigned": {
    "title": "Роль назначена в области",
    "emitter": "access",
    "kind": "decision",
    "stream": "policy",
    "axis": "none",
    "actionClass": "permissive",
    "critical": true,
    "caGroup": "authority",
    "currentVersion": 1
  },
  "policy.role.defined": {
    "title": "Роль определена",
    "emitter": "access",
    "kind": "decision",
    "stream": "policy",
    "axis": "none",
    "actionClass": "record",
    "critical": true,
    "caGroup": "authority",
    "currentVersion": 1
  },
  "policy.role.unassigned": {
    "title": "Роль снята",
    "emitter": "access",
    "kind": "decision",
    "stream": "policy",
    "axis": "none",
    "actionClass": "protective",
    "critical": true,
    "caGroup": "authority",
    "currentVersion": 1
  },
  "policy.sod_rule.set": {
    "title": "Правило разделения обязанностей",
    "emitter": "access",
    "kind": "decision",
    "stream": "policy",
    "axis": "none",
    "actionClass": "record",
    "critical": true,
    "caGroup": "authority",
    "currentVersion": 1
  },
  "policy.stamp.issued": {
    "title": "Цифровое клеймо выдано",
    "emitter": "access",
    "kind": "decision",
    "stream": "policy",
    "axis": "none",
    "actionClass": "permissive",
    "critical": true,
    "caGroup": "authority",
    "currentVersion": 1
  },
  "policy.stamp.revoked": {
    "title": "Цифровое клеймо отозвано",
    "emitter": "access",
    "kind": "decision",
    "stream": "policy",
    "axis": "none",
    "actionClass": "protective",
    "critical": true,
    "caGroup": "authority",
    "currentVersion": 1
  },
  "quality.defect.identified": {
    "title": "Физический дефект установлен",
    "emitter": "quality",
    "kind": "reaction",
    "stream": "item",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "quality.escape.recorded": {
    "title": "Пропуск брака зафиксирован",
    "emitter": "quality",
    "kind": "reaction",
    "stream": "item",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "quality.inspection.auto_passed": {
    "title": "Уверенный результат пропущен к следующему контролю",
    "emitter": "quality",
    "kind": "reaction",
    "stream": "item",
    "axis": "none",
    "actionClass": "permissive",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "quality.inspection.missing": {
    "title": "Нет данных контроля",
    "emitter": "quality",
    "kind": "reaction",
    "stream": "item",
    "axis": "quality",
    "actionClass": "protective",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "quality.observation.linked": {
    "title": "Наблюдение связано с известным дефектом",
    "emitter": "quality",
    "kind": "reaction",
    "stream": "item",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "quality.signal.raised": {
    "title": "Сигнал о признаке дефекта или нарушении",
    "emitter": "quality",
    "kind": "reaction",
    "stream": "item",
    "axis": "quality",
    "actionClass": "protective",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "reference.calendar.defined": {
    "title": "Производственный календарь",
    "emitter": "reference",
    "kind": "decision",
    "stream": "reference",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "reference.change.affects_item": {
    "title": "Изменение справочника затрагивает изделие",
    "emitter": "reference",
    "kind": "reaction",
    "stream": "item",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "reference.equipment.defined": {
    "title": "Оборудование определено",
    "emitter": "reference",
    "kind": "decision",
    "stream": "reference",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "reference.equipment.verified": {
    "title": "Поверка или калибровка записана",
    "emitter": "reference",
    "kind": "decision",
    "stream": "reference",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "reference.external_id.mapped": {
    "title": "Соответствие внешнего идентификатора",
    "emitter": "reference",
    "kind": "fact",
    "stream": "reference",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "reference.item_type.defined": {
    "title": "Тип изделия определён",
    "emitter": "reference",
    "kind": "decision",
    "stream": "reference",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "reference.location.defined": {
    "title": "Место определено",
    "emitter": "reference",
    "kind": "decision",
    "stream": "reference",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "reference.shift.scheduled": {
    "title": "График смен",
    "emitter": "reference",
    "kind": "decision",
    "stream": "reference",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "security.access.denied": {
    "title": "Отказ в доступе",
    "emitter": "security",
    "kind": "service",
    "stream": "global",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "security.admission.denied": {
    "title": "Отказ в допуске к рабочему месту",
    "emitter": "security",
    "kind": "service",
    "stream": "workplace",
    "axis": "none",
    "actionClass": "record",
    "critical": true,
    "caGroup": "admin_security",
    "currentVersion": 1
  },
  "security.auth.failed": {
    "title": "Неудачный вход",
    "emitter": "security",
    "kind": "service",
    "stream": "global",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "security.critical_action.recorded": {
    "title": "Критическое действие",
    "emitter": "security",
    "kind": "service",
    "stream": "global",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "security.idempotency.conflict": {
    "title": "Конфликт идемпотентности",
    "emitter": "security",
    "kind": "service",
    "stream": "source",
    "axis": "none",
    "actionClass": "record",
    "critical": true,
    "caGroup": "admin_security",
    "currentVersion": 1
  },
  "security.integrity.checked": {
    "title": "Отчёт верификатора получен",
    "emitter": "security",
    "kind": "service",
    "stream": "global",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "security.integrity.violated": {
    "title": "Нарушение целостности обнаружено",
    "emitter": "security",
    "kind": "service",
    "stream": "global",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "security.keeper.alert": {
    "title": "Тревога хранителя",
    "emitter": "security",
    "kind": "service",
    "stream": "global",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "security.key.alert": {
    "title": "Тревога по ключу",
    "emitter": "security",
    "kind": "service",
    "stream": "key",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "security.presence.deviation": {
    "title": "Отклонение присутствия",
    "emitter": "security",
    "kind": "service",
    "stream": "workplace",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "security.signature.invalid": {
    "title": "Недействительная подпись",
    "emitter": "security",
    "kind": "service",
    "stream": "global",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "simulation.injection.applied": {
    "title": "Инъекция цифрового стенда",
    "emitter": "simulation",
    "kind": "service",
    "stream": "run",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "simulation.run.finished": {
    "title": "Прогон завершён",
    "emitter": "simulation",
    "kind": "service",
    "stream": "run",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "simulation.run.paused": {
    "title": "Прогон на паузе",
    "emitter": "simulation",
    "kind": "service",
    "stream": "run",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "simulation.run.resumed": {
    "title": "Прогон продолжен",
    "emitter": "simulation",
    "kind": "service",
    "stream": "run",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "simulation.run.started": {
    "title": "Прогон сценария запущен",
    "emitter": "simulation",
    "kind": "service",
    "stream": "run",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "task.notification.sent": {
    "title": "Уведомление",
    "emitter": "notifications",
    "kind": "reaction",
    "stream": "item",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "task.notification.withdrawn": {
    "title": "Уведомление отозвано",
    "emitter": "notifications",
    "kind": "reaction",
    "stream": "item",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "task.task.acknowledged": {
    "title": "Задача подтверждена",
    "emitter": "notifications",
    "kind": "decision",
    "stream": "item",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "task.task.created": {
    "title": "Задача поставлена",
    "emitter": "notifications",
    "kind": "reaction",
    "stream": "item",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "task.task.withdrawn": {
    "title": "Задача снята",
    "emitter": "notifications",
    "kind": "reaction",
    "stream": "item",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "time.clock.mode_set": {
    "title": "Режим часов установлен",
    "emitter": "journal",
    "kind": "service",
    "stream": "global",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  },
  "time.clock.ticked": {
    "title": "Тик виртуальных часов сценария",
    "emitter": "simulation",
    "kind": "service",
    "stream": "run",
    "axis": "none",
    "actionClass": "record",
    "critical": false,
    "caGroup": null,
    "currentVersion": 1
  }
} as const

/** Тип записи журнала `семейство.сущность.действие`. */
export type EventType = keyof typeof eventCatalog
