// Code generated by backend/tools/contractgen; DO NOT EDIT.
// Источник: contracts/journal (make generate). Руками не править (AD-20).

// Пакет journal — Go-тип записи журнала (AD-44): открытые поля, звено цепочки, обязательство; им пользуются все, включая верификатор.
//
// Слой: сгенерированные контракты — чистые данные; доступны домену (AD-1).
package journal
