// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.
// Источник: contracts/journal/entry.schema.json (make generate). Руками не править (AD-20).

package journal

import crypto "ant/internal/contracts/crypto"

// Запись журнала v1 (AD-44): открытый заголовок (маршрутизация, время, тип,
// изделие, правило, слот, обязательство и звено) и зашифрованный блок с исходным
// конвертом DSSE и salt (AD-23). Go-типы генерируются и используются всеми,
// включая верификатор. Формат цепочки — chain-format.v1.md.
type JournalEntry struct {
	// Реакции — основание пачки; решения — позиция журнала, на которой проверен гард
	// (AD-39).
	BasisSeq *int `json:"basis_seq,omitempty,omitzero"`

	// Значение носителя из item_ref источника: `‹тип›:‹значение›` (AD-41).
	CarrierRef *string `json:"carrier_ref,omitempty,omitzero"`

	// Непосредственная причина; null у корневой записи.
	CausationID JournalEntryCausationID `json:"causation_id"`

	// Цепочка: основной журнал или журнал критических действий (AD-8).
	Chain JournalEntryChain `json:"chain"`

	// Обязательство: H(salt ‖ JCS(конверт DSSE)) (AD-23, AD-44).
	Commit string `json:"commit"`

	// Реальное время фиксации (InfraClock), не убывает по seq, покрыто контрольными
	// точками.
	CommittedAt string `json:"committed_at"`

	// Сквозная цепочка.
	CorrelationID string `json:"correlation_id"`

	// Хеш доменного пакета, свернувшего запись (AD-9).
	DomainBuild string `json:"domain_build"`

	// Вид записи (AD-2); совпадает с каталогом для event_type.
	EntryKind JournalEntryEntryKind `json:"entry_kind"`

	// event_id из конверта: UUIDv7; у реакций, производных и событий сценария —
	// UUIDv5.
	EventID string `json:"event_id"`

	// Тип записи из catalog.yaml.
	EventType string `json:"event_type"`

	// Внутренний ID изделия — только внутренний (AD-41).
	ItemID *string `json:"item_id,omitempty,omitzero"`

	// Звено: H(prev_link ‖ commit ‖ H(JCS(открытые поля без link))) (AD-44).
	Link string `json:"link"`

	// Ревизия нормативного слоя, по которой исполнено (хеш версии процесса или
	// номер).
	NormativeRev *string `json:"normative_rev,omitempty,omitzero"`

	// Время возникновения (из конверта; для решений и реакций ставит ядро, AD-37).
	OccurredAt string `json:"occurred_at"`

	// Партиция: hash(item_id) mod P; для записей вне изделия — партиция стадии.
	Partition int `json:"partition"`

	// Ревизия политики доступа, по которой проверена команда (AD-39).
	PolicySeq *int `json:"policy_seq,omitempty,omitzero"`

	// Класс происхождения подписи (AD-2).
	ProvenanceClass JournalEntryProvenanceClass `json:"provenance_class"`

	// Слот реакции (AD-3).
	ReactionSlot *JournalEntryReactionSlot `json:"reaction_slot,omitempty,omitzero"`

	// Время поступления в приём — ставит только ядро.
	ReceivedAt string `json:"received_at"`

	// Доменное время записи (DomainClock), не убывает по seq (AD-37).
	RecordedAt string `json:"recorded_at"`

	// Правило реакции (AD-3).
	RuleID *string `json:"rule_id,omitempty,omitzero"`

	// Прогон сценария (AD-38).
	RunID *string `json:"run_id,omitempty,omitzero"`

	// Мажорная версия схемы data в исходном конверте (повышатели применяются при
	// чтении, AD-20).
	SchemaVersion int `json:"schema_version"`

	// Sealed corresponds to the JSON schema field "sealed".
	Sealed SealedBlock `json:"sealed"`

	// Позиция в своей цепочке (`chain`): порядок знания (AD-37); для ca — номер
	// CA-‹n›.
	Seq int `json:"seq"`

	// Источник.
	SourceID string `json:"source_id"`

	// Номер у источника.
	SourceSeq *int `json:"source_seq,omitempty,omitzero"`

	// Поток (AD-39): `item:‹item_id›`, `‹вид›:‹id›` или `global`.
	Stream string `json:"stream"`

	// Заменяемая версия слота.
	Supersedes JournalEntrySupersedes `json:"supersedes,omitempty,omitzero"`

	// Версия слота реакции.
	Version *int `json:"version,omitempty,omitzero"`
}

// Непосредственная причина; null у корневой записи.
type JournalEntryCausationID *string

type JournalEntryChain string

const JournalEntryChainCa JournalEntryChain = "ca"
const JournalEntryChainMain JournalEntryChain = "main"

type JournalEntryEntryKind string

const JournalEntryEntryKindDecision JournalEntryEntryKind = "decision"
const JournalEntryEntryKindFact JournalEntryEntryKind = "fact"
const JournalEntryEntryKindReaction JournalEntryEntryKind = "reaction"
const JournalEntryEntryKindService JournalEntryEntryKind = "service"

type JournalEntryProvenanceClass string

const JournalEntryProvenanceClassDevice JournalEntryProvenanceClass = "device"
const JournalEntryProvenanceClassGenesis JournalEntryProvenanceClass = "genesis"
const JournalEntryProvenanceClassPaper JournalEntryProvenanceClass = "paper"
const JournalEntryProvenanceClassPartner JournalEntryProvenanceClass = "partner"
const JournalEntryProvenanceClassPersonal JournalEntryProvenanceClass = "personal"
const JournalEntryProvenanceClassScenario JournalEntryProvenanceClass = "scenario"
const JournalEntryProvenanceClassServerAttested JournalEntryProvenanceClass = "server_attested"

// Слот реакции (AD-3).
type JournalEntryReactionSlot struct {
	// Правило.
	RuleID string `json:"rule_id"`

	// Субъект — поток.
	Subject string `json:"subject"`

	// Ключ срабатывания.
	TriggerKey string `json:"trigger_key"`
}

// Заменяемая версия слота.
type JournalEntrySupersedes *string

// Содержимое после расшифрования; после него всегда проверяется commit.
type PlainBlock struct {
	// Envelope corresponds to the JSON schema field "envelope".
	Envelope crypto.DsseEnvelope `json:"envelope"`

	// 128 случайных бит на запись.
	SaltB64 string `json:"salt_b64"`
}

// Зашифрованный блок (AD-23): AEAD над JCS(plain_block); доп. данные — chain ‖ seq
// ‖ commit.
type SealedBlock struct {
	// Алгоритм AEAD: «Кузнечик»-MGM (ГОСТ) или AES-256-GCM.
	Aead SealedBlockAead `json:"aead"`

	// Шифротекст с тегом.
	CiphertextB64 string `json:"ciphertext_b64"`

	// Ключ шифрования данных; обёртки — journal.dek_wraps.
	DekID string `json:"dek_id"`

	// Нонс.
	NonceB64 string `json:"nonce_b64"`
}

type SealedBlockAead string

const SealedBlockAeadAes256Gcm SealedBlockAead = "aes_256_gcm"
const SealedBlockAeadKuznyechikMgm SealedBlockAead = "kuznyechik_mgm"
