// Code generated by backend/tools/contractgen; DO NOT EDIT.
// Источник: contracts/problem.schema.json (make generate). Руками не править (AD-20).

// Пакет problem — Go-тип тела ошибки RFC 9457 problem+json с расширениями ant (FR-28).
//
// Слой: сгенерированные контракты — чистые данные; доступны домену (AD-1).
package problem
