// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.
// Источник: contracts/problem.schema.json (make generate). Руками не править (AD-20).

package problem

// Тело ответа об ошибке — RFC 9457 `application/problem+json` с расширениями ant.
// Код — из contracts/errors.yaml.
type Problem struct {
	// Что пользователь может сделать вместо: например, «Запросить решение» (FR-146).
	AllowedActions []string `json:"allowed_actions,omitempty,omitzero"`

	// Для journal.stale_*: на каком seq проверено.
	BasisSeq *int `json:"basis_seq,omitempty,omitzero"`

	// Критическое действие, записанное из-за отказа (FR-19).
	CaRef *string `json:"ca_ref,omitempty,omitzero"`

	// Код из contracts/errors.yaml.
	Code string `json:"code"`

	// Пояснение по-русски для этого случая.
	Detail *string `json:"detail,omitempty,omitzero"`

	// URI конкретного случая (путь запроса или id записи карантина).
	Instance *string `json:"instance,omitempty,omitzero"`

	// Параметры шаблона текста интерфейса.
	Params ProblemParams `json:"params,omitempty,omitzero"`

	// Запись карантина (FR-30).
	QuarantineID *string `json:"quarantine_id,omitempty,omitzero"`

	// HTTP-статус.
	Status int `json:"status"`

	// Краткий заголовок по-русски (из каталога).
	Title string `json:"title"`

	// URI типа проблемы: urn:ant:problem:‹код›.
	Type string `json:"type"`

	// Нарушения по полям или элементам.
	Violations []ProblemViolationsElem `json:"violations,omitempty,omitzero"`
}

// Параметры шаблона текста интерфейса.
type ProblemParams map[string]string

type ProblemViolationsElem struct {
	// Код нарушения.
	Code string `json:"code"`

	// Идентификатор элемента BPMN.
	ElementID *string `json:"element_id,omitempty,omitzero"`

	// JSON Pointer поля.
	Field *string `json:"field,omitempty,omitzero"`

	// Пояснение.
	Message *string `json:"message,omitempty,omitzero"`
}
