// Code generated by backend/tools/contractgen; DO NOT EDIT.
// Источник: contracts/events/upcasters/*.yaml (make generate). Руками не править (AD-20).

// Пакет upcast — повышатели версий данных событий (AD-20, FR-110): чистые функции
// над разобранным JSON-объектом поля data. Журнал хранит исходный конверт без
// изменений; повышение применяют при чтении воркер, воспроизведение и верификатор.
// Чего нет в старой версии — «unknown»; смысл не додумывается (FR-123).
//
// Слой: сгенерированные контракты — чистые функции без ввода-вывода; доступны домену.
package upcast

import (
	"fmt"
	"strings"
)

// Step — один шаг повышения типа from → from+1.
type Step struct {
	EventType string
	From, To  int
	Fn        func(map[string]any) map[string]any
}

// EquipmentStateChangedV1ToV2 — equipment.state.changed v1 → v2 (contracts/events/upcasters/equipment.state.changed.v1-to-v2.yaml).
func EquipmentStateChangedV1ToV2(in map[string]any) map[string]any {
	out := clone(in)
	switch v, _ := getPath(in, "/machine_state").(string); v {
	case "running":
		setPath(out, "/execution", "running")
		setPath(out, "/condition", "normal")
	case "idle":
		setPath(out, "/execution", "idle")
		setPath(out, "/condition", "normal")
	case "stopped":
		setPath(out, "/execution", "stopped")
		setPath(out, "/condition", "normal")
	case "warning":
		setPath(out, "/execution", "unknown")
		setPath(out, "/condition", "warning")
	case "alarm":
		setPath(out, "/execution", "unknown")
		setPath(out, "/condition", "fault")
	default:
		setPath(out, "/execution", "unknown")
		setPath(out, "/condition", "unknown")
	}
	deletePath(out, "/machine_state")
	setPath(out, "/controller_mode", "unknown")
	return out
}

// steps — все шаги повышения, по типу и версии.
var steps = [...]Step{
	{EventType: "equipment.state.changed", From: 1, To: 2, Fn: EquipmentStateChangedV1ToV2},
}

// Steps возвращает все шаги повышения.
func Steps() []Step { return steps[:] }

// Upcast повышает data типа eventType с версии from до версии to цепочкой шагов.
// Нет шага — ошибка (приём: карантин ingest.unknown_schema_version, AD-20).
func Upcast(eventType string, from, to int, data map[string]any) (map[string]any, error) {
	for v := from; v < to; v++ {
		found := false
		for _, s := range steps {
			if s.EventType == eventType && s.From == v {
				data = s.Fn(data)
				found = true
				break
			}
		}
		if !found {
			return nil, fmt.Errorf("upcast: нет повышателя %s v%d → v%d", eventType, v, v+1)
		}
	}
	return data, nil
}

func clone(in map[string]any) map[string]any {
	out := make(map[string]any, len(in))
	for k, v := range in {
		if m, ok := v.(map[string]any); ok {
			v = clone(m)
		}
		out[k] = v
	}
	return out
}

func split(p string) []string { return strings.Split(strings.TrimPrefix(p, "/"), "/") }

func getPath(m map[string]any, p string) any {
	parts := split(p)
	var cur any = m
	for _, k := range parts {
		mm, ok := cur.(map[string]any)
		if !ok {
			return nil
		}
		cur = mm[k]
	}
	return cur
}

func setPath(m map[string]any, p string, v any) {
	parts := split(p)
	for _, k := range parts[:len(parts)-1] {
		next, ok := m[k].(map[string]any)
		if !ok {
			next = map[string]any{}
			m[k] = next
		}
		m = next
	}
	m[parts[len(parts)-1]] = v
}

func deletePath(m map[string]any, p string) {
	parts := split(p)
	for _, k := range parts[:len(parts)-1] {
		next, ok := m[k].(map[string]any)
		if !ok {
			return
		}
		m = next
	}
	delete(m, parts[len(parts)-1])
}
