// Code generated by backend/tools/contractgen; DO NOT EDIT.
// Источник: contracts/constants.yaml (make generate). Руками не править (AD-20).

// Пакет constants — константы контракта v1: NS_ANT, URI расширения BPMN, шаблоны
// payloadType и QR, формат цепочки (AD-3, AD-10, AD-17, AD-44).
//
// Слой: сгенерированные контракты — чистые данные; доступны домену (AD-1).
package constants

const (
	// Пространство имён UUIDv5 системы (AD-3, «Соглашения/Идентификаторы»):
	//   reaction_id = UUIDv5(NS_ANT, слот ‖ версия); производные id — UUIDv5 от NS_ANT.
	// Значение зафиксировано как UUIDv5(NAMESPACE_URL, "urn:ant:ns:1") и больше не меняется.
	NsAnt = "4b82fbf1-fc9e-5a06-91c6-8c100ebac4ef"
	// Пространство имён расширения BPMN (AD-17); дескриптор — contracts/bpmn-ext/ant.json.
	BpmnExtUri    = "urn:ant:bpmn-ext:1"
	BpmnExtPrefix = "ant"
	// payloadType пакета DSSE (AD-10): application/vnd.ant.‹класс›+json; v=‹версия›.
	// Классы — contracts/crypto/payload-classes.yaml.
	PayloadTypeTemplate = "application/vnd.ant.{class}+json; v={version}"
	// Контекстная строка ML-DSA для профиля pq: "ant/" + payloadType (AD-10).
	MldsaContextTemplate = "ant/{payload_type}"
	// QR (соглашения): документ и носитель.
	QrDocumentTemplate = "ant:doc:{doc_id}:{doc_digest}"
	QrCarrierTemplate  = "ant:carrier:{carrier_type}:{value}"
	// Формат цепочки журнала v1 (AD-44): H = Стрибог-256, префикс отпечатков — streebog256.
	ChainFormatVersion = 1
	HashAlgorithm      = "streebog256"
	DigestPrefix       = "streebog256:"
	// Базовый URI идентификаторов схем ($id). Домен .invalid зарезервирован (RFC 2606) —
	// схемы по сети никогда не загружаются, $id лишь повторяет путь файла от contracts/.
	SchemaBaseUri = "https://ant.invalid/contracts/"
	// Тип проблемы RFC 9457: urn:ant:problem:‹код› (коды — contracts/errors.yaml).
	ProblemTypePrefix = "urn:ant:problem:"
	// Время: RFC 3339 UTC, ровно три знака после секунд.
	TimestampPattern = "^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\\.[0-9]{3}Z$"
	// Целые в подписываемом JSON — в пределах ±(2^53−1) (AD-10); большие — строками.
	MaxSafeInteger = 9007199254740991
)
