// Code generated by backend/tools/contractgen; DO NOT EDIT.
// Источник: contracts/internal (make generate). Руками не править (AD-20).

// Пакет procs — Go-типы контрактов собственных процессов (AD-46): сообщения агента токена, сменный рапорт, отчёт верификатора, телеметрия stand-ов.
//
// Слой: сгенерированные контракты — чистые данные; доступны домену (AD-1).
package procs
