// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.
// Источник: contracts/internal/{token-agent,verifier,stands}/*.json (make generate). Руками не править (AD-20).

package procs

import crypto "ant/internal/contracts/crypto"

// Сменный рапорт — уровень подписи 3 (AD-12, AD-13): одна подпись над корнем
// дерева Меркла RFC 6962 по отпечаткам подписей смены из локального журнала
// агента; счётчики по типам. Класс пакета `shift-report`. Закрытая схема.
type ShiftReportV1 struct {
	// Сколько подписей каждого типа.
	CountsByType ShiftReportV1CountsByType `json:"counts_by_type"`

	// Профиль.
	CryptoProfile ShiftReportV1CryptoProfile `json:"crypto_profile"`

	// Первый номер локального журнала в окне.
	FirstLocalSeq *int `json:"first_local_seq,omitempty,omitzero"`

	// Версия формата.
	FormatVersion int `json:"format_version"`

	// Последний номер.
	LastLocalSeq *int `json:"last_local_seq,omitempty,omitzero"`

	// Число листьев.
	LeafCount int `json:"leaf_count"`

	// Корень: лист H(0x00‖отпечаток подписи), узел H(0x01‖l‖r), листья в порядке
	// подписания.
	MerkleRoot string `json:"merkle_root"`

	// Подписант.
	PersonID string `json:"person_id"`

	// Последняя известная агенту контрольная точка.
	SeenCheckpoint *int `json:"seen_checkpoint,omitempty,omitzero"`

	// Смена.
	ShiftID string `json:"shift_id"`

	// Подписанты.
	Signers []string `json:"signers"`

	// Начало окна.
	WindowFrom string `json:"window_from"`

	// Конец окна.
	WindowTo string `json:"window_to"`

	// Рабочее место.
	WorkplaceID *string `json:"workplace_id,omitempty,omitzero"`
}

// Сколько подписей каждого типа.
type ShiftReportV1CountsByType map[string]int

type ShiftReportV1CryptoProfile string

const ShiftReportV1CryptoProfileGost ShiftReportV1CryptoProfile = "gost"
const ShiftReportV1CryptoProfileHybrid ShiftReportV1CryptoProfile = "hybrid"

// Запрос одной подписи: агент сам разбирает содержимое, сам считает отпечаток
// пакетом domain/documents и сам вычисляет поля сводки (AD-14).
type SignBlock struct {
	// Версия формата документа; неизвестную агент отвергает
	// (signing.unknown_doc_format).
	DocFormatVersion *int `json:"doc_format_version,omitempty,omitzero"`

	// Тип события-команды (для проверки перечня уровня 1).
	EventType *string `json:"event_type,omitempty,omitzero"`

	// Отпечаток, который ожидает сервер; агент сверяет со своим.
	ExpectedDocDigest *string `json:"expected_doc_digest,omitempty,omitzero"`

	// Ключ, которым просят подписать.
	KeyRef *string `json:"key_ref,omitempty,omitzero"`

	// Уровень подписи 1–2; уровень 1 — только типы из level1-actions.yaml, иначе
	// агент отклоняет сам.
	Level int `json:"level"`

	// Каноническое содержимое (base64): событие-команда или содержимое документа.
	PayloadB64 string `json:"payload_b64"`

	// payloadType пакета.
	PayloadType string `json:"payload_type"`

	// Шаблон документа `‹id›@‹версия›`, если подписывается документ.
	TemplateRef *string `json:"template_ref,omitempty,omitzero"`
}

// Сообщение stand-а оборудования (станок ЧПУ, сварочный источник, стенд) →
// edge-агенту (AD-18, AD-46, FR-149): отсчёты и события по классификации
// MTConnect. Сырые отсчёты остаются на краю; в ant уходят события и сводки на окно
// цикла (`equipment.*`). Закрытая схема.
type StandTelemetryV1 struct {
	// Маркер цикла.
	Cycle *StandTelemetryV1Cycle `json:"cycle,omitempty,omitzero"`

	// Оборудование.
	EquipmentID string `json:"equipment_id"`

	// События.
	Events []StandTelemetryV1EventsElem `json:"events,omitempty,omitzero"`

	// Прогон сценария.
	RunID *string `json:"run_id,omitempty,omitzero"`

	// Отсчёты.
	Samples []StandTelemetryV1SamplesElem `json:"samples,omitempty,omitzero"`

	// Доменное время сценария.
	SentAt string `json:"sent_at"`

	// Номер сообщения stand-а.
	Seq int `json:"seq"`

	// Уставки параметров выполняемой программы (задание режима: WPS сварки,
	// запрограммированные подача и нагрузка ЧПУ) — сообщает источник в начале цикла;
	// по ним edge-агент выделяет выход за уставку (FR-147).
	Setpoints []StandTelemetryV1SetpointsElem `json:"setpoints,omitempty,omitzero"`

	// Идентификатор stand-а.
	StandID string `json:"stand_id"`
}

// Маркер цикла.
type StandTelemetryV1Cycle struct {
	// Цикл.
	CycleRef string `json:"cycle_ref"`

	// Фаза.
	Phase StandTelemetryV1CyclePhase `json:"phase"`
}

type StandTelemetryV1CyclePhase string

const StandTelemetryV1CyclePhaseEnd StandTelemetryV1CyclePhase = "end"
const StandTelemetryV1CyclePhaseStart StandTelemetryV1CyclePhase = "start"

// Событие EVENT/CONDITION.
type StandTelemetryV1EventsElem struct {
	// Время.
	At string `json:"at"`

	// Категория: режим работы, режим управления, исправность, программа, инструмент,
	// цикл, авария, коррекция режима оператором (override: value — проценты, code —
	// что корректируется: feed, spindle, rapid, current).
	Category StandTelemetryV1EventsElemCategory `json:"category"`

	// Код.
	Code *string `json:"code,omitempty,omitzero"`

	// Ресурс инструмента: допустимо.
	ToolLifeLimit *int `json:"tool_life_limit,omitempty,omitzero"`

	// Ресурс инструмента: сделано.
	ToolLifeUsed *int `json:"tool_life_used,omitempty,omitzero"`

	// Значение (например, running, manual, warning, программа, инструмент).
	Value string `json:"value"`
}

type StandTelemetryV1EventsElemCategory string

const StandTelemetryV1EventsElemCategoryAlarm StandTelemetryV1EventsElemCategory = "alarm"
const StandTelemetryV1EventsElemCategoryCondition StandTelemetryV1EventsElemCategory = "condition"
const StandTelemetryV1EventsElemCategoryControllerMode StandTelemetryV1EventsElemCategory = "controller_mode"
const StandTelemetryV1EventsElemCategoryCycle StandTelemetryV1EventsElemCategory = "cycle"
const StandTelemetryV1EventsElemCategoryExecution StandTelemetryV1EventsElemCategory = "execution"
const StandTelemetryV1EventsElemCategoryOverride StandTelemetryV1EventsElemCategory = "override"
const StandTelemetryV1EventsElemCategoryProgram StandTelemetryV1EventsElemCategory = "program"
const StandTelemetryV1EventsElemCategoryTool StandTelemetryV1EventsElemCategory = "tool"

// Отсчёт SAMPLE.
type StandTelemetryV1SamplesElem struct {
	// Время.
	At string `json:"at"`

	// Параметр.
	Parameter string `json:"parameter"`

	// Масштаб.
	Scale int `json:"scale"`

	// Единица UCUM.
	Unit string `json:"unit"`

	// Мантисса.
	Value int `json:"value"`
}

// Уставка параметра: номинал и границы в масштабе и единице отсчёта.
type StandTelemetryV1SetpointsElem struct {
	// Нижняя граница, мантисса; нет — не ограничена.
	Lower *int `json:"lower,omitempty,omitzero"`

	// Номинал, мантисса.
	Nominal *int `json:"nominal,omitempty,omitzero"`

	// Параметр (как в отсчётах).
	Parameter string `json:"parameter"`

	// Масштаб.
	Scale int `json:"scale"`

	// Единица UCUM.
	Unit string `json:"unit"`

	// Верхняя граница, мантисса; нет — не ограничена.
	Upper *int `json:"upper,omitempty,omitzero"`
}

// Сообщение браузерного расширения → агенту токена по Native Messaging (AD-14,
// AD-46). Вид — поле `type`; для каждого вида обязателен свой блок (без oneOf,
// диалект AD-20). Хост Native Messaging — тонкий посредник; PIN вводится только в
// окне агента, никогда на странице.
type TokenAgentRequestV1 struct {
	// Запрос выписки локального журнала подписанного.
	LocalJournal *TokenAgentRequestV1LocalJournal `json:"local_journal,omitempty,omitzero"`

	// Origin страницы ant, от которой пришёл запрос (проверяет расширение).
	Origin string `json:"origin"`

	// Версия протокола.
	ProtocolVersion int `json:"protocol_version"`

	// Идентификатор запроса расширения.
	RequestID string `json:"request_id"`

	// Запрос сменного рапорта (уровень 3).
	ShiftReport *TokenAgentRequestV1ShiftReport `json:"shift_report,omitempty,omitzero"`

	// Sign corresponds to the JSON schema field "sign".
	Sign *SignBlock `json:"sign,omitempty,omitzero"`

	// Пачка однородных подписей уровня 2: «подписать: N изделий, операция X, годен» —
	// одно окно, одно касание токена (AD-13).
	SignBatch []SignBlock `json:"sign_batch,omitempty,omitzero"`

	// Вид запроса.
	Type TokenAgentRequestV1Type `json:"type"`
}

// Запрос выписки локального журнала подписанного.
type TokenAgentRequestV1LocalJournal struct {
	// С какого номера локального журнала.
	SinceSeq int `json:"since_seq"`
}

// Запрос сменного рапорта (уровень 3).
type TokenAgentRequestV1ShiftReport struct {
	// Смена.
	ShiftID string `json:"shift_id"`

	// Начало окна.
	WindowFrom string `json:"window_from"`

	// Конец окна.
	WindowTo string `json:"window_to"`
}

type TokenAgentRequestV1Type string

const TokenAgentRequestV1TypeHello TokenAgentRequestV1Type = "hello"
const TokenAgentRequestV1TypeLocalJournal TokenAgentRequestV1Type = "local_journal"
const TokenAgentRequestV1TypeShiftReport TokenAgentRequestV1Type = "shift_report"
const TokenAgentRequestV1TypeSign TokenAgentRequestV1Type = "sign"
const TokenAgentRequestV1TypeSignBatch TokenAgentRequestV1Type = "sign_batch"
const TokenAgentRequestV1TypeStatus TokenAgentRequestV1Type = "status"

// Ответ агента токена расширению по Native Messaging (AD-14, AD-46). Вид — поле
// `type`.
type TokenAgentResponseV1 struct {
	// Отказ агента.
	Error *TokenAgentResponseV1Error `json:"error,omitempty,omitzero"`

	// Приветствие агента.
	Hello *TokenAgentResponseV1Hello `json:"hello,omitempty,omitzero"`

	// Локальный журнал подписанного.
	LocalJournal []TokenAgentResponseV1LocalJournalElem `json:"local_journal,omitempty,omitzero"`

	// Версия протокола.
	ProtocolVersion int `json:"protocol_version"`

	// Запрос, на который ответ.
	RequestID string `json:"request_id"`

	// ShiftReport corresponds to the JSON schema field "shift_report".
	ShiftReport *ShiftReportV1 `json:"shift_report,omitempty,omitzero"`

	// Подписанные пакеты (один или пачка).
	Signed []TokenAgentResponseV1SignedElem `json:"signed,omitempty,omitzero"`

	// Состояние токена.
	Status *TokenAgentResponseV1Status `json:"status,omitempty,omitzero"`

	// Вид ответа.
	Type TokenAgentResponseV1Type `json:"type"`
}

// Отказ агента.
type TokenAgentResponseV1Error struct {
	// Код из contracts/errors.yaml (например, signing.level_not_allowed,
	// signing.token_missing).
	Code string `json:"code"`

	// Пояснение.
	Message *string `json:"message,omitempty,omitzero"`
}

// Приветствие агента.
type TokenAgentResponseV1Hello struct {
	// Версия агента.
	AgentVersion string `json:"agent_version"`

	// Хеш сборки: агент, сервер и demo-signer — из одного коммита (AD-12).
	BuildDigest string `json:"build_digest"`

	// Поддерживаемые версии формата документа.
	DocFormatVersions []int `json:"doc_format_versions"`

	// Ключи.
	Keys []TokenAgentResponseV1HelloKeysElem `json:"keys"`
}

// Ключ на токене.
type TokenAgentResponseV1HelloKeysElem struct {
	// Ключ.
	KeyRef string `json:"key_ref"`

	// Субъект.
	PersonID string `json:"person_id"`

	// Профиль.
	Profile TokenAgentResponseV1HelloKeysElemProfile `json:"profile"`
}

type TokenAgentResponseV1HelloKeysElemProfile string

const TokenAgentResponseV1HelloKeysElemProfileGost TokenAgentResponseV1HelloKeysElemProfile = "gost"
const TokenAgentResponseV1HelloKeysElemProfilePq TokenAgentResponseV1HelloKeysElemProfile = "pq"

// Запись локального журнала подписанного.
type TokenAgentResponseV1LocalJournalElem struct {
	// Отпечаток подписанного.
	Digest string `json:"digest"`

	// Тип.
	EventType *string `json:"event_type,omitempty,omitzero"`

	// Номер.
	Seq int `json:"seq"`

	// seq журнала сервера из квитанции приёма, если получена.
	ServerSeq *int `json:"server_seq,omitempty,omitzero"`

	// Когда.
	SignedAt string `json:"signed_at"`
}

// Результат подписи.
type TokenAgentResponseV1SignedElem struct {
	// Время подписи по часам клиента — справочно, в порядок не входит (AD-37).
	ClientSignedAt string `json:"client_signed_at"`

	// Отпечаток, посчитанный агентом.
	DocDigest *string `json:"doc_digest,omitempty,omitzero"`

	// Envelope corresponds to the JSON schema field "envelope".
	Envelope crypto.DsseEnvelope `json:"envelope"`

	// Номер в локальном журнале подписанного.
	LocalJournalSeq int `json:"local_journal_seq"`

	// Поля сводки уровня 2 (3–7), которые агент вычислил сам из содержимого.
	Summary []TokenAgentResponseV1SignedElemSummaryElem `json:"summary,omitempty,omitzero"`
}

// Поле сводки.
type TokenAgentResponseV1SignedElemSummaryElem struct {
	// Подпись поля.
	Label string `json:"label"`

	// Значение.
	Value string `json:"value"`
}

// Состояние токена.
type TokenAgentResponseV1Status struct {
	// Владелец.
	PersonID *string `json:"person_id,omitempty,omitzero"`

	// PIN введён в этой смене.
	PinUnlocked bool `json:"pin_unlocked"`

	// Токен вставлен.
	TokenPresent bool `json:"token_present"`

	// Рабочее место из конфигурации агента.
	WorkplaceID *string `json:"workplace_id,omitempty,omitzero"`
}

type TokenAgentResponseV1Type string

const TokenAgentResponseV1TypeError TokenAgentResponseV1Type = "error"
const TokenAgentResponseV1TypeHello TokenAgentResponseV1Type = "hello"
const TokenAgentResponseV1TypeLocalJournal TokenAgentResponseV1Type = "local_journal"
const TokenAgentResponseV1TypeShiftReport TokenAgentResponseV1Type = "shift_report"
const TokenAgentResponseV1TypeSigned TokenAgentResponseV1Type = "signed"
const TokenAgentResponseV1TypeStatus TokenAgentResponseV1Type = "status"

// Подписанный отчёт независимого верификатора (AD-9, AD-46): класс
// `verifier-report`, профиль hybrid, ключ из тома verifier. Сдаётся хранителю; ant
// журналирует только ссылку (`security.integrity.checked`). Закрытая схема.
type VerifierReportV1 struct {
	// Проверки.
	Checks []VerifierReportV1ChecksElem `json:"checks"`

	// Профиль.
	CryptoProfile VerifierReportV1CryptoProfile `json:"crypto_profile"`

	// Перечень допустимых сборок из нормативного слоя.
	DomainBuildsAllowed []string `json:"domain_builds_allowed,omitempty,omitzero"`

	// Версия формата.
	FormatVersion int `json:"format_version"`

	// Когда сформирован (часы верификатора).
	GeneratedAt string `json:"generated_at"`

	// Реестр бумажных решений.
	PaperRegister []VerifierReportV1PaperRegisterElem `json:"paper_register"`

	// Проверенный диапазон.
	Range VerifierReportV1Range `json:"range"`

	// Прогон сценария, если проверялся он.
	RunID *string `json:"run_id,omitempty,omitzero"`

	// Подписи по классам происхождения — различаются в отчёте (AD-9).
	SignatureClasses VerifierReportV1SignatureClasses `json:"signature_classes"`

	// Подписанты.
	Signers []string `json:"signers"`

	// Отпечаток файла trust-anchors.
	TrustAnchorsDigest string `json:"trust_anchors_digest"`

	// Общий вердикт: «цело» только при нуле «не проверяемо».
	Verdict VerifierReportV1Verdict `json:"verdict"`

	// Хеш бинарника верификатора.
	VerifierBuild string `json:"verifier_build"`

	// Временные проверки — по виртуальному времени сценария.
	VirtualTime bool `json:"virtual_time"`
}

// Итог одной проверки.
type VerifierReportV1ChecksElem struct {
	// Проверка.
	Check VerifierReportV1ChecksElemCheck `json:"check"`

	// Сколько объектов проверено.
	Checked int `json:"checked"`

	// Находки.
	Findings []VerifierReportV1ChecksElemFindingsElem `json:"findings"`

	// Статус.
	Status VerifierReportV1ChecksElemStatus `json:"status"`
}

type VerifierReportV1ChecksElemCheck string

const VerifierReportV1ChecksElemCheckAuthority VerifierReportV1ChecksElemCheck = "authority"
const VerifierReportV1ChecksElemCheckBpmnQuorum VerifierReportV1ChecksElemCheck = "bpmn_quorum"
const VerifierReportV1ChecksElemCheckBuild VerifierReportV1ChecksElemCheck = "build"
const VerifierReportV1ChecksElemCheckChains VerifierReportV1ChecksElemCheck = "chains"
const VerifierReportV1ChecksElemCheckCheckpoints VerifierReportV1ChecksElemCheck = "checkpoints"
const VerifierReportV1ChecksElemCheckCoverage VerifierReportV1ChecksElemCheck = "coverage"
const VerifierReportV1ChecksElemCheckGenesis VerifierReportV1ChecksElemCheck = "genesis"
const VerifierReportV1ChecksElemCheckLateWrite VerifierReportV1ChecksElemCheck = "late_write"
const VerifierReportV1ChecksElemCheckProjections VerifierReportV1ChecksElemCheck = "projections"
const VerifierReportV1ChecksElemCheckReactions VerifierReportV1ChecksElemCheck = "reactions"
const VerifierReportV1ChecksElemCheckRendering VerifierReportV1ChecksElemCheck = "rendering"
const VerifierReportV1ChecksElemCheckSignatures VerifierReportV1ChecksElemCheck = "signatures"
const VerifierReportV1ChecksElemCheckSigningMoment VerifierReportV1ChecksElemCheck = "signing_moment"
const VerifierReportV1ChecksElemCheckSourceSeq VerifierReportV1ChecksElemCheck = "source_seq"

// Нарушение или оговорка.
type VerifierReportV1ChecksElemFindingsElem struct {
	// Номер критического действия CA-‹n›.
	CaRef *string `json:"ca_ref,omitempty,omitzero"`

	// Цепочка.
	Chain *VerifierReportV1ChecksElemFindingsElemChain `json:"chain,omitempty,omitzero"`

	// Код.
	Code string `json:"code"`

	// Что и где — по-русски.
	Detail string `json:"detail"`

	// Запись.
	Seq *int `json:"seq,omitempty,omitzero"`
}

type VerifierReportV1ChecksElemFindingsElemChain string

const VerifierReportV1ChecksElemFindingsElemChainCa VerifierReportV1ChecksElemFindingsElemChain = "ca"
const VerifierReportV1ChecksElemFindingsElemChainMain VerifierReportV1ChecksElemFindingsElemChain = "main"

type VerifierReportV1ChecksElemStatus string

const VerifierReportV1ChecksElemStatusIntact VerifierReportV1ChecksElemStatus = "intact"
const VerifierReportV1ChecksElemStatusNotVerifiable VerifierReportV1ChecksElemStatus = "not_verifiable"
const VerifierReportV1ChecksElemStatusRejected VerifierReportV1ChecksElemStatus = "rejected"

type VerifierReportV1CryptoProfile string

const VerifierReportV1CryptoProfileHybrid VerifierReportV1CryptoProfile = "hybrid"

// Бумажное решение для сверки с оригиналом.
type VerifierReportV1PaperRegisterElem struct {
	// Заверитель.
	AttestedBy string `json:"attested_by"`

	// Отпечаток.
	DocDigest string `json:"doc_digest"`

	// Документ.
	DocumentID string `json:"document_id"`

	// Учётный номер оригинала.
	PaperOriginalNo *string `json:"paper_original_no,omitempty,omitzero"`

	// QR со скана перечитан и совпал.
	ScanQrOk bool `json:"scan_qr_ok"`

	// Подписант.
	SignerPersonID string `json:"signer_person_id"`
}

// Проверенный диапазон.
type VerifierReportV1Range struct {
	// Цепочка CA по.
	CaToSeq int `json:"ca_to_seq"`

	// Последняя контрольная точка.
	LastCheckpointNo int `json:"last_checkpoint_no"`

	// С.
	MainFromSeq int `json:"main_from_seq"`

	// По.
	MainToSeq int `json:"main_to_seq"`
}

// Подписи по классам происхождения — различаются в отчёте (AD-9).
type VerifierReportV1SignatureClasses struct {
	// Подписи устройств.
	Device int `json:"device"`

	// Подписи блока генезиса.
	Genesis int `json:"genesis"`

	// Бумажные подписи с заверением.
	Paper int `json:"paper"`

	// Подписи партнёра (федерация).
	Partner int `json:"partner"`

	// Личные подписи людей (агент токена).
	Personal int `json:"personal"`

	// Подписи демо-персон сценариев.
	Scenario int `json:"scenario"`

	// Подписи ключами сервера (движок, шлюзы).
	ServerAttested int `json:"server_attested"`
}

type VerifierReportV1Verdict string

const VerifierReportV1VerdictIntact VerifierReportV1Verdict = "intact"
const VerifierReportV1VerdictIntactWithReservations VerifierReportV1Verdict = "intact_with_reservations"
const VerifierReportV1VerdictViolated VerifierReportV1Verdict = "violated"
