// Code generated by backend/tools/contractgen; DO NOT EDIT.
// Источник: contracts/normative (make generate). Руками не править (AD-20).

// Пакет normative — Go-типы файлов затравки нормативного слоя (/normative): политика, классификатор, карта реакций, шаблоны документов, справочники (AD-17, AD-31).
//
// Слой: сгенерированные контракты — чистые данные; доступны домену (AD-1).
package normative
