// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.
// Источник: contracts/normative/*.schema.json (make generate). Руками не править (AD-20).

package normative

// Стартовые паспорта допуска анализаторов для демо
// (normative/vision/analyzer-passports.v*.yaml; эпик 33, AD-29, AD-33): записи
// analyzer.passport.admitted, которые роль migrate пишет генезисом в профилях demo
// и fixtures. Это не допуск по экзамену (полный маршрут — эпик 40): паспорт
// помечен происхождением genesis.
type AnalyzerPassportsSeed struct {
	// occurred_at записей допуска: раньше любого наблюдения демо.
	AdmittedAt string `json:"admitted_at"`

	// Пометка для людей: демо-затравка, не промышленная валидация.
	Note *string `json:"note,omitempty,omitzero"`

	// Паспорта допуска.
	Passports []AnalyzerPassportsSeedPassportsElem `json:"passports"`

	// Профили, в которых паспорта записываются; в prod затравка не пишется никогда.
	Profiles []AnalyzerPassportsSeedProfilesElem `json:"profiles"`

	// Версия затравки: входит в event_id записей (повтор той же версии — дубль, а не
	// вторая запись).
	Version int `json:"version"`
}

// Паспорт допуска карты контроля.
type AnalyzerPassportsSeedPassportsElem struct {
	// Анализатор.
	AnalyzerID string `json:"analyzer_id"`

	// Визуальный контроль или контроль действий оператора.
	AnalyzerKind AnalyzerPassportsSeedPassportsElemAnalyzerKind `json:"analyzer_kind"`

	// Протокол допуска (для затравки — условный номер демо).
	DocumentID string `json:"document_id"`

	// Паспорт.
	PassportID string `json:"passport_id"`

	// Карта контроля `‹id›@‹версия›` — как в ant:inspection/@recipeRef процесса.
	RecipeRef string `json:"recipe_ref"`

	// Стадия допуска.
	Stage AnalyzerPassportsSeedPassportsElemStage `json:"stage"`

	// Название анализатора.
	Title string `json:"title"`

	// Уровень доверия (contracts/analyzer-trust-levels.yaml).
	TrustLevel int `json:"trust_level"`

	// Допущенная конфигурация контура — все восемь составляющих вектора версий
	// (AD-29).
	Versions AnalyzerPassportsSeedPassportsElemVersions `json:"versions"`
}

type AnalyzerPassportsSeedPassportsElemAnalyzerKind string

const AnalyzerPassportsSeedPassportsElemAnalyzerKindOperatorvision AnalyzerPassportsSeedPassportsElemAnalyzerKind = "operatorvision"
const AnalyzerPassportsSeedPassportsElemAnalyzerKindVisionqc AnalyzerPassportsSeedPassportsElemAnalyzerKind = "visionqc"

type AnalyzerPassportsSeedPassportsElemStage string

const AnalyzerPassportsSeedPassportsElemStageActive AnalyzerPassportsSeedPassportsElemStage = "active"
const AnalyzerPassportsSeedPassportsElemStagePilot AnalyzerPassportsSeedPassportsElemStage = "pilot"
const AnalyzerPassportsSeedPassportsElemStageShadow AnalyzerPassportsSeedPassportsElemStage = "shadow"

// Допущенная конфигурация контура — все восемь составляющих вектора версий
// (AD-29).
type AnalyzerPassportsSeedPassportsElemVersions struct {
	// Версия анализатора.
	AnalyzerVersion string `json:"analyzer_version"`

	// Версия приложения источника.
	AppVersion string `json:"app_version"`

	// Калибровка.
	Calibration string `json:"calibration"`

	// Конфигурация камеры и света.
	CameraConfig string `json:"camera_config"`

	// Версия контракта данных источника.
	ContractVersion string `json:"contract_version"`

	// Ревизия изделия (КД).
	ItemRevision string `json:"item_revision"`

	// Карта контроля с версией.
	RecipeRef string `json:"recipe_ref"`

	// Профиль порогов.
	ThresholdProfile string `json:"threshold_profile"`
}

type AnalyzerPassportsSeedProfilesElem string

const AnalyzerPassportsSeedProfilesElemDemo AnalyzerPassportsSeedProfilesElem = "demo"
const AnalyzerPassportsSeedProfilesElemFixtures AnalyzerPassportsSeedProfilesElem = "fixtures"
const AnalyzerPassportsSeedProfilesElemLoad AnalyzerPassportsSeedProfilesElem = "load"

// Производственный календарь (FR-55): normative/reference/*/calendar.yaml.
type CalendarSeed struct {
	// Календарь.
	CalendarID string `json:"calendar_id"`

	// Часовой пояс IANA.
	TimeZone string `json:"time_zone"`

	// Версия.
	Version int `json:"version"`

	// Годы.
	Years []CalendarSeedYearsElem `json:"years"`
}

// Год.
type CalendarSeedYearsElem struct {
	// Нерабочие дни сверх еженедельных: праздники и перенесённые выходные.
	Holidays []string `json:"holidays"`

	// Сокращённые дни.
	ShortenedDays []string `json:"shortened_days"`

	// Еженедельные выходные.
	WeeklyDaysOff []CalendarSeedYearsElemWeeklyDaysOffElem `json:"weekly_days_off"`

	// Рабочие дни, выпадающие на еженедельные выходные (перенос выходного).
	WorkingDays []string `json:"working_days,omitempty,omitzero"`

	// Год.
	Year int `json:"year"`
}

type CalendarSeedYearsElemWeeklyDaysOffElem string

const CalendarSeedYearsElemWeeklyDaysOffElemFri CalendarSeedYearsElemWeeklyDaysOffElem = "fri"
const CalendarSeedYearsElemWeeklyDaysOffElemMon CalendarSeedYearsElemWeeklyDaysOffElem = "mon"
const CalendarSeedYearsElemWeeklyDaysOffElemSat CalendarSeedYearsElemWeeklyDaysOffElem = "sat"
const CalendarSeedYearsElemWeeklyDaysOffElemSun CalendarSeedYearsElemWeeklyDaysOffElem = "sun"
const CalendarSeedYearsElemWeeklyDaysOffElemThu CalendarSeedYearsElemWeeklyDaysOffElem = "thu"
const CalendarSeedYearsElemWeeklyDaysOffElemTue CalendarSeedYearsElemWeeklyDaysOffElem = "tue"
const CalendarSeedYearsElemWeeklyDaysOffElemWed CalendarSeedYearsElemWeeklyDaysOffElem = "wed"

// Классификатор видов дефектов нормативного слоя (FR-125):
// normative/defects/classifier.v*.yaml.
type DefectClassifier struct {
	// Виды дефектов.
	DefectTypes []DefectClassifierDefectTypesElem `json:"defect_types"`

	// Тип изделия.
	ItemTypeID string `json:"item_type_id"`

	// Версия классификатора.
	Version int `json:"version"`
}

// Вид дефекта.
type DefectClassifierDefectTypesElem struct {
	// Код вида.
	Code string `json:"code"`

	// Измеряемая характеристика: значение против допуска.
	Measurable bool `json:"measurable"`

	// Методы, способные выявить вид (FR-14).
	Methods []DefectClassifierDefectTypesElemMethodsElem `json:"methods"`

	// Наименование.
	Name string `json:"name"`

	// Класс тяжести по ГОСТ 15467.
	Severity DefectClassifierDefectTypesElemSeverity `json:"severity"`

	// Где встречается.
	ZoneKinds []DefectClassifierDefectTypesElemZoneKindsElem `json:"zone_kinds"`
}

type DefectClassifierDefectTypesElemMethodsElem string

const DefectClassifierDefectTypesElemMethodsElemCamera DefectClassifierDefectTypesElemMethodsElem = "camera"
const DefectClassifierDefectTypesElemMethodsElemCmm DefectClassifierDefectTypesElemMethodsElem = "cmm"
const DefectClassifierDefectTypesElemMethodsElemLaboratory DefectClassifierDefectTypesElemMethodsElem = "laboratory"
const DefectClassifierDefectTypesElemMethodsElemLeakTest DefectClassifierDefectTypesElemMethodsElem = "leak_test"
const DefectClassifierDefectTypesElemMethodsElemOther DefectClassifierDefectTypesElemMethodsElem = "other"
const DefectClassifierDefectTypesElemMethodsElemPenetrant DefectClassifierDefectTypesElemMethodsElem = "penetrant"
const DefectClassifierDefectTypesElemMethodsElemRadiography DefectClassifierDefectTypesElemMethodsElem = "radiography"
const DefectClassifierDefectTypesElemMethodsElemSupplierDocuments DefectClassifierDefectTypesElemMethodsElem = "supplier_documents"
const DefectClassifierDefectTypesElemMethodsElemTorque DefectClassifierDefectTypesElemMethodsElem = "torque"
const DefectClassifierDefectTypesElemMethodsElemUltrasonic DefectClassifierDefectTypesElemMethodsElem = "ultrasonic"
const DefectClassifierDefectTypesElemMethodsElemVisualHuman DefectClassifierDefectTypesElemMethodsElem = "visual_human"

type DefectClassifierDefectTypesElemSeverity string

const DefectClassifierDefectTypesElemSeverityCritical DefectClassifierDefectTypesElemSeverity = "critical"
const DefectClassifierDefectTypesElemSeverityMajor DefectClassifierDefectTypesElemSeverity = "major"
const DefectClassifierDefectTypesElemSeverityMinor DefectClassifierDefectTypesElemSeverity = "minor"

type DefectClassifierDefectTypesElemZoneKindsElem string

const DefectClassifierDefectTypesElemZoneKindsElemCavity DefectClassifierDefectTypesElemZoneKindsElem = "cavity"
const DefectClassifierDefectTypesElemZoneKindsElemGroove DefectClassifierDefectTypesElemZoneKindsElem = "groove"
const DefectClassifierDefectTypesElemZoneKindsElemHole DefectClassifierDefectTypesElemZoneKindsElem = "hole"
const DefectClassifierDefectTypesElemZoneKindsElemJoint DefectClassifierDefectTypesElemZoneKindsElem = "joint"
const DefectClassifierDefectTypesElemZoneKindsElemOther DefectClassifierDefectTypesElemZoneKindsElem = "other"
const DefectClassifierDefectTypesElemZoneKindsElemSurface DefectClassifierDefectTypesElemZoneKindsElem = "surface"
const DefectClassifierDefectTypesElemZoneKindsElemWeldSection DefectClassifierDefectTypesElemZoneKindsElem = "weld_section"

// Перечень шаблонов документов шагов процесса (AD-12):
// normative/documents/templates.v*.yaml.
type DocumentTemplatesSeed struct {
	// Шаблоны.
	Templates []DocumentTemplatesSeedTemplatesElem `json:"templates"`

	// Версия.
	Version int `json:"version"`
}

// Шаблон.
type DocumentTemplatesSeedTemplatesElem struct {
	// Класс: запись, решение, требование, вход.
	Class DocumentTemplatesSeedTemplatesElemClass `json:"class"`

	// Построитель содержимого в domain/documents: traveler, nc_statement,
	// nc_disposition, generic. Нет — шаблон только объявлен (эпик 44).
	DocType *string `json:"doc_type,omitempty,omitzero"`

	// Идентификатор шаблона.
	ID string `json:"id"`

	// Каноническая отрисовка HTML (AD-12): печатная рамка в неё не входит.
	Layout []DocumentTemplatesSeedTemplatesElemLayoutElem `json:"layout,omitempty,omitzero"`

	// Маршрут подписей (AD-13, AD-43).
	Route []DocumentTemplatesSeedTemplatesElemRouteElem `json:"route,omitempty,omitzero"`

	// Вид объекта документа.
	Subject *DocumentTemplatesSeedTemplatesElemSubject `json:"subject,omitempty,omitzero"`

	// Поля сводки уровня 2 (3–7), входят в отпечаток (AD-12, FR-66).
	Summary []DocumentTemplatesSeedTemplatesElemSummaryElem `json:"summary,omitempty,omitzero"`

	// Название документа.
	Title string `json:"title"`

	// Версия шаблона: template_ref = ‹id›@‹версия› (AD-12). Нет — 1.
	Version *int `json:"version,omitempty,omitzero"`
}

type DocumentTemplatesSeedTemplatesElemClass string

const DocumentTemplatesSeedTemplatesElemClassDecision DocumentTemplatesSeedTemplatesElemClass = "decision"
const DocumentTemplatesSeedTemplatesElemClassInput DocumentTemplatesSeedTemplatesElemClass = "input"
const DocumentTemplatesSeedTemplatesElemClassRecord DocumentTemplatesSeedTemplatesElemClass = "record"
const DocumentTemplatesSeedTemplatesElemClassRequirement DocumentTemplatesSeedTemplatesElemClass = "requirement"

// Раздел канонической HTML-отрисовки (AD-12).
type DocumentTemplatesSeedTemplatesElemLayoutElem struct {
	// Колонки раздела table: путь внутри строки и подпись.
	Columns []DocumentTemplatesSeedTemplatesElemLayoutElemColumnsElem `json:"columns,omitempty,omitzero"`

	// Поля раздела fields.
	Fields []DocumentTemplatesSeedTemplatesElemLayoutElemFieldsElem `json:"fields,omitempty,omitzero"`

	// Путь к полю раздела text.
	Key *string `json:"key,omitempty,omitzero"`

	// Вид раздела: поля, таблица по массиву, маршрут подписей, текст поля.
	Kind DocumentTemplatesSeedTemplatesElemLayoutElemKind `json:"kind"`

	// Путь к массиву строк раздела table.
	Rows *string `json:"rows,omitempty,omitzero"`

	// Заголовок раздела.
	Title *string `json:"title,omitempty,omitzero"`
}

// Поле: путь в content и подпись.
type DocumentTemplatesSeedTemplatesElemLayoutElemColumnsElem struct {
	// Путь к полю content через точку.
	Key string `json:"key"`

	// Подпись поля.
	Label string `json:"label"`
}

// Поле: путь в content и подпись.
type DocumentTemplatesSeedTemplatesElemLayoutElemFieldsElem struct {
	// Путь к полю content через точку.
	Key string `json:"key"`

	// Подпись поля.
	Label string `json:"label"`
}

type DocumentTemplatesSeedTemplatesElemLayoutElemKind string

const DocumentTemplatesSeedTemplatesElemLayoutElemKindFields DocumentTemplatesSeedTemplatesElemLayoutElemKind = "fields"
const DocumentTemplatesSeedTemplatesElemLayoutElemKindRoute DocumentTemplatesSeedTemplatesElemLayoutElemKind = "route"
const DocumentTemplatesSeedTemplatesElemLayoutElemKindTable DocumentTemplatesSeedTemplatesElemLayoutElemKind = "table"
const DocumentTemplatesSeedTemplatesElemLayoutElemKindText DocumentTemplatesSeedTemplatesElemLayoutElemKind = "text"

// Этап маршрута подписей (AD-13); обязательные подписи вычисляет
// access.RequiredApprovals (AD-43).
type DocumentTemplatesSeedTemplatesElemRouteElem struct {
	// Полномочие заверителя бумажной подписи; нет — бумага на этапе запрещена.
	AttesterAuthorityID *string `json:"attester_authority_id,omitempty,omitzero"`

	// Полномочие этапа (normative/policy) или роль, если отдельного полномочия нет.
	AuthorityID string `json:"authority_id"`

	// Этап закрывает само решение-источник документа.
	BySource *bool `json:"by_source,omitempty,omitzero"`

	// Внешняя сторона.
	ExternalParty *DocumentTemplatesSeedTemplatesElemRouteElemExternalParty `json:"external_party,omitempty,omitzero"`

	// k для k из n и число подписей для «все».
	K *int `json:"k,omitempty,omitzero"`

	// Бумага с заверением допустима (AD-43).
	PaperAllowed bool `json:"paper_allowed"`

	// Сколько подписей: 1 | все | k из n.
	Quorum DocumentTemplatesSeedTemplatesElemRouteElemQuorum `json:"quorum"`

	// Роль подписанта по политике (с наследованием).
	Role *string `json:"role,omitempty,omitzero"`

	// Разделение обязанностей (FR-56, AD-43).
	Separation []DocumentTemplatesSeedTemplatesElemRouteElemSeparationElem `json:"separation,omitempty,omitzero"`

	// Уровень подписи (AD-13).
	SignatureLevel int `json:"signature_level"`

	// Номер этапа по порядку.
	Stage int `json:"stage"`

	// Вид цифрового клейма для действий контроля (FR-145).
	StampKind *string `json:"stamp_kind,omitempty,omitzero"`

	// Кто подписывает — для людей.
	Title string `json:"title"`

	// Этап нужен только при условии (режим автоматизации, решение).
	When *DocumentTemplatesSeedTemplatesElemRouteElemWhen `json:"when,omitempty,omitzero"`
}

type DocumentTemplatesSeedTemplatesElemRouteElemExternalParty string

const DocumentTemplatesSeedTemplatesElemRouteElemExternalPartyCustomerRepresentative DocumentTemplatesSeedTemplatesElemRouteElemExternalParty = "customer_representative"
const DocumentTemplatesSeedTemplatesElemRouteElemExternalPartyNone DocumentTemplatesSeedTemplatesElemRouteElemExternalParty = "none"
const DocumentTemplatesSeedTemplatesElemRouteElemExternalPartyPartner DocumentTemplatesSeedTemplatesElemRouteElemExternalParty = "partner"

type DocumentTemplatesSeedTemplatesElemRouteElemQuorum string

const DocumentTemplatesSeedTemplatesElemRouteElemQuorumAll DocumentTemplatesSeedTemplatesElemRouteElemQuorum = "all"
const DocumentTemplatesSeedTemplatesElemRouteElemQuorumKOfN DocumentTemplatesSeedTemplatesElemRouteElemQuorum = "k_of_n"
const DocumentTemplatesSeedTemplatesElemRouteElemQuorumOne DocumentTemplatesSeedTemplatesElemRouteElemQuorum = "one"

type DocumentTemplatesSeedTemplatesElemRouteElemSeparationElem string

const DocumentTemplatesSeedTemplatesElemRouteElemSeparationElemDistinctSigners DocumentTemplatesSeedTemplatesElemRouteElemSeparationElem = "distinct_signers"
const DocumentTemplatesSeedTemplatesElemRouteElemSeparationElemNotItemParticipant DocumentTemplatesSeedTemplatesElemRouteElemSeparationElem = "not_item_participant"

// Этап нужен только при условии (режим автоматизации, решение).
type DocumentTemplatesSeedTemplatesElemRouteElemWhen struct {
	// Этап нужен для продукции с приёмкой представителя заказчика (режим 5).
	CustomerAcceptance *bool `json:"customer_acceptance,omitempty,omitzero"`

	// Решения, при которых этап нужен (например, repair, use_as_is — режим 4).
	Decisions []string `json:"decisions,omitempty,omitzero"`

	// Сфера выдачи прав (документ «Выдача ролей, полномочий, клейм», AD-11): этап
	// второй подписи нужен, если сфера выдачи — одна из этих; её вычисляет
	// access.Assess по эффективным правам.
	GrantDomains []DocumentTemplatesSeedTemplatesElemRouteElemWhenGrantDomainsElem `json:"grant_domains,omitempty,omitzero"`
}

type DocumentTemplatesSeedTemplatesElemRouteElemWhenGrantDomainsElem string

const DocumentTemplatesSeedTemplatesElemRouteElemWhenGrantDomainsElemAdmin DocumentTemplatesSeedTemplatesElemRouteElemWhenGrantDomainsElem = "admin"
const DocumentTemplatesSeedTemplatesElemRouteElemWhenGrantDomainsElemProduction DocumentTemplatesSeedTemplatesElemRouteElemWhenGrantDomainsElem = "production"
const DocumentTemplatesSeedTemplatesElemRouteElemWhenGrantDomainsElemQc DocumentTemplatesSeedTemplatesElemRouteElemWhenGrantDomainsElem = "qc"

type DocumentTemplatesSeedTemplatesElemSubject string

const DocumentTemplatesSeedTemplatesElemSubjectItem DocumentTemplatesSeedTemplatesElemSubject = "item"
const DocumentTemplatesSeedTemplatesElemSubjectLot DocumentTemplatesSeedTemplatesElemSubject = "lot"
const DocumentTemplatesSeedTemplatesElemSubjectNonconformity DocumentTemplatesSeedTemplatesElemSubject = "nonconformity"
const DocumentTemplatesSeedTemplatesElemSubjectOther DocumentTemplatesSeedTemplatesElemSubject = "other"
const DocumentTemplatesSeedTemplatesElemSubjectPolicy DocumentTemplatesSeedTemplatesElemSubject = "policy"
const DocumentTemplatesSeedTemplatesElemSubjectProcessVersion DocumentTemplatesSeedTemplatesElemSubject = "process_version"

// Поле: путь в content и подпись.
type DocumentTemplatesSeedTemplatesElemSummaryElem struct {
	// Путь к полю content через точку.
	Key string `json:"key"`

	// Подпись поля.
	Label string `json:"label"`
}

// Оборудование и поверка (AD-31, FR-17): normative/reference/*/equipment.yaml.
type EquipmentSeed struct {
	// Оборудование.
	Equipment []EquipmentSeedEquipmentElem `json:"equipment"`

	// Поверки.
	Verifications []EquipmentSeedVerificationsElem `json:"verifications"`

	// Версия.
	Version int `json:"version"`
}

// Оборудование.
type EquipmentSeedEquipmentElem struct {
	// Идентификатор.
	ID string `json:"id"`

	// Вид.
	Kind EquipmentSeedEquipmentElemKind `json:"kind"`

	// Место.
	LocationID string `json:"location_id"`

	// Средство измерений.
	Measuring bool `json:"measuring"`

	// Название.
	Name string `json:"name"`

	// Уставки параметров (целые в базовой единице параметра).
	Setpoints EquipmentSeedEquipmentElemSetpoints `json:"setpoints,omitempty,omitzero"`

	// Источник событий.
	SourceID *string `json:"source_id,omitempty,omitzero"`
}

type EquipmentSeedEquipmentElemKind string

const EquipmentSeedEquipmentElemKindCamera EquipmentSeedEquipmentElemKind = "camera"
const EquipmentSeedEquipmentElemKindCmm EquipmentSeedEquipmentElemKind = "cmm"
const EquipmentSeedEquipmentElemKindCncMachine EquipmentSeedEquipmentElemKind = "cnc_machine"
const EquipmentSeedEquipmentElemKindLeakTester EquipmentSeedEquipmentElemKind = "leak_tester"
const EquipmentSeedEquipmentElemKindOther EquipmentSeedEquipmentElemKind = "other"
const EquipmentSeedEquipmentElemKindTestBench EquipmentSeedEquipmentElemKind = "test_bench"
const EquipmentSeedEquipmentElemKindTorqueWrench EquipmentSeedEquipmentElemKind = "torque_wrench"
const EquipmentSeedEquipmentElemKindWeldingSource EquipmentSeedEquipmentElemKind = "welding_source"
const EquipmentSeedEquipmentElemKindXray EquipmentSeedEquipmentElemKind = "xray"

// Уставки параметров (целые в базовой единице параметра).
type EquipmentSeedEquipmentElemSetpoints map[string]struct {
	// Нижняя граница.
	Lower int `json:"lower"`

	// Номинал.
	Nominal int `json:"nominal"`

	// Верхняя граница.
	Upper int `json:"upper"`
}

// Поверка или калибровка.
type EquipmentSeedVerificationsElem struct {
	// Свидетельство.
	CertificateRef *string `json:"certificate_ref,omitempty,omitzero"`

	// Оборудование.
	EquipmentID string `json:"equipment_id"`

	// Вид.
	Kind EquipmentSeedVerificationsElemKind `json:"kind"`

	// Итог.
	Result EquipmentSeedVerificationsElemResult `json:"result"`

	// До.
	ValidUntil string `json:"valid_until"`
}

type EquipmentSeedVerificationsElemKind string

const EquipmentSeedVerificationsElemKindCalibration EquipmentSeedVerificationsElemKind = "calibration"
const EquipmentSeedVerificationsElemKindVerification EquipmentSeedVerificationsElemKind = "verification"

type EquipmentSeedVerificationsElemResult string

const EquipmentSeedVerificationsElemResultInvalid EquipmentSeedVerificationsElemResult = "invalid"
const EquipmentSeedVerificationsElemResultValid EquipmentSeedVerificationsElemResult = "valid"

// Иллюстрации к сигналам VisionQC из открытых наборов
// (normative/vision/illustrations.v*.yaml; FR-102, PRD §11.12): набор, ссылка,
// лицензия, автор и соответствие классов набора видам дефектов классификатора.
// Файлы в репозиторий не кладутся; приложить иллюстрацию можно, только если файл
// есть офлайн на краю, иначе — только ссылка и метаданные.
type IllustrationsCatalog struct {
	// Открытые наборы.
	Datasets []IllustrationsCatalogDatasetsElem `json:"datasets"`

	// Версия каталога.
	Version int `json:"version"`
}

// Открытый набор изображений.
type IllustrationsCatalogDatasetsElem struct {
	// Автор набора.
	Author string `json:"author"`

	// Публикация, которую просит цитировать автор.
	Citation *string `json:"citation,omitempty,omitzero"`

	// Классы набора и виды дефектов классификатора.
	Classes []IllustrationsCatalogDatasetsElemClassesElem `json:"classes"`

	// Идентификатор набора.
	ID string `json:"id"`

	// Лицензия.
	License string `json:"license"`

	// Текст лицензии.
	LicenseURL *string `json:"license_url,omitempty,omitzero"`

	// Пометка на экране (например, «ИЛЛЮСТРАЦИЯ»).
	Mark string `json:"mark"`

	// Оговорка: не относится к изделию, не промышленная валидация.
	Note string `json:"note"`

	// Название набора.
	Title string `json:"title"`

	// Ссылка на набор.
	URL string `json:"url"`
}

// Класс набора.
type IllustrationsCatalogDatasetsElemClassesElem struct {
	// Класс (каталог) в наборе.
	DatasetClass string `json:"dataset_class"`

	// Виды дефектов классификатора, которые иллюстрирует класс; пусто — «признаков
	// нет».
	DefectCodes []string `json:"defect_codes"`

	// MIME-тип образца.
	MediaType string `json:"media_type"`

	// Относительный путь файла-образца внутри распакованного набора.
	Sample string `json:"sample"`
}

// Номенклатура, состав, зоны и связи изделия (FR-45, FR-46, PRD §11.15):
// normative/reference/*/item-types.yaml.
type ItemTypesSeed struct {
	// Типы.
	ItemTypes []ItemTypesSeedItemTypesElem `json:"item_types"`

	// Версия.
	Version int `json:"version"`
}

// Тип изделия.
type ItemTypesSeedItemTypesElem struct {
	// Состав.
	Components []ItemTypesSeedItemTypesElemComponentsElem `json:"components,omitempty,omitzero"`

	// Обозначение.
	Designation string `json:"designation"`

	// Идентификатор.
	ID string `json:"id"`

	// Связи.
	Links []ItemTypesSeedItemTypesElemLinksElem `json:"links,omitempty,omitzero"`

	// Постоянный носитель.
	Marking ItemTypesSeedItemTypesElemMarking `json:"marking"`

	// Наименование.
	Name string `json:"name"`

	// Ревизия.
	Revision string `json:"revision"`

	// Зоны.
	Zones []ItemTypesSeedItemTypesElemZonesElem `json:"zones,omitempty,omitzero"`
}

// Позиция состава.
type ItemTypesSeedItemTypesElemComponentsElem struct {
	// Тип.
	ItemTypeID string `json:"item_type_id"`

	// Учитывается партией.
	LotTracked bool `json:"lot_tracked"`

	// Количество.
	Quantity int `json:"quantity"`
}

// Связь сборки.
type ItemTypesSeedItemTypesElemLinksElem struct {
	// Закрывает доступ к зонам (FR-20).
	ClosesAccessTo []string `json:"closes_access_to,omitempty,omitzero"`

	// Ставится до связи.
	InstallBefore *string `json:"install_before,omitempty,omitzero"`

	// Вид.
	Kind ItemTypesSeedItemTypesElemLinksElemKind `json:"kind"`

	// Связь.
	LinkID string `json:"link_id"`

	// Лимит ремонтов на зону (FR-18).
	ReworkLimitPerZone *int `json:"rework_limit_per_zone,omitempty,omitzero"`

	// Зоны.
	Zones []string `json:"zones"`
}

type ItemTypesSeedItemTypesElemLinksElemKind string

const ItemTypesSeedItemTypesElemLinksElemKindBoltedJoint ItemTypesSeedItemTypesElemLinksElemKind = "bolted_joint"
const ItemTypesSeedItemTypesElemLinksElemKindOther ItemTypesSeedItemTypesElemLinksElemKind = "other"
const ItemTypesSeedItemTypesElemLinksElemKindSeal ItemTypesSeedItemTypesElemLinksElemKind = "seal"
const ItemTypesSeedItemTypesElemLinksElemKindWeld ItemTypesSeedItemTypesElemLinksElemKind = "weld"

type ItemTypesSeedItemTypesElemMarking string

const ItemTypesSeedItemTypesElemMarkingContainerCell ItemTypesSeedItemTypesElemMarking = "container_cell"
const ItemTypesSeedItemTypesElemMarkingDpmDatamatrix ItemTypesSeedItemTypesElemMarking = "dpm_datamatrix"
const ItemTypesSeedItemTypesElemMarkingInternalID ItemTypesSeedItemTypesElemMarking = "internal_id"
const ItemTypesSeedItemTypesElemMarkingManualEntry ItemTypesSeedItemTypesElemMarking = "manual_entry"
const ItemTypesSeedItemTypesElemMarkingPostContext ItemTypesSeedItemTypesElemMarking = "post_context"
const ItemTypesSeedItemTypesElemMarkingRouteCard ItemTypesSeedItemTypesElemMarking = "route_card"
const ItemTypesSeedItemTypesElemMarkingTagQr ItemTypesSeedItemTypesElemMarking = "tag_qr"

// Зона.
type ItemTypesSeedItemTypesElemZonesElem struct {
	// Вид.
	Kind ItemTypesSeedItemTypesElemZonesElemKind `json:"kind"`

	// Название.
	Name string `json:"name"`

	// Зона.
	ZoneID string `json:"zone_id"`
}

type ItemTypesSeedItemTypesElemZonesElemKind string

const ItemTypesSeedItemTypesElemZonesElemKindCavity ItemTypesSeedItemTypesElemZonesElemKind = "cavity"
const ItemTypesSeedItemTypesElemZonesElemKindGroove ItemTypesSeedItemTypesElemZonesElemKind = "groove"
const ItemTypesSeedItemTypesElemZonesElemKindHole ItemTypesSeedItemTypesElemZonesElemKind = "hole"
const ItemTypesSeedItemTypesElemZonesElemKindJoint ItemTypesSeedItemTypesElemZonesElemKind = "joint"
const ItemTypesSeedItemTypesElemZonesElemKindOther ItemTypesSeedItemTypesElemZonesElemKind = "other"
const ItemTypesSeedItemTypesElemZonesElemKindSurface ItemTypesSeedItemTypesElemZonesElemKind = "surface"
const ItemTypesSeedItemTypesElemZonesElemKindWeldSection ItemTypesSeedItemTypesElemZonesElemKind = "weld_section"

// Справочник мест (AD-31): normative/reference/*/locations.yaml.
type LocationsSeed struct {
	// Предприятие.
	Enterprise LocationsSeedEnterprise `json:"enterprise"`

	// Места.
	Locations []LocationsSeedLocationsElem `json:"locations"`

	// Версия.
	Version int `json:"version"`
}

// Предприятие.
type LocationsSeedEnterprise struct {
	// Код.
	Code string `json:"code"`

	// Название.
	Name string `json:"name"`
}

// Место.
type LocationsSeedLocationsElem struct {
	// Зона СКУД.
	AccessZoneID *string `json:"access_zone_id,omitempty,omitzero"`

	// Идентификатор.
	ID string `json:"id"`

	// Вид.
	Kind LocationsSeedLocationsElemKind `json:"kind"`

	// Дорожка BPMN (для цеха).
	LaneID *string `json:"lane_id,omitempty,omitzero"`

	// Название.
	Name string `json:"name"`

	// Родитель.
	Parent *string `json:"parent,omitempty,omitzero"`

	// Область политики.
	Scope string `json:"scope"`

	// Склад цеха.
	WarehouseID *string `json:"warehouse_id,omitempty,omitzero"`
}

type LocationsSeedLocationsElemKind string

const LocationsSeedLocationsElemKindBuilding LocationsSeedLocationsElemKind = "building"
const LocationsSeedLocationsElemKindIsolator LocationsSeedLocationsElemKind = "isolator"
const LocationsSeedLocationsElemKindLine LocationsSeedLocationsElemKind = "line"
const LocationsSeedLocationsElemKindStation LocationsSeedLocationsElemKind = "station"
const LocationsSeedLocationsElemKindStorage LocationsSeedLocationsElemKind = "storage"
const LocationsSeedLocationsElemKindWarehouse LocationsSeedLocationsElemKind = "warehouse"
const LocationsSeedLocationsElemKindWorkplace LocationsSeedLocationsElemKind = "workplace"
const LocationsSeedLocationsElemKindWorkshop LocationsSeedLocationsElemKind = "workshop"

// Шаблоны партий фикстур генезиса (AD-38):
// normative/reference/*/lot-templates.yaml.
type LotTemplatesSeed struct {
	// Партии.
	Lots []LotTemplatesSeedLotsElem `json:"lots"`

	// Поставщики.
	Suppliers []LotTemplatesSeedSuppliersElem `json:"suppliers"`

	// Версия.
	Version int `json:"version"`
}

// Партия.
type LotTemplatesSeedLotsElem struct {
	// Сертификат.
	CertificateNo *string `json:"certificate_no,omitempty,omitzero"`

	// Срок годности.
	ExpiryDate *string `json:"expiry_date,omitempty,omitzero"`

	// Плавка.
	HeatNo *string `json:"heat_no,omitempty,omitzero"`

	// Идентификатор.
	ID string `json:"id"`

	// Тип.
	ItemTypeID string `json:"item_type_id"`

	// Количество.
	Quantity int `json:"quantity"`

	// Поставщик.
	SupplierID string `json:"supplier_id"`
}

// Поставщик.
type LotTemplatesSeedSuppliersElem struct {
	// Идентификатор.
	ID string `json:"id"`

	// Название.
	Name string `json:"name"`

	// Код партнёра федерации.
	PartnerCode *string `json:"partner_code,omitempty,omitzero"`
}

// Стартовая политика доступа (AD-15, AD-33): normative/policy/policy.v*.yaml;
// генезис превращает её в записи policy.* и access.*.
type PolicySeed struct {
	// Параметры аудита (AD-8).
	Audit PolicySeedAudit `json:"audit"`

	// Полномочия.
	Authorities []PolicySeedAuthoritiesElem `json:"authorities"`

	// Код предприятия.
	EnterpriseCode string `json:"enterprise_code"`

	// Маршрут подписей документа «Выдача ролей, полномочий, клейм» (каталог
	// документов спайна, AD-13, AD-43); тот же маршрут — у шаблона в
	// normative/documents (проверяет тест).
	GrantRoute *PolicySeedGrantRoute `json:"grant_route,omitempty,omitzero"`

	// Выдачи.
	Grants PolicySeedGrants `json:"grants"`

	// Сотрудники.
	Persons []PolicySeedPersonsElem `json:"persons"`

	// Роли.
	Roles []PolicySeedRolesElem `json:"roles"`

	// Области.
	Scopes PolicySeedScopes `json:"scopes"`

	// Вторая подпись независимой стороны (AD-11).
	SecondSignature PolicySeedSecondSignature `json:"second_signature"`

	// Разделение обязанностей.
	SeparationOfDuties []PolicySeedSeparationOfDutiesElem `json:"separation_of_duties"`

	// Виды контроля для клейм.
	StampKinds []string `json:"stamp_kinds"`

	// Роль субъекта без сеанса (edge-агент, станок, stand, анализатор): подлинность
	// его сообщений — подпись пакета (AD-10), а не сеанс; обычно только приём фактов
	// (эпик 08).
	UnauthenticatedRole *string `json:"unauthenticated_role,omitempty,omitzero"`

	// Версия.
	Version int `json:"version"`
}

// Параметры аудита (AD-8).
type PolicySeedAudit struct {
	// Интервал, с.
	CheckpointIntervalS int `json:"checkpoint_interval_s"`

	// Предельный разрыв, с.
	CheckpointMaxGapS int `json:"checkpoint_max_gap_s"`

	// Дополнительно критические типы.
	CriticalTypes []string `json:"critical_types,omitempty,omitzero"`

	// Отпечаток ключа хранителя.
	KeeperKeyFingerprint *string `json:"keeper_key_fingerprint,omitempty,omitzero"`

	// Подписчики.
	SecurityBusSubscribers []string `json:"security_bus_subscribers,omitempty,omitzero"`
}

// Полномочие.
type PolicySeedAuthoritiesElem struct {
	// Сфера полномочия (AD-11): чья вторая подпись нужна при выдаче.
	Domain *PolicySeedAuthoritiesElemDomain `json:"domain,omitempty,omitzero"`

	// Идентификатор.
	ID string `json:"id"`

	// Название.
	Title string `json:"title"`
}

type PolicySeedAuthoritiesElemDomain string

const PolicySeedAuthoritiesElemDomainAdmin PolicySeedAuthoritiesElemDomain = "admin"
const PolicySeedAuthoritiesElemDomainProduction PolicySeedAuthoritiesElemDomain = "production"
const PolicySeedAuthoritiesElemDomainQc PolicySeedAuthoritiesElemDomain = "qc"

// Маршрут подписей документа «Выдача ролей, полномочий, клейм» (каталог документов
// спайна, AD-13, AD-43); тот же маршрут — у шаблона в normative/documents
// (проверяет тест).
type PolicySeedGrantRoute struct {
	// Маршрут подписей (AD-13, AD-43).
	Route []PolicySeedGrantRouteRouteElem `json:"route"`

	// Шаблон документа выдачи: ‹id›@‹версия›.
	Template string `json:"template"`

	// Название документа.
	Title *string `json:"title,omitempty,omitzero"`
}

// Этап маршрута подписей (AD-13); обязательные подписи вычисляет
// access.RequiredApprovals (AD-43).
type PolicySeedGrantRouteRouteElem struct {
	// Полномочие заверителя бумажной подписи; нет — бумага на этапе запрещена.
	AttesterAuthorityID *string `json:"attester_authority_id,omitempty,omitzero"`

	// Полномочие этапа (normative/policy) или роль, если отдельного полномочия нет.
	AuthorityID string `json:"authority_id"`

	// Этап закрывает само решение-источник документа.
	BySource *bool `json:"by_source,omitempty,omitzero"`

	// Внешняя сторона.
	ExternalParty *PolicySeedGrantRouteRouteElemExternalParty `json:"external_party,omitempty,omitzero"`

	// k для k из n и число подписей для «все».
	K *int `json:"k,omitempty,omitzero"`

	// Бумага с заверением допустима (AD-43).
	PaperAllowed bool `json:"paper_allowed"`

	// Сколько подписей: 1 | все | k из n.
	Quorum PolicySeedGrantRouteRouteElemQuorum `json:"quorum"`

	// Роль подписанта по политике (с наследованием).
	Role *string `json:"role,omitempty,omitzero"`

	// Разделение обязанностей (FR-56, AD-43).
	Separation []PolicySeedGrantRouteRouteElemSeparationElem `json:"separation,omitempty,omitzero"`

	// Уровень подписи (AD-13).
	SignatureLevel int `json:"signature_level"`

	// Номер этапа по порядку.
	Stage int `json:"stage"`

	// Вид цифрового клейма для действий контроля (FR-145).
	StampKind *string `json:"stamp_kind,omitempty,omitzero"`

	// Кто подписывает — для людей.
	Title string `json:"title"`

	// Этап нужен только при условии (режим автоматизации, решение).
	When *PolicySeedGrantRouteRouteElemWhen `json:"when,omitempty,omitzero"`
}

type PolicySeedGrantRouteRouteElemExternalParty string

const PolicySeedGrantRouteRouteElemExternalPartyCustomerRepresentative PolicySeedGrantRouteRouteElemExternalParty = "customer_representative"
const PolicySeedGrantRouteRouteElemExternalPartyNone PolicySeedGrantRouteRouteElemExternalParty = "none"
const PolicySeedGrantRouteRouteElemExternalPartyPartner PolicySeedGrantRouteRouteElemExternalParty = "partner"

type PolicySeedGrantRouteRouteElemQuorum string

const PolicySeedGrantRouteRouteElemQuorumAll PolicySeedGrantRouteRouteElemQuorum = "all"
const PolicySeedGrantRouteRouteElemQuorumKOfN PolicySeedGrantRouteRouteElemQuorum = "k_of_n"
const PolicySeedGrantRouteRouteElemQuorumOne PolicySeedGrantRouteRouteElemQuorum = "one"

type PolicySeedGrantRouteRouteElemSeparationElem string

const PolicySeedGrantRouteRouteElemSeparationElemDistinctSigners PolicySeedGrantRouteRouteElemSeparationElem = "distinct_signers"
const PolicySeedGrantRouteRouteElemSeparationElemNotItemParticipant PolicySeedGrantRouteRouteElemSeparationElem = "not_item_participant"

// Этап нужен только при условии (режим автоматизации, решение).
type PolicySeedGrantRouteRouteElemWhen struct {
	// Этап нужен для продукции с приёмкой представителя заказчика (режим 5).
	CustomerAcceptance *bool `json:"customer_acceptance,omitempty,omitzero"`

	// Решения, при которых этап нужен (например, repair, use_as_is — режим 4).
	Decisions []string `json:"decisions,omitempty,omitzero"`

	// Сфера выдачи прав (документ «Выдача ролей, полномочий, клейм», AD-11): этап
	// второй подписи нужен, если сфера выдачи — одна из этих; её вычисляет
	// access.Assess по эффективным правам.
	GrantDomains []PolicySeedGrantRouteRouteElemWhenGrantDomainsElem `json:"grant_domains,omitempty,omitzero"`
}

type PolicySeedGrantRouteRouteElemWhenGrantDomainsElem string

const PolicySeedGrantRouteRouteElemWhenGrantDomainsElemAdmin PolicySeedGrantRouteRouteElemWhenGrantDomainsElem = "admin"
const PolicySeedGrantRouteRouteElemWhenGrantDomainsElemProduction PolicySeedGrantRouteRouteElemWhenGrantDomainsElem = "production"
const PolicySeedGrantRouteRouteElemWhenGrantDomainsElemQc PolicySeedGrantRouteRouteElemWhenGrantDomainsElem = "qc"

// Выдачи.
type PolicySeedGrants struct {
	// Полномочия.
	Authorities []PolicySeedGrantsAuthoritiesElem `json:"authorities"`

	// Квалификации.
	Qualifications []PolicySeedGrantsQualificationsElem `json:"qualifications"`

	// Клейма.
	Stamps []PolicySeedGrantsStampsElem `json:"stamps"`
}

// Полномочие сотрудника.
type PolicySeedGrantsAuthoritiesElem struct {
	// Полномочие.
	Authority string `json:"authority"`

	// Рамки.
	Limits *PolicySeedGrantsAuthoritiesElemLimits `json:"limits,omitempty,omitzero"`

	// Кто.
	Person string `json:"person"`

	// Область.
	Scope string `json:"scope"`
}

// Рамки.
type PolicySeedGrantsAuthoritiesElemLimits struct {
	// Типы.
	ItemTypeIds []string `json:"item_type_ids,omitempty,omitzero"`

	// Наибольшая тяжесть.
	MaxSeverity *PolicySeedGrantsAuthoritiesElemLimitsMaxSeverity `json:"max_severity,omitempty,omitzero"`
}

type PolicySeedGrantsAuthoritiesElemLimitsMaxSeverity string

const PolicySeedGrantsAuthoritiesElemLimitsMaxSeverityCritical PolicySeedGrantsAuthoritiesElemLimitsMaxSeverity = "critical"
const PolicySeedGrantsAuthoritiesElemLimitsMaxSeverityMajor PolicySeedGrantsAuthoritiesElemLimitsMaxSeverity = "major"
const PolicySeedGrantsAuthoritiesElemLimitsMaxSeverityMinor PolicySeedGrantsAuthoritiesElemLimitsMaxSeverity = "minor"

// Квалификация.
type PolicySeedGrantsQualificationsElem struct {
	// Удостоверение.
	CertificateRef *string `json:"certificate_ref,omitempty,omitzero"`

	// Кто.
	Person string `json:"person"`

	// Вид.
	Qualification string `json:"qualification"`

	// Область.
	Scope string `json:"scope"`

	// До.
	ValidUntil string `json:"valid_until"`
}

// Цифровое клеймо.
type PolicySeedGrantsStampsElem struct {
	// Вид контроля.
	Kind string `json:"kind"`

	// Приказ.
	OrderRef string `json:"order_ref"`

	// Кто.
	Person string `json:"person"`

	// Область.
	Scope string `json:"scope"`

	// Номер клейма.
	StampID string `json:"stamp_id"`
}

// Сотрудник.
type PolicySeedPersonsElem struct {
	// Псевдоним.
	ID string `json:"id"`

	// Условное имя.
	Name string `json:"name"`

	// Роли.
	Roles []PolicySeedPersonsElemRolesElem `json:"roles"`
}

// Роль в области.
type PolicySeedPersonsElemRolesElem struct {
	// Роль.
	Role string `json:"role"`

	// Область.
	Scope string `json:"scope"`
}

// Роль.
type PolicySeedRolesElem struct {
	// Действия.
	Actions []string `json:"actions"`

	// Редкий подписант (FR-136): только адресованные ему карточки решения и их
	// предметы.
	CardOnly *bool `json:"card_only,omitempty,omitzero"`

	// Одна из пяти ролей кейса.
	CaseRole *bool `json:"case_role,omitempty,omitzero"`

	// Сфера роли для второй подписи (AD-11): admin — привилегии администраторов и
	// аудита, qc — ОТК; наследники берут сферу базовой роли.
	Domain *PolicySeedRolesElemDomain `json:"domain,omitempty,omitzero"`

	// Идентификатор роли.
	ID string `json:"id"`

	// Наследуемые роли.
	Inherits []string `json:"inherits,omitempty,omitzero"`

	// Название.
	Title string `json:"title"`
}

type PolicySeedRolesElemDomain string

const PolicySeedRolesElemDomainAdmin PolicySeedRolesElemDomain = "admin"
const PolicySeedRolesElemDomainProduction PolicySeedRolesElemDomain = "production"
const PolicySeedRolesElemDomainQc PolicySeedRolesElemDomain = "qc"

// Области.
type PolicySeedScopes struct {
	// Области.
	Paths []string `json:"paths"`

	// Корень.
	Root string `json:"root"`
}

// Вторая подпись независимой стороны (AD-11).
type PolicySeedSecondSignature struct {
	// Полномочие.
	AdminAndAuditPrivileges string `json:"admin_and_audit_privileges"`

	// Полномочие.
	ProductionAuthoritiesKeys string `json:"production_authorities_keys"`

	// Полномочие.
	QcAuthoritiesStampsKeys string `json:"qc_authorities_stamps_keys"`
}

// Правило разделения обязанностей.
type PolicySeedSeparationOfDutiesElem struct {
	// Несовместимые действия.
	ConflictingActions []string `json:"conflicting_actions"`

	// Идентификатор.
	ID string `json:"id"`

	// Формулировка.
	Statement string `json:"statement"`
}

// Карта реакций нормативного слоя (FR-48, FR-50, AD-3):
// normative/reactions/reaction-map.v*.yaml.
type ReactionMap struct {
	// Кто утвердил.
	ApprovedBy string `json:"approved_by"`

	// Сроки (FR-55).
	Deadlines ReactionMapDeadlines `json:"deadlines"`

	// Идентификатор карты.
	ID string `json:"id"`

	// Роль-владелец.
	OwnerRole string `json:"owner_role"`

	// Правила.
	Rules []ReactionMapRulesElem `json:"rules"`

	// Рамки применения.
	Scope ReactionMapScope `json:"scope"`

	// Действует с.
	ValidFrom string `json:"valid_from"`

	// Действует до.
	ValidUntil *string `json:"valid_until,omitempty,omitzero"`

	// Версия карты.
	Version int `json:"version"`
}

// Сроки (FR-55).
type ReactionMapDeadlines struct {
	// Срок быстрого сдерживания по классу риска, минут.
	ContainmentReviewMinutes ReactionMapDeadlinesContainmentReviewMinutes `json:"containment_review_minutes"`

	// Срок физического перемещения в изолятор, минут.
	IsolationMoveMinutes int `json:"isolation_move_minutes"`

	// Срок решения по изолированному изделию, рабочих дней.
	NcDispositionWorkDays int `json:"nc_disposition_work_days"`
}

// Срок быстрого сдерживания по классу риска, минут.
type ReactionMapDeadlinesContainmentReviewMinutes struct {
	// Тяжесть critical.
	Critical int `json:"critical"`

	// Тяжесть major.
	Major int `json:"major"`

	// Тяжесть minor.
	Minor int `json:"minor"`
}

// Правило реакции.
type ReactionMapRulesElem struct {
	// Режим автоматизации 1–5 (FR-50).
	AutomationMode int `json:"automation_mode"`

	// Идентификатор правила.
	ID string `json:"id"`

	// Условие.
	Match ReactionMapRulesElemMatch `json:"match"`

	// Порядок применения: меньше — раньше.
	Priority int `json:"priority"`

	// Реакция.
	Reaction ReactionMapRulesElemReaction `json:"reaction"`

	// Опоры.
	Refs []string `json:"refs,omitempty,omitzero"`

	// Смысл.
	Title string `json:"title"`
}

// Условие.
type ReactionMapRulesElemMatch struct {
	// Основания.
	BasisKind []ReactionMapRulesElemMatchBasisKindElem `json:"basis_kind,omitempty,omitzero"`

	// Уверенность не ниже, б. п.
	ConfidenceMinBp *int `json:"confidence_min_bp,omitempty,omitzero"`

	// Виды дефектов.
	DefectTypes []string `json:"defect_types,omitempty,omitzero"`

	// Отклонения.
	DeviationKinds []ReactionMapRulesElemMatchDeviationKindsElem `json:"deviation_kinds,omitempty,omitzero"`

	// Нет требования КД для вида.
	NoRequirement *bool `json:"no_requirement,omitempty,omitzero"`

	// Качество наблюдения ниже порога карты контроля.
	ObservationQualityBelowRecipe *bool `json:"observation_quality_below_recipe,omitempty,omitzero"`

	// Исходы наблюдения.
	Outcome []ReactionMapRulesElemMatchOutcomeElem `json:"outcome,omitempty,omitzero"`

	// Тяжесть.
	Severity []ReactionMapRulesElemMatchSeverityElem `json:"severity,omitempty,omitzero"`

	// Шаг — специальный процесс.
	SpecialProcess *bool `json:"special_process,omitempty,omitzero"`

	// Уровень доверия паспорта не ниже.
	TrustLevelMin *int `json:"trust_level_min,omitempty,omitzero"`
}

type ReactionMapRulesElemMatchBasisKindElem string

const ReactionMapRulesElemMatchBasisKindElemCheckSkipped ReactionMapRulesElemMatchBasisKindElem = "check_skipped"
const ReactionMapRulesElemMatchBasisKindElemDamageOnReceipt ReactionMapRulesElemMatchBasisKindElem = "damage_on_receipt"
const ReactionMapRulesElemMatchBasisKindElemEquipmentDeviation ReactionMapRulesElemMatchBasisKindElem = "equipment_deviation"
const ReactionMapRulesElemMatchBasisKindElemInspectionResult ReactionMapRulesElemMatchBasisKindElem = "inspection_result"
const ReactionMapRulesElemMatchBasisKindElemLeak ReactionMapRulesElemMatchBasisKindElem = "leak"
const ReactionMapRulesElemMatchBasisKindElemOperatorReport ReactionMapRulesElemMatchBasisKindElem = "operator_report"
const ReactionMapRulesElemMatchBasisKindElemSpecialProcessViolation ReactionMapRulesElemMatchBasisKindElem = "special_process_violation"

type ReactionMapRulesElemMatchDeviationKindsElem string

const ReactionMapRulesElemMatchDeviationKindsElemAlarm ReactionMapRulesElemMatchDeviationKindsElem = "alarm"
const ReactionMapRulesElemMatchDeviationKindsElemManualOverride ReactionMapRulesElemMatchDeviationKindsElem = "manual_override"
const ReactionMapRulesElemMatchDeviationKindsElemOther ReactionMapRulesElemMatchDeviationKindsElem = "other"
const ReactionMapRulesElemMatchDeviationKindsElemOutOfSetpoint ReactionMapRulesElemMatchDeviationKindsElem = "out_of_setpoint"
const ReactionMapRulesElemMatchDeviationKindsElemOverload ReactionMapRulesElemMatchDeviationKindsElem = "overload"
const ReactionMapRulesElemMatchDeviationKindsElemToolLifeWarning ReactionMapRulesElemMatchDeviationKindsElem = "tool_life_warning"
const ReactionMapRulesElemMatchDeviationKindsElemUnplannedProgramChange ReactionMapRulesElemMatchDeviationKindsElem = "unplanned_program_change"

type ReactionMapRulesElemMatchOutcomeElem string

const ReactionMapRulesElemMatchOutcomeElemDefectIndicated ReactionMapRulesElemMatchOutcomeElem = "defect_indicated"
const ReactionMapRulesElemMatchOutcomeElemNoDefectIndicated ReactionMapRulesElemMatchOutcomeElem = "no_defect_indicated"
const ReactionMapRulesElemMatchOutcomeElemUnableToAssess ReactionMapRulesElemMatchOutcomeElem = "unable_to_assess"

type ReactionMapRulesElemMatchSeverityElem string

const ReactionMapRulesElemMatchSeverityElemCritical ReactionMapRulesElemMatchSeverityElem = "critical"
const ReactionMapRulesElemMatchSeverityElemMajor ReactionMapRulesElemMatchSeverityElem = "major"
const ReactionMapRulesElemMatchSeverityElemMinor ReactionMapRulesElemMatchSeverityElem = "minor"
const ReactionMapRulesElemMatchSeverityElemUnknown ReactionMapRulesElemMatchSeverityElem = "unknown"

// Реакция.
type ReactionMapRulesElemReaction struct {
	// Уровень сдерживания.
	ContainmentLevel ReactionMapRulesElemReactionContainmentLevel `json:"containment_level"`

	// Черновик карточки несоответствия.
	DraftNc bool `json:"draft_nc"`

	// Реакция карты.
	Outcome ReactionMapRulesElemReactionOutcome `json:"outcome"`

	// Доля выборочной перепроверки человеком, б. п.
	SampledRecheckBp *int `json:"sampled_recheck_bp,omitempty,omitzero"`

	// Несоответствие всем изделиям окна нарушения (FR-151).
	SpecialProcessWindowNc *bool `json:"special_process_window_nc,omitempty,omitzero"`

	// Задача.
	Task *ReactionMapRulesElemReactionTask `json:"task,omitempty,omitzero"`
}

type ReactionMapRulesElemReactionContainmentLevel string

const ReactionMapRulesElemReactionContainmentLevelAdditionalCheck ReactionMapRulesElemReactionContainmentLevel = "additional_check"
const ReactionMapRulesElemReactionContainmentLevelItemHold ReactionMapRulesElemReactionContainmentLevel = "item_hold"
const ReactionMapRulesElemReactionContainmentLevelLotHold ReactionMapRulesElemReactionContainmentLevel = "lot_hold"
const ReactionMapRulesElemReactionContainmentLevelNone ReactionMapRulesElemReactionContainmentLevel = "none"
const ReactionMapRulesElemReactionContainmentLevelObserve ReactionMapRulesElemReactionContainmentLevel = "observe"

type ReactionMapRulesElemReactionOutcome string

const ReactionMapRulesElemReactionOutcomeIsolate ReactionMapRulesElemReactionOutcome = "isolate"
const ReactionMapRulesElemReactionOutcomeManualReview ReactionMapRulesElemReactionOutcome = "manual_review"
const ReactionMapRulesElemReactionOutcomePassToNext ReactionMapRulesElemReactionOutcome = "pass_to_next"
const ReactionMapRulesElemReactionOutcomeQuestionToTechnologist ReactionMapRulesElemReactionOutcome = "question_to_technologist"

type ReactionMapRulesElemReactionTask string

const ReactionMapRulesElemReactionTaskDecisionRequired ReactionMapRulesElemReactionTask = "decision_required"
const ReactionMapRulesElemReactionTaskInspectionMissing ReactionMapRulesElemReactionTask = "inspection_missing"
const ReactionMapRulesElemReactionTaskIsolateMove ReactionMapRulesElemReactionTask = "isolate_move"
const ReactionMapRulesElemReactionTaskRecheck ReactionMapRulesElemReactionTask = "recheck"

// Рамки применения.
type ReactionMapScope struct {
	// Типы изделий.
	ItemTypeIds []string `json:"item_type_ids"`

	// Шаги процесса.
	StepKeys []string `json:"step_keys,omitempty,omitzero"`
}

// Шаблоны смен (FR-81): normative/reference/*/shifts.yaml.
type ShiftsSeed struct {
	// Шаблоны.
	Patterns []ShiftsSeedPatternsElem `json:"patterns"`

	// Часовой пояс IANA.
	TimeZone string `json:"time_zone"`

	// Версия.
	Version int `json:"version"`
}

// Шаблон смены.
type ShiftsSeedPatternsElem struct {
	// Конец, местное время.
	Ends string `json:"ends"`

	// Идентификатор.
	ID string `json:"id"`

	// Цеха.
	Locations []string `json:"locations"`

	// Название.
	Name string `json:"name"`

	// Начало, местное время.
	Starts string `json:"starts"`
}
