// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.
// Источник: contracts/crypto/{dsse-envelope,checkpoint}.schema.json (make generate). Руками не править (AD-20).

package crypto

// Конверт DSSE v1 (AD-10): payloadType, payload (base64 канонического JSON RFC
// 8785) и подписи над PAE. Имена полей — как в спецификации DSSE. Закрытая схема.
type DsseEnvelope struct {
	// Base64 (стандартный алфавит, с выравниванием) канонических байтов содержимого.
	Payload string `json:"payload"`

	// Тип содержимого: application/vnd.ant.‹класс›+json; v=‹версия›.
	PayloadType string `json:"payloadType"`

	// Подписи над PAE(payloadType, payload); для hybrid — две (ГОСТ и ML-DSA-65).
	// Лишние и повторные не засчитываются.
	Signatures []DsseEnvelopeSignaturesElem `json:"signatures"`
}

type DsseEnvelopeSignaturesElem struct {
	// Ключ подписанта: key_id@версия.
	Keyid string `json:"keyid"`

	// Подпись в base64; кодирование по профилю — contracts/crypto/README.md.
	Sig string `json:"sig"`
}

// Содержимое контрольной точки хранителя (класс checkpoint, профиль hybrid, AD-8):
// головы обеих цепочек, звенья, диапазон committed_at, отпечаток предыдущей точки,
// время хранителя. Закрытая схема.
type KeeperCheckpoint struct {
	// Номер контрольной точки.
	CheckpointNo int `json:"checkpoint_no"`

	// Наименьший committed_at покрытых записей.
	CommittedAtFrom string `json:"committed_at_from"`

	// Наибольший committed_at покрытых записей.
	CommittedAtTo string `json:"committed_at_to"`

	// Профиль контрольных точек — hybrid (AD-32).
	CryptoProfile KeeperCheckpointCryptoProfile `json:"crypto_profile"`

	// Версия формата пакета.
	FormatVersion int `json:"format_version"`

	// Отпечаток генезиса — обязателен в первой точке каждой цепочки (AD-33).
	GenesisDigest *string `json:"genesis_digest,omitempty,omitzero"`

	// Головы цепочек main и ca.
	Heads []KeeperCheckpointHeadsElem `json:"heads"`

	// Время по часам хранителя.
	KeeperTime string `json:"keeper_time"`

	// Отпечаток предыдущей точки; null у первой.
	PreviousCheckpointDigest KeeperCheckpointPreviousCheckpointDigest `json:"previous_checkpoint_digest"`

	// Ключи хранителя (ГОСТ и ML-DSA).
	Signers []string `json:"signers"`
}

type KeeperCheckpointCryptoProfile string

const KeeperCheckpointCryptoProfileHybrid KeeperCheckpointCryptoProfile = "hybrid"

type KeeperCheckpointHeadsElem struct {
	// Цепочка.
	Chain KeeperCheckpointHeadsElemChain `json:"chain"`

	// Звено головы.
	Link string `json:"link"`

	// Номер головы.
	Seq int `json:"seq"`
}

type KeeperCheckpointHeadsElemChain string

const KeeperCheckpointHeadsElemChainCa KeeperCheckpointHeadsElemChain = "ca"
const KeeperCheckpointHeadsElemChainMain KeeperCheckpointHeadsElemChain = "main"

// Отпечаток предыдущей точки; null у первой.
type KeeperCheckpointPreviousCheckpointDigest *string
