// Code generated by backend/tools/contractgen; DO NOT EDIT.
// Источник: contracts/crypto (make generate). Руками не править (AD-20).

// Пакет crypto — Go-типы криптоформатов: конверт DSSE (AD-10), контрольная точка хранителя (AD-8).
//
// Слой: сгенерированные контракты — чистые данные; доступны домену (AD-1).
package crypto
