// Code generated by backend/tools/contractgen; DO NOT EDIT.
// Источник: contracts/statuses.yaml (make generate). Руками не править (AD-20).

// Пакет statuses — словарь статусов изделия (PRD §3b, AD-30, NFR-UI-3): шесть осей
// с модулем-владельцем и дополнительные словари; одно перечисление на весь продукт.
//
// Слой: сгенерированные контракты — чистые данные; доступны домену (AD-1).
package statuses

// Value — значение оси или словаря: код, текст интерфейса, тон цвета.
type Value struct {
	Code  string
	Label string
	Tone  string
}

// Dictionary — ось статуса или словарь.
type Dictionary struct {
	Name   string
	Title  string
	Owner  string
	Values []Value
}

// Palette — тон → цвет по умолчанию.
var Palette = [...][2]string{
	{"neutral", "#8A8F98"},
	{"info", "#2F6FDB"},
	{"attention", "#E0A100"},
	{"danger", "#D64545"},
	{"critical", "#8B1E1E"},
	{"success", "#2E9E5B"},
	{"qualified", "#7A9A2E"},
	{"muted", "#B8BDC6"},
}

// Положение в процессе (ось статуса).
type Position string

// Значения position.
const (
	// В очереди
	PositionInQueue Position = "in_queue"
	// В работе
	PositionInProgress Position = "in_progress"
	// На контроле
	PositionAtInspection Position = "at_inspection"
	// На точке предъявления
	PositionAtPresentationPoint Position = "at_presentation_point"
	// В перемещении
	PositionInTransit Position = "in_transit"
	// На хранении
	PositionInStorage Position = "in_storage"
	// В изоляции
	PositionIsolated Position = "isolated"
	// Завершено
	PositionCompleted Position = "completed"
)

// Состояние качества (ось статуса).
type Quality string

// Значения quality.
const (
	// Не проверено
	QualityNotInspected Quality = "not_inspected"
	// Годно
	QualityConforming Quality = "conforming"
	// Годно по разрешению на отклонение
	QualityAcceptedWithConcession Quality = "accepted_with_concession"
	// Оценка невозможна
	QualityUnableToAssess Quality = "unable_to_assess"
	// Сигнал о признаке дефекта
	QualitySignal Quality = "signal"
	// Несоответствие подтверждено
	QualityNonconforming Quality = "nonconforming"
)

// Решение по изделию (ось статуса).
type Disposition string

// Значения disposition.
const (
	// Решения нет
	DispositionNone Disposition = "none"
	// Переделка
	DispositionRework Disposition = "rework"
	// Ремонт
	DispositionRepair Disposition = "repair"
	// Как есть
	DispositionUseAsIs Disposition = "use_as_is"
	// Списание
	DispositionScrap Disposition = "scrap"
	// Возврат поставщику
	DispositionReturnToSupplier Disposition = "return_to_supplier"
)

// Сдерживание (ось статуса).
type Containment string

// Значения containment.
const (
	// Без сдерживания
	ContainmentNone Containment = "none"
	// Наблюдать
	ContainmentObserve Containment = "observe"
	// Доп. проверка
	ContainmentAdditionalCheck Containment = "additional_check"
	// Блок изделия
	ContainmentItemHold Containment = "item_hold"
	// Блок партии
	ContainmentLotHold Containment = "lot_hold"
)

// Учёт в 1С (ось статуса).
type ErpAccounting string

// Значения erp_accounting.
const (
	// Не передано в 1С
	ErpAccountingNotSent ErpAccounting = "not_sent"
	// Принято в работу
	ErpAccountingAcceptedIntoWork ErpAccounting = "accepted_into_work"
	// Перемещено
	ErpAccountingMoved ErpAccounting = "moved"
	// Переведено в брак
	ErpAccountingTransferredToScrap ErpAccounting = "transferred_to_scrap"
	// Возвращено поставщику
	ErpAccountingReturnedToSupplier ErpAccounting = "returned_to_supplier"
	// Выпущено
	ErpAccountingReleased ErpAccounting = "released"
)

// Статус в инциденте (для каждого инцидента отдельно) (ось статуса).
type Incident string

// Значения incident.
const (
	// Подтверждено
	IncidentConfirmed Incident = "confirmed"
	// Под подозрением
	IncidentSuspect Incident = "suspect"
	// Исключено
	IncidentExcluded Incident = "excluded"
	// Неизвестно
	IncidentUnknown Incident = "unknown"
)

// Axes — ось статуса в порядке файла.
var Axes = [...]Dictionary{
	{Name: "position", Title: "Положение в процессе", Owner: "process", Values: []Value{{Code: "in_queue", Label: "В очереди", Tone: "neutral"}, {Code: "in_progress", Label: "В работе", Tone: "info"}, {Code: "at_inspection", Label: "На контроле", Tone: "info"}, {Code: "at_presentation_point", Label: "На точке предъявления", Tone: "attention"}, {Code: "in_transit", Label: "В перемещении", Tone: "info"}, {Code: "in_storage", Label: "На хранении", Tone: "neutral"}, {Code: "isolated", Label: "В изоляции", Tone: "danger"}, {Code: "completed", Label: "Завершено", Tone: "muted"}}},
	{Name: "quality", Title: "Состояние качества", Owner: "quality", Values: []Value{{Code: "not_inspected", Label: "Не проверено", Tone: "neutral"}, {Code: "conforming", Label: "Годно", Tone: "success"}, {Code: "accepted_with_concession", Label: "Годно по разрешению на отклонение", Tone: "qualified"}, {Code: "unable_to_assess", Label: "Оценка невозможна", Tone: "attention"}, {Code: "signal", Label: "Сигнал о признаке дефекта", Tone: "attention"}, {Code: "nonconforming", Label: "Несоответствие подтверждено", Tone: "danger"}}},
	{Name: "disposition", Title: "Решение по изделию", Owner: "nonconformity", Values: []Value{{Code: "none", Label: "Решения нет", Tone: "neutral"}, {Code: "rework", Label: "Переделка", Tone: "attention"}, {Code: "repair", Label: "Ремонт", Tone: "attention"}, {Code: "use_as_is", Label: "Как есть", Tone: "qualified"}, {Code: "scrap", Label: "Списание", Tone: "critical"}, {Code: "return_to_supplier", Label: "Возврат поставщику", Tone: "critical"}}},
	{Name: "containment", Title: "Сдерживание", Owner: "nonconformity", Values: []Value{{Code: "none", Label: "Без сдерживания", Tone: "neutral"}, {Code: "observe", Label: "Наблюдать", Tone: "info"}, {Code: "additional_check", Label: "Доп. проверка", Tone: "attention"}, {Code: "item_hold", Label: "Блок изделия", Tone: "danger"}, {Code: "lot_hold", Label: "Блок партии", Tone: "danger"}}},
	{Name: "erp_accounting", Title: "Учёт в 1С", Owner: "erp", Values: []Value{{Code: "not_sent", Label: "Не передано в 1С", Tone: "neutral"}, {Code: "accepted_into_work", Label: "Принято в работу", Tone: "info"}, {Code: "moved", Label: "Перемещено", Tone: "info"}, {Code: "transferred_to_scrap", Label: "Переведено в брак", Tone: "critical"}, {Code: "returned_to_supplier", Label: "Возвращено поставщику", Tone: "critical"}, {Code: "released", Label: "Выпущено", Tone: "success"}}},
	{Name: "incident", Title: "Статус в инциденте (для каждого инцидента отдельно)", Owner: "analysis", Values: []Value{{Code: "confirmed", Label: "Подтверждено", Tone: "danger"}, {Code: "suspect", Label: "Под подозрением", Tone: "attention"}, {Code: "excluded", Label: "Исключено", Tone: "success"}, {Code: "unknown", Label: "Неизвестно", Tone: "neutral"}}},
}

// Что делать с изделием в инциденте (FR-62) (словарь).
type IncidentAction string

// Значения incident_action.
const (
	// Наблюдать
	IncidentActionObserve IncidentAction = "observe"
	// Проверить
	IncidentActionCheck IncidentAction = "check"
	// Заблокировать
	IncidentActionBlock IncidentAction = "block"
	// Выпустить
	IncidentActionRelease IncidentAction = "release"
)

// Сдерживание процесса — отдельный объект от сдерживания изделий (FR-49) (словарь).
type ProcessContainment string

// Значения process_containment.
const (
	// Стоп точки процесса
	ProcessContainmentProcessPointStop ProcessContainment = "process_point_stop"
	// Критическая остановка
	ProcessContainmentCriticalStop ProcessContainment = "critical_stop"
)

// Состояние исходящего учётного сообщения (не ось: ось меняет только квитанция) (словарь).
type ErpMessageStatus string

// Значения erp_message_status.
const (
	// В очереди на отправку
	ErpMessageStatusQueued ErpMessageStatus = "queued"
	// Отправлено — ждём подтверждения 1С
	ErpMessageStatusSent ErpMessageStatus = "sent"
	// Подтверждено 1С
	ErpMessageStatusAcknowledged ErpMessageStatus = "acknowledged"
	// Ошибка обмена
	ErpMessageStatusRejected ErpMessageStatus = "rejected"
	// В карантине — нужна переотправка
	ErpMessageStatusQuarantined ErpMessageStatus = "quarantined"
)

// Стадия расследования инцидента (стол технолога): область → гипотезы → причина → меры → проверка эффективности → закрыто (словарь).
type InvestigationStage string

// Значения investigation_stage.
const (
	// Область определена
	InvestigationStageScopeDefined InvestigationStage = "scope_defined"
	// Проверка гипотез
	InvestigationStageHypothesis InvestigationStage = "hypothesis"
	// Причина установлена
	InvestigationStageCauseConfirmed InvestigationStage = "cause_confirmed"
	// Меры назначены
	InvestigationStageActionAssigned InvestigationStage = "action_assigned"
	// Проверка эффективности
	InvestigationStageEffectivenessCheck InvestigationStage = "effectiveness_check"
	// Расследование закрыто
	InvestigationStageClosed InvestigationStage = "closed"
)

// Сводный статус изделия для списков и карты (словарь продукта «Статусы изделия»); вычисляется из шести осей, сам осью не является (словарь).
type ItemSummary string

// Значения item_summary.
const (
	// В работе
	ItemSummaryInProcess ItemSummary = "in_process"
	// Под подозрением
	ItemSummarySuspect ItemSummary = "suspect"
	// Ожидает доп. контроля
	ItemSummaryReinspectionRequired ItemSummary = "reinspection_required"
	// Заблокировано
	ItemSummaryHold ItemSummary = "hold"
	// Ожидает решения
	ItemSummaryPendingDecision ItemSummary = "pending_decision"
	// Несоответствие подтверждено
	ItemSummaryNonconforming ItemSummary = "nonconforming"
	// Исключено из подозрения
	ItemSummaryCleared ItemSummary = "cleared"
	// Разрешено к движению
	ItemSummaryReleased ItemSummary = "released"
	// На переделке
	ItemSummaryInRework ItemSummary = "in_rework"
	// На ремонте
	ItemSummaryInRepair ItemSummary = "in_repair"
	// Годно по разрешению на отклонение
	ItemSummaryAcceptedWithConcession ItemSummary = "accepted_with_concession"
	// Списано
	ItemSummaryScrapped ItemSummary = "scrapped"
	// Возвращено поставщику
	ItemSummaryReturned ItemSummary = "returned"
)

// Dictionaries — словарь в порядке файла.
var Dictionaries = [...]Dictionary{
	{Name: "incident_action", Title: "Что делать с изделием в инциденте (FR-62)", Owner: "", Values: []Value{{Code: "observe", Label: "Наблюдать", Tone: "info"}, {Code: "check", Label: "Проверить", Tone: "attention"}, {Code: "block", Label: "Заблокировать", Tone: "danger"}, {Code: "release", Label: "Выпустить", Tone: "success"}}},
	{Name: "process_containment", Title: "Сдерживание процесса — отдельный объект от сдерживания изделий (FR-49)", Owner: "", Values: []Value{{Code: "process_point_stop", Label: "Стоп точки процесса", Tone: "danger"}, {Code: "critical_stop", Label: "Критическая остановка", Tone: "critical"}}},
	{Name: "erp_message_status", Title: "Состояние исходящего учётного сообщения (не ось: ось меняет только квитанция)", Owner: "", Values: []Value{{Code: "queued", Label: "В очереди на отправку", Tone: "neutral"}, {Code: "sent", Label: "Отправлено — ждём подтверждения 1С", Tone: "attention"}, {Code: "acknowledged", Label: "Подтверждено 1С", Tone: "success"}, {Code: "rejected", Label: "Ошибка обмена", Tone: "danger"}, {Code: "quarantined", Label: "В карантине — нужна переотправка", Tone: "danger"}}},
	{Name: "investigation_stage", Title: "Стадия расследования инцидента (стол технолога): область → гипотезы → причина → меры → проверка эффективности → закрыто", Owner: "", Values: []Value{{Code: "scope_defined", Label: "Область определена", Tone: "info"}, {Code: "hypothesis", Label: "Проверка гипотез", Tone: "attention"}, {Code: "cause_confirmed", Label: "Причина установлена", Tone: "info"}, {Code: "action_assigned", Label: "Меры назначены", Tone: "info"}, {Code: "effectiveness_check", Label: "Проверка эффективности", Tone: "attention"}, {Code: "closed", Label: "Расследование закрыто", Tone: "muted"}}},
	{Name: "item_summary", Title: "Сводный статус изделия для списков и карты (словарь продукта «Статусы изделия»); вычисляется из шести осей, сам осью не является", Owner: "", Values: []Value{{Code: "in_process", Label: "В работе", Tone: "info"}, {Code: "suspect", Label: "Под подозрением", Tone: "attention"}, {Code: "reinspection_required", Label: "Ожидает доп. контроля", Tone: "attention"}, {Code: "hold", Label: "Заблокировано", Tone: "danger"}, {Code: "pending_decision", Label: "Ожидает решения", Tone: "attention"}, {Code: "nonconforming", Label: "Несоответствие подтверждено", Tone: "danger"}, {Code: "cleared", Label: "Исключено из подозрения", Tone: "success"}, {Code: "released", Label: "Разрешено к движению", Tone: "success"}, {Code: "in_rework", Label: "На переделке", Tone: "attention"}, {Code: "in_repair", Label: "На ремонте", Tone: "attention"}, {Code: "accepted_with_concession", Label: "Годно по разрешению на отклонение", Tone: "qualified"}, {Code: "scrapped", Label: "Списано", Tone: "critical"}, {Code: "returned", Label: "Возвращено поставщику", Tone: "critical"}}},
}
