// Code generated by backend/tools/contractgen; DO NOT EDIT.
// Источник: contracts/bpmn-ext/ant.json (дескриптор moddle) (make generate). Руками не править (AD-20).

// Пакет bpmnext — Go-структуры XML расширения BPMN urn:ant:bpmn-ext:1 (AD-17, FR-12, FR-156).
// Расширение BPMN 2.0 системы ant (AD-17, FR-12, FR-156): свойства элементов процесса в extensionElements пространства urn:ant:bpmn-ext:1. Источник схемы: из дескриптора генерируются Go-структуры XML, XSD и таблица документации (эпик 02). Значения перечислений и обязательность — contracts/bpmn-ext/rules.yaml.
//
// Слой: сгенерированные контракты — чистые данные; доступны домену (AD-1).
package bpmnext

import "encoding/xml"

// Namespace — пространство имён расширения.
const Namespace = "urn:ant:bpmn-ext:1"

// Prefix — префикс расширения в XML.
const Prefix = "ant"

// Properties — элемент ant:properties. Свойства шага: стабильный ключ, вид, цех и склад, специальный процесс, буфер, закрытие доступа к зоне, заверитель бумажной подписи, закрывающая точка, точка контроля, лимит доработок, учётное действие, тип события-триггера, область таймера.
type Properties struct {
	XMLName xml.Name `xml:"urn:ant:bpmn-ext:1 properties"`
	// Стабильный ключ шага, сохраняемый между версиями; смена смысла — новый ключ (AD-17).
	StepKey string `xml:"stepKey,attr,omitempty"`
	// Вид шага: operation | automated_inspection | human_inspection | movement | storage.
	StepKind string `xml:"stepKind,attr,omitempty"`
	// Цех (для дорожки) — id места вида workshop.
	Workshop string `xml:"workshop,attr,omitempty"`
	// Склад цеха (для дорожки).
	Warehouse string `xml:"warehouse,attr,omitempty"`
	// Специальный процесс (FR-151, ГОСТ Р 58633 п. 3.17).
	SpecialProcess *bool `xml:"specialProcess,attr,omitempty"`
	// Буфер или место очереди (FR-12).
	BufferPlace *bool `xml:"bufferPlace,attr,omitempty"`
	// Зоны, доступ к которым закрывает шаг, через пробел (FR-20).
	ClosesZoneAccess string `xml:"closesZoneAccess,attr,omitempty"`
	// Роль заверителя бумажной подписи на шаге (AD-43); у заверителя — полномочие paper_attestation в области.
	PaperAttester string `xml:"paperAttester,attr,omitempty"`
	// Закрывающая точка: ZT-1…ZT-6, ZT-4.1, ZT-4.2, ZT-R, ZT-V.
	ClosingPoint string `xml:"closingPoint,attr,omitempty"`
	// Точка контроля: KT-1…KT-5, KT-4d.
	InspectionPoint string `xml:"inspectionPoint,attr,omitempty"`
	// Операция по маршрутной карте.
	OperationCode string `xml:"operationCode,attr,omitempty"`
	// Лимит повторов или доработок (FR-18).
	ReworkLimit *int64 `xml:"reworkLimit,attr,omitempty"`
	// К чему лимит: item | zone | loop.
	ReworkLimitScope string `xml:"reworkLimitScope,attr,omitempty"`
	// Учётное действие на событии-сообщении «в 1С» (AD-18).
	ErpAction string `xml:"erpAction,attr,omitempty"`
	// Тип события каталога, которое запускает стартовое или промежуточное событие-сообщение (решение Д-5).
	TriggerEventType string `xml:"triggerEventType,attr,omitempty"`
	// Для граничного таймера: until_started — окно до начала операции; activity — всё время шага.
	TimerScope string `xml:"timerScope,attr,omitempty"`
	// Для конечного события вызываемого подпроцесса: значение переменной nc.outcome в точке вызова.
	Outcome string `xml:"outcome,attr,omitempty"`
}

// Inspection — элемент ant:inspection. Метод контроля и покрытие видов дефектов (FR-12, FR-14).
type Inspection struct {
	XMLName xml.Name `xml:"urn:ant:bpmn-ext:1 inspection"`
	// Метод контроля (defs.v1.json#/definitions/inspection_method).
	Method string `xml:"method,attr,omitempty"`
	// Фаза контроля.
	Phase string `xml:"phase,attr,omitempty"`
	// Коды видов дефектов классификатора, которые метод способен выявить, через пробел.
	Coverage string `xml:"coverage,attr,omitempty"`
	// Карта контроля `‹id›@‹версия›`.
	RecipeRef string `xml:"recipeRef,attr,omitempty"`
	// Порог качества наблюдения, б. п.: ниже — «оценка невозможна».
	ObservationQualityMinBp *int64 `xml:"observationQualityMinBp,attr,omitempty"`
}

// Requirement — элемент ant:requirement. Требование КД: характеристика, допуск, ревизия (FR-12).
type Requirement struct {
	XMLName xml.Name `xml:"urn:ant:bpmn-ext:1 requirement"`
	// Характеристика.
	Characteristic string `xml:"characteristic,attr,omitempty"`
	// Допуск.
	Tolerance string `xml:"tolerance,attr,omitempty"`
	// Документ КД и ревизия.
	KdRef string `xml:"kdRef,attr,omitempty"`
}

// ZoneRef — элемент ant:zoneRef. Зона изделия, к которой относится шаг (FR-12, FR-46).
type ZoneRef struct {
	XMLName xml.Name `xml:"urn:ant:bpmn-ext:1 zoneRef"`
	// Идентификатор зоны из номенклатуры.
	Zone string `xml:"zone,attr,omitempty"`
}

// PresentationPoint — элемент ant:presentationPoint. Точка предъявления: полномочие, роль, срок ожидания, эскалация при повторном предъявлении (FR-19).
type PresentationPoint struct {
	XMLName xml.Name `xml:"urn:ant:bpmn-ext:1 presentationPoint"`
	// Полномочие подписи.
	Authority string `xml:"authority,attr,omitempty"`
	// Роль.
	Role string `xml:"role,attr,omitempty"`
	// Вид цифрового клейма.
	StampKind string `xml:"stampKind,attr,omitempty"`
	// Срок ожидания, минут.
	WaitLimitMinutes *int64 `xml:"waitLimitMinutes,attr,omitempty"`
	// Срок ожидания, рабочих дней.
	WaitLimitWorkDays *int64 `xml:"waitLimitWorkDays,attr,omitempty"`
	// Полномочие при повторном предъявлении (уровнем выше).
	RepeatAuthority string `xml:"repeatAuthority,attr,omitempty"`
	// Изделие в перечне приёмок ПЗ/ВП — нужна подпись представителя заказчика.
	CustomerAcceptance *bool `xml:"customerAcceptance,attr,omitempty"`
}

// Precondition — элемент ant:precondition. Предусловие операции на дату операции (FR-17, FR-20).
type Precondition struct {
	XMLName xml.Name `xml:"urn:ant:bpmn-ext:1 precondition"`
	// Вид предусловия.
	Kind string `xml:"kind,attr,omitempty"`
	// block | record_violation.
	Mode string `xml:"mode,attr,omitempty"`
	// Параметр: квалификация, оборудование, зона, партия.
	Ref string `xml:"ref,attr,omitempty"`
}

// Document — элемент ant:document. Документ шага — шаблон нормативного слоя (FR-12, AD-12).
type Document struct {
	XMLName xml.Name `xml:"urn:ant:bpmn-ext:1 document"`
	// Шаблон документа.
	Template string `xml:"template,attr,omitempty"`
}

// ReactionMap — элемент ant:reactionMap. Карта реакций шага (FR-48).
type ReactionMap struct {
	XMLName xml.Name `xml:"urn:ant:bpmn-ext:1 reactionMap"`
	// Карта реакций `‹id›@‹версия›`.
	Ref string `xml:"ref,attr,omitempty"`
}

// Norm — элемент ant:norm. Норма времени и пропускной способности узла (FR-5, FR-12).
type Norm struct {
	XMLName xml.Name `xml:"urn:ant:bpmn-ext:1 norm"`
	// Норма времени, минут.
	TimeMinutes *int64 `xml:"timeMinutes,attr,omitempty"`
	// Нижняя граница нормы.
	TimeMinMinutes *int64 `xml:"timeMinMinutes,attr,omitempty"`
	// Верхняя граница нормы.
	TimeMaxMinutes *int64 `xml:"timeMaxMinutes,attr,omitempty"`
	// Норма ожидания в очереди, минут.
	QueueNormMinutes *int64 `xml:"queueNormMinutes,attr,omitempty"`
	// Пропускная способность за смену.
	ThroughputPerShift *int64 `xml:"throughputPerShift,attr,omitempty"`
	// Порог простоя в рабочую смену.
	IdleThresholdMinutes *int64 `xml:"idleThresholdMinutes,attr,omitempty"`
}

// NormRef — элемент ant:normRef. Нормативная опора для слоя «нормы» (FR-156): пункт стандарта, что проверить, что делает система; только из проверенного перечня norm-anchors.yaml.
type NormRef struct {
	XMLName xml.Name `xml:"urn:ant:bpmn-ext:1 normRef"`
	// Стандарт.
	Standard string `xml:"standard,attr,omitempty"`
	// Пункт.
	Clause string `xml:"clause,attr,omitempty"`
	// Что проверить на шаге.
	Check string `xml:"urn:ant:bpmn-ext:1 check,omitempty"`
	// Что делает система на шаге.
	SystemAction string `xml:"urn:ant:bpmn-ext:1 systemAction,omitempty"`
}

// ExtensionElements — наши элементы внутри bpmn:extensionElements узла; чужие элементы пропускаются.
type ExtensionElements struct {
	Properties        []Properties        `xml:"urn:ant:bpmn-ext:1 properties"`
	Inspection        []Inspection        `xml:"urn:ant:bpmn-ext:1 inspection"`
	Requirement       []Requirement       `xml:"urn:ant:bpmn-ext:1 requirement"`
	ZoneRef           []ZoneRef           `xml:"urn:ant:bpmn-ext:1 zoneRef"`
	PresentationPoint []PresentationPoint `xml:"urn:ant:bpmn-ext:1 presentationPoint"`
	Precondition      []Precondition      `xml:"urn:ant:bpmn-ext:1 precondition"`
	Document          []Document          `xml:"urn:ant:bpmn-ext:1 document"`
	ReactionMap       []ReactionMap       `xml:"urn:ant:bpmn-ext:1 reactionMap"`
	Norm              []Norm              `xml:"urn:ant:bpmn-ext:1 norm"`
	NormRef           []NormRef           `xml:"urn:ant:bpmn-ext:1 normRef"`
}
