// Code generated by backend/tools/contractgen; DO NOT EDIT.
// Источник: contracts/errors.yaml (make generate). Руками не править (AD-20).

// Пакет errcodes — каталог кодов ошибок RFC 9457 (FR-28, AD-39, «Соглашения/Ошибки API»):
// код → HTTP-статус, заголовок, шаблон пояснения, ключ текста интерфейса, карантин,
// признак отказа доменного гарда.
//
// Слой: сгенерированные контракты — чистые данные; доступны домену (AD-1).
package errcodes

// Code — код ошибки `‹семейство›.‹причина›`.
type Code string

// Info — строка каталога ошибок.
type Info struct {
	Code       Code
	Status     int
	Title      string
	Detail     string
	UIKey      string
	Quarantine bool
	Severity   string
	Guard      bool
	Aliases    []string
}

// ProblemTypePrefix — префикс URI типа проблемы.
const ProblemTypePrefix = "urn:ant:problem:"

// Коды ошибок.
const (
	// Заявка не активирована
	AccessAccountPending Code = "access.account_pending"
	// Отказ в допуске к рабочему месту
	AccessAdmissionDenied Code = "access.admission_denied"
	// Нужно согласование начальника ОТК
	AccessControllerApprovalRequired Code = "access.controller_approval_required"
	// Нет полномочий на это действие
	AccessForbidden Code = "access.forbidden"
	// Неверный логин или пароль
	AccessLoginFailed Code = "access.login_failed"
	// Нет действующего цифрового клейма
	AccessNoStamp Code = "access.no_stamp"
	// Нет в зоне по СКУД
	AccessNotInZone Code = "access.not_in_zone"
	// Нет действующей квалификации
	AccessNotQualified Code = "access.not_qualified"
	// Выдача прав себе
	AccessSelfGrant Code = "access.self_grant"
	// Разделение обязанностей
	AccessSeparationOfDuties Code = "access.separation_of_duties"
	// Нужна подпись уполномоченного
	AccessSignatureRequired Code = "access.signature_required"
	// Нужен вход
	AccessUnauthenticated Code = "access.unauthenticated"
	// Не своё рабочее место
	AccessWrongWorkplace Code = "access.wrong_workplace"
	// Протокол допуска не подписан
	AnalyzerAdmissionRouteOpen Code = "analyzer.admission_route_open"
	// Действие с паспортом недоступно в его статусе
	AnalyzerInvalidTransition Code = "analyzer.invalid_transition"
	// Нет допущенного анализатора
	AnalyzerNoQualifiedAnalyzer Code = "analyzer.no_qualified_analyzer"
	// Вернуть анализатор может только начальник ОТК
	AnalyzerReinstateRequiresHeadOfQc Code = "analyzer.reinstate_requires_head_of_qc"
	// Действие сверх уровня доверия паспорта
	AnalyzerTrustLevelExceeded Code = "analyzer.trust_level_exceeded"
	// Внутренняя ошибка
	ApiInternalError Code = "api.internal_error"
	// Объект не найден
	ApiNotFound Code = "api.not_found"
	// Операция ещё не реализована
	ApiNotImplemented Code = "api.not_implemented"
	// Слишком много запросов
	ApiRateLimited Code = "api.rate_limited"
	// В режиме воспроизведения действия недоступны
	ApiReplayReadOnly Code = "api.replay_read_only"
	// Запрос не соответствует контракту
	ApiValidationFailed Code = "api.validation_failed"
	// Этап маршрута не ждёт подписи
	DocumentStageNotOpen Code = "document.stage_not_open"
	// Канал обмена в режиме degraded
	ErpChannelDegraded Code = "erp.channel_degraded"
	// Несовместимое изменение контракта обмена
	ErpContractIncompatible Code = "erp.contract_incompatible"
	// Не найден договор с контрагентом
	ErpContractNotFound Code = "erp.contract_not_found"
	// Новая версия отправленного сообщения ждёт решения
	ErpCorrectionPending Code = "erp.correction_pending"
	// 1С вернула ошибку данных
	ErpDataError Code = "erp.data_error"
	// 1С уже провела документ
	ErpDuplicateInErp Code = "erp.duplicate_in_erp"
	// Галактика:ERP недоступна
	ErpGalaktikaUnavailable Code = "erp.galaktika_unavailable"
	// Нет соответствия идентификатора
	ErpIdMappingMissing Code = "erp.id_mapping_missing"
	// 1С не подтвердила приём
	ErpNoAck Code = "erp.no_ack"
	// Сообщение не ждёт решения
	ErpNotQuarantined Code = "erp.not_quarantined"
	// 1С недоступна
	ErpUnavailable Code = "erp.unavailable"
	// Выписка паспорта изменена
	FederationExtractTampered Code = "federation.extract_tampered"
	// Происхождение не подтверждено
	FederationExtractUnverifiable Code = "federation.extract_unverifiable"
	// Автоматически исключить нельзя
	IncidentAutoExcludeForbidden Code = "incident.auto_exclude_forbidden"
	// Нужно основание
	IncidentBasisRequired Code = "incident.basis_required"
	// Инцидент закрыт
	IncidentClosed Code = "incident.closed"
	// Нужно письменное объяснение работника
	IncidentExplanationRequired Code = "incident.explanation_required"
	// Изделия нет в области риска
	IncidentItemNotInScope Code = "incident.item_not_in_scope"
	// Слишком большая пачка
	IngestBatchTooLarge Code = "ingest.batch_too_large"
	// Подписанные байты не в каноническом виде
	IngestCanonicalFormViolation Code = "ingest.canonical_form_violation"
	// Тот же номер события, другое содержимое
	IngestDuplicateConflict Code = "ingest.duplicate_conflict"
	// Нет обязательного поля
	IngestMissingRequiredField Code = "ingest.missing_required_field"
	// Ключ источника отозван
	IngestRevokedKey Code = "ingest.revoked_key"
	// Сообщение не соответствует схеме
	IngestSchemaViolation Code = "ingest.schema_violation"
	// Подпись сообщения недействительна
	IngestSignatureInvalid Code = "ingest.signature_invalid"
	// Неизвестное значение перечисления — принято с пометкой
	IngestUnknownEnumValue Code = "ingest.unknown_enum_value"
	// Неизвестное значение в поле, важном для безопасности
	IngestUnknownEnumValueCritical Code = "ingest.unknown_enum_value_critical"
	// Неизвестный тип события
	IngestUnknownEventType Code = "ingest.unknown_event_type"
	// Неизвестная версия контракта
	IngestUnknownSchemaVersion Code = "ingest.unknown_schema_version"
	// Источник не зарегистрирован
	IngestUnknownSource Code = "ingest.unknown_source"
	// Изделие уже зарегистрировано
	ItemAlreadyRegistered Code = "item.already_registered"
	// Изделие уже выпущено
	ItemAlreadyReleased Code = "item.already_released"
	// Сборка образует цикл
	ItemAssemblyCycle Code = "item.assembly_cycle"
	// Привязываемое событие не найдено
	ItemBindingSubjectUnknown Code = "item.binding_subject_unknown"
	// Носитель уже действует у другого изделия
	ItemCarrierInUse Code = "item.carrier_in_use"
	// Носитель не нанесён
	ItemCarrierNotActive Code = "item.carrier_not_active"
	// Компонент уже в другой сборке
	ItemComponentAlreadyAssembled Code = "item.component_already_assembled"
	// Группа изделий составлена неверно
	ItemGroupInvalid Code = "item.group_invalid"
	// Группа не действует
	ItemGroupNotActive Code = "item.group_not_active"
	// Идентификация не под сомнением
	ItemIdentificationNotQuestioned Code = "item.identification_not_questioned"
	// Идентификация изделия под сомнением
	ItemIdentificationQuestioned Code = "item.identification_questioned"
	// Вмешательство не открыто
	ItemInterventionNotOpen Code = "item.intervention_not_open"
	// Партия уже зарегистрирована
	ItemLotAlreadyRegistered Code = "item.lot_already_registered"
	// Партия не принята
	ItemLotNotAccepted Code = "item.lot_not_accepted"
	// Изделие не зарегистрировано
	ItemNotRegistered Code = "item.not_registered"
	// Зона не описана в КД
	ItemZoneUnknown Code = "item.zone_unknown"
	// Журнал только на дописывание
	JournalAppendOnly Code = "journal.append_only"
	// Лимит разрешения на отклонение исчерпан
	JournalConcessionExhausted Code = "journal.concession_exhausted"
	// Запись уже есть в журнале
	JournalDuplicate Code = "journal.duplicate"
	// Запись отвергнута: аренда партиции утрачена
	JournalFenced Code = "journal.fenced"
	// Политика доступа изменилась
	JournalStalePolicy Code = "journal.stale_policy"
	// Состояние изменилось после проверки
	JournalStaleState Code = "journal.stale_state"
	// Убывание времени записи
	JournalTimeRegression Code = "journal.time_regression"
	// MES недоступна
	MesUnavailable Code = "mes.unavailable"
	// Не хватает подписей
	NonconformityApprovalsMissing Code = "nonconformity.approvals_missing"
	// Разрешение на отклонение не применимо
	NonconformityConcessionNotApplicable Code = "nonconformity.concession_not_applicable"
	// Нужно действующее разрешение на отклонение
	NonconformityConcessionRequired Code = "nonconformity.concession_required"
	// Точка предъявления без подписи
	NonconformityGateWithoutSignature Code = "nonconformity.gate_without_signature"
	// Открыто вмешательство
	NonconformityInterventionOpen Code = "nonconformity.intervention_open"
	// Решение недопустимо в этом состоянии
	NonconformityInvalidTransition Code = "nonconformity.invalid_transition"
	// Изделие заблокировано
	NonconformityItemBlocked Code = "nonconformity.item_blocked"
	// Нет результата метода контроля
	NonconformityMethodResultMissing Code = "nonconformity.method_result_missing"
	// Остановка точки процесса не действует
	NonconformityProcessHoldNotActive Code = "nonconformity.process_hold_not_active"
	// Нужна причина отклонения
	NonconformityRejectReasonRequired Code = "nonconformity.reject_reason_required"
	// Вернуть поставщику можно только необработанное
	NonconformityReturnOnlyUnprocessed Code = "nonconformity.return_only_unprocessed"
	// Закрывающий путь без контроля человеком
	ProcessClosingPathWithoutHuman Code = "process.closing_path_without_human"
	// Условие на стрелке не по языку условий
	ProcessConditionInvalid Code = "process.condition_invalid"
	// Неявное слияние стрелок без шлюза
	ProcessImplicitMerge Code = "process.implicit_merge"
	// Контроль без ссылки на требование КД
	ProcessInspectionWithoutRequirement Code = "process.inspection_without_requirement"
	// Не выполнено предусловие операции
	ProcessPreconditionFailed Code = "process.precondition_failed"
	// Точка предъявления без роли или полномочия
	ProcessPresentationPointWithoutRole Code = "process.presentation_point_without_role"
	// Квалификация исполнителя истекла
	ProcessQualificationExpired Code = "process.qualification_expired"
	// Не хватает подписей кворума
	ProcessQuorumIncomplete Code = "process.quorum_incomplete"
	// Лимит доработок зоны исчерпан
	ProcessReworkLimitExceeded Code = "process.rework_limit_exceeded"
	// Нарушение схемы расширения
	ProcessSchemaViolation Code = "process.schema_violation"
	// Истёк срок статуса
	ProcessStatusExpired Code = "process.status_expired"
	// У элемента нет step_key
	ProcessStepKeyMissing Code = "process.step_key_missing"
	// Недостижимый узел
	ProcessUnreachableNode Code = "process.unreachable_node"
	// Неподдерживаемый элемент BPMN
	ProcessUnsupportedElement Code = "process.unsupported_element"
	// Содержимое действующей версии изменено
	ProcessVersionTampered Code = "process.version_tampered"
	// Версия процесса изделия не найдена
	ProcessVersionUnknown Code = "process.version_unknown"
	// Сначала проверка зоны
	ProcessZoneCheckRequired Code = "process.zone_check_required"
	// Запись справочника не найдена
	ReferenceNotFound Code = "reference.not_found"
	// Агент токена не найден
	SigningAgentNotFound Code = "signing.agent_not_found"
	// Заверитель совпадает с подписантом
	SigningAttesterIsSigner Code = "signing.attester_is_signer"
	// Документ изменён после подписи
	SigningDocumentChanged Code = "signing.document_changed"
	// Чужой ключ
	SigningForeignKey Code = "signing.foreign_key"
	// Ключ отозван
	SigningKeyRevoked Code = "signing.key_revoked"
	// Ключ недоступен — проверить подпись нельзя
	SigningKeyUnavailable Code = "signing.key_unavailable"
	// Уровень подписи не допускается
	SigningLevelNotAllowed Code = "signing.level_not_allowed"
	// Нет пути подписи
	SigningNoSignaturePath Code = "signing.no_signature_path"
	// Пакет изменён
	SigningPackageTampered Code = "signing.package_tampered"
	// Бумага на этом этапе запрещена
	SigningPaperForbidden Code = "signing.paper_forbidden"
	// Неверный ПИН-код
	SigningPinWrong Code = "signing.pin_wrong"
	// Понижение криптопрофиля
	SigningProfileDowngrade Code = "signing.profile_downgrade"
	// QR-отпечаток на скане не совпадает с документом
	SigningQrMismatch Code = "signing.qr_mismatch"
	// Токен не вставлен
	SigningTokenMissing Code = "signing.token_missing"
	// Неизвестная версия формата документа
	SigningUnknownDocFormat Code = "signing.unknown_doc_format"
	// Прогон не найден
	SimulationRunNotFound Code = "simulation.run_not_found"
	// Ключи сценариев в профиле prod
	SimulationScenarioKeysInProd Code = "simulation.scenario_keys_in_prod"
)

var codes = [...]Info{
	{Code: AccessAccountPending, Status: 403, Title: "Заявка не активирована", Detail: "Учётная запись ещё не активирована администратором", UIKey: "errors.access.accountPending", Quarantine: false, Severity: "error", Guard: false, Aliases: nil},
	{Code: AccessAdmissionDenied, Status: 403, Title: "Отказ в допуске к рабочему месту", Detail: "Не выполнено: {checks}", UIKey: "errors.access.forbidden", Quarantine: false, Severity: "error", Guard: true, Aliases: nil},
	{Code: AccessControllerApprovalRequired, Status: 403, Title: "Нужно согласование начальника ОТК", Detail: "Контролёра на пост {workplace} назначает мастер по согласованию начальника ОТК — нужен закрытый документ «Назначение контролёра на пост»", UIKey: "errors.access.needSignature", Quarantine: false, Severity: "error", Guard: true, Aliases: nil},
	{Code: AccessForbidden, Status: 403, Title: "Нет полномочий на это действие", Detail: "Действие {action_id} над {object} не разрешено политикой", UIKey: "errors.access.forbidden", Quarantine: false, Severity: "error", Guard: false, Aliases: nil},
	{Code: AccessLoginFailed, Status: 401, Title: "Неверный логин или пароль", Detail: "Неверный логин или пароль", UIKey: "errors.access.loginFailed", Quarantine: false, Severity: "error", Guard: false, Aliases: nil},
	{Code: AccessNoStamp, Status: 403, Title: "Нет действующего цифрового клейма", Detail: "Нет действующего цифрового клейма по виду контроля «{kind}»", UIKey: "errors.decision.noStamp", Quarantine: false, Severity: "error", Guard: true, Aliases: nil},
	{Code: AccessNotInZone, Status: 403, Title: "Нет в зоне по СКУД", Detail: "По данным СКУД вы не в зоне {zone}", UIKey: "errors.access.notInZone", Quarantine: false, Severity: "error", Guard: true, Aliases: nil},
	{Code: AccessNotQualified, Status: 409, Title: "Нет действующей квалификации", Detail: "У {person} нет действующей квалификации в области поста {workplace} на {date} — назначить нельзя", UIKey: "errors.decision.qualificationExpired", Quarantine: false, Severity: "error", Guard: true, Aliases: nil},
	{Code: AccessSelfGrant, Status: 403, Title: "Выдача прав себе", Detail: "Расширение собственных прав — только со второй подписью независимой стороны: {who}", UIKey: "errors.access.selfGrant", Quarantine: false, Severity: "error", Guard: true, Aliases: nil},
	{Code: AccessSeparationOfDuties, Status: 403, Title: "Разделение обязанностей", Detail: "Вы участвовали в изготовлении этого изделия — принять его на точке предъявления нельзя", UIKey: "errors.decision.separationOfDuties", Quarantine: false, Severity: "error", Guard: true, Aliases: nil},
	{Code: AccessSignatureRequired, Status: 403, Title: "Нужна подпись уполномоченного", Detail: "Не хватает полномочий — нужна подпись: {who}", UIKey: "errors.access.needSignature", Quarantine: false, Severity: "error", Guard: false, Aliases: nil},
	{Code: AccessUnauthenticated, Status: 401, Title: "Нужен вход", Detail: "Сеанс отсутствует или истёк", UIKey: "errors.access.sessionExpired", Quarantine: false, Severity: "error", Guard: false, Aliases: nil},
	{Code: AccessWrongWorkplace, Status: 403, Title: "Не своё рабочее место", Detail: "Подписать можно только на своём рабочем месте: {workplace}", UIKey: "errors.access.wrongWorkplace", Quarantine: false, Severity: "error", Guard: true, Aliases: nil},
	{Code: AnalyzerAdmissionRouteOpen, Status: 409, Title: "Протокол допуска не подписан", Detail: "Протокол допуска {document_id} не подписан: маршрут подписей не закрыт — паспорт не вводится в действие", UIKey: "errors.generic", Quarantine: false, Severity: "error", Guard: true, Aliases: nil},
	{Code: AnalyzerInvalidTransition, Status: 409, Title: "Действие с паспортом недоступно в его статусе", Detail: "Паспорт {passport_id} в статусе «{status}»: действие «{action}» недоступно", UIKey: "errors.generic", Quarantine: false, Severity: "error", Guard: true, Aliases: nil},
	{Code: AnalyzerNoQualifiedAnalyzer, Status: 200, Title: "Нет допущенного анализатора", Detail: "Для карты контроля {recipe_ref} нет допущенного анализатора — контроль ручной", UIKey: "errors.vision.noQualifiedAnalyzer", Quarantine: false, Severity: "warning", Guard: false, Aliases: nil},
	{Code: AnalyzerReinstateRequiresHeadOfQc, Status: 403, Title: "Вернуть анализатор может только начальник ОТК", Detail: "Вернуть анализатор в работу может только начальник ОТК", UIKey: "errors.vision.returnRequiresHeadOfQc", Quarantine: false, Severity: "error", Guard: true, Aliases: nil},
	{Code: AnalyzerTrustLevelExceeded, Status: 403, Title: "Действие сверх уровня доверия паспорта", Detail: "Уровень доверия {trust_level} не разрешает действие {action}", UIKey: "errors.generic", Quarantine: false, Severity: "error", Guard: true, Aliases: nil},
	{Code: ApiInternalError, Status: 500, Title: "Внутренняя ошибка", Detail: "{detail}", UIKey: "errors.generic", Quarantine: false, Severity: "error", Guard: false, Aliases: nil},
	{Code: ApiNotFound, Status: 404, Title: "Объект не найден", Detail: "{object} «{id}» не найден", UIKey: "empty.notFound", Quarantine: false, Severity: "error", Guard: false, Aliases: nil},
	{Code: ApiNotImplemented, Status: 501, Title: "Операция ещё не реализована", Detail: "Операция {operation_id} объявлена в контракте, реализация — в работе", UIKey: "errors.generic", Quarantine: false, Severity: "error", Guard: false, Aliases: nil},
	{Code: ApiRateLimited, Status: 429, Title: "Слишком много запросов", Detail: "Повторите через {retry_after} с", UIKey: "errors.generic", Quarantine: false, Severity: "error", Guard: false, Aliases: nil},
	{Code: ApiReplayReadOnly, Status: 403, Title: "В режиме воспроизведения действия недоступны", Detail: "Запрос на момент {as_of} только для чтения", UIKey: "errors.decision.replayReadOnly", Quarantine: false, Severity: "error", Guard: false, Aliases: nil},
	{Code: ApiValidationFailed, Status: 400, Title: "Запрос не соответствует контракту", Detail: "Поле {field}: {reason}", UIKey: "errors.generic", Quarantine: false, Severity: "error", Guard: false, Aliases: nil},
	{Code: DocumentStageNotOpen, Status: 409, Title: "Этап маршрута не ждёт подписи", Detail: "Документ {doc_id}, версия {version}, этап {stage}: {why}", UIKey: "errors.generic", Quarantine: false, Severity: "error", Guard: true, Aliases: nil},
	{Code: ErpChannelDegraded, Status: 503, Title: "Канал обмена в режиме degraded", Detail: "Канал {system} в режиме degraded: {detail} — отправка остановлена до восстановления контракта", UIKey: "errors.integration.contractIncompatible", Quarantine: false, Severity: "error", Guard: false, Aliases: nil},
	{Code: ErpContractIncompatible, Status: 422, Title: "Несовместимое изменение контракта обмена", Detail: "Метаданные {system} не совпали с версией контракта адаптера — канал degraded, результат не отправлен", UIKey: "errors.integration.contractIncompatible", Quarantine: false, Severity: "error", Guard: false, Aliases: nil},
	{Code: ErpContractNotFound, Status: 422, Title: "Не найден договор с контрагентом", Detail: "Не найден договор с контрагентом {counterparty}", UIKey: "errors.integration.contractNotFound", Quarantine: false, Severity: "error", Guard: false, Aliases: nil},
	{Code: ErpCorrectionPending, Status: 409, Title: "Новая версия отправленного сообщения ждёт решения", Detail: "Содержимое учётного сообщения {business_key} изменилось после подтверждения 1С — исправление (сторно + новое) только по решению человека", UIKey: "errors.integration.erpDataError", Quarantine: false, Severity: "error", Guard: false, Aliases: nil},
	{Code: ErpDataError, Status: 422, Title: "1С вернула ошибку данных", Detail: "1С вернула ошибку данных {code}: {message}. Автоповтора нет — задача администратору", UIKey: "errors.integration.erpDataError", Quarantine: false, Severity: "error", Guard: false, Aliases: nil},
	{Code: ErpDuplicateInErp, Status: 200, Title: "1С уже провела документ", Detail: "1С уже провела документ с этим номером сообщения — второй не создан", UIKey: "errors.integration.duplicateInErp", Quarantine: false, Severity: "warning", Guard: false, Aliases: nil},
	{Code: ErpGalaktikaUnavailable, Status: 503, Title: "Галактика:ERP недоступна", Detail: "Галактика:ERP недоступна — повтор с тем же номером сообщения", UIKey: "errors.integration.galaktikaUnavailable", Quarantine: false, Severity: "error", Guard: false, Aliases: nil},
	{Code: ErpIdMappingMissing, Status: 422, Title: "Нет соответствия идентификатора", Detail: "Нет соответствия идентификатора: {object} «{external_id}» — добавьте его в таблицу соответствий", UIKey: "errors.integration.idMappingMissing", Quarantine: false, Severity: "error", Guard: false, Aliases: nil},
	{Code: ErpNoAck, Status: 504, Title: "1С не подтвердила приём", Detail: "1С не подтвердила приём за {time} — статус «учтено в 1С» не поставлен", UIKey: "errors.integration.noAck", Quarantine: false, Severity: "error", Guard: false, Aliases: nil},
	{Code: ErpNotQuarantined, Status: 409, Title: "Сообщение не ждёт решения", Detail: "Учётное сообщение {business_key} в состоянии «{status}» — переотправка и исправление только из карантина", UIKey: "errors.integration.erpDataError", Quarantine: false, Severity: "error", Guard: false, Aliases: nil},
	{Code: ErpUnavailable, Status: 503, Title: "1С недоступна", Detail: "1С недоступна — повтор с тем же номером сообщения через {delay}", UIKey: "errors.integration.erpUnavailable", Quarantine: false, Severity: "error", Guard: false, Aliases: nil},
	{Code: FederationExtractTampered, Status: 422, Title: "Выписка паспорта изменена", Detail: "Выписка паспорта изменена — не принята", UIKey: "errors.federation.extractTampered", Quarantine: false, Severity: "error", Guard: false, Aliases: nil},
	{Code: FederationExtractUnverifiable, Status: 202, Title: "Происхождение не подтверждено", Detail: "Подписи выписки проверить нельзя — принята с пометкой «происхождение не подтверждено»", UIKey: "errors.federation.extractUnverifiable", Quarantine: false, Severity: "warning", Guard: false, Aliases: nil},
	{Code: IncidentAutoExcludeForbidden, Status: 403, Title: "Автоматически исключить нельзя", Detail: "Исключить изделие из области риска автоматически нельзя — нужен человек или делегированное правило", UIKey: "errors.decision.autoExcludeForbidden", Quarantine: false, Severity: "error", Guard: true, Aliases: nil},
	{Code: IncidentBasisRequired, Status: 422, Title: "Нужно основание", Detail: "Сужение области риска — только с основанием: доказательство, автор, время", UIKey: "riskScope.basisRequired", Quarantine: false, Severity: "error", Guard: true, Aliases: nil},
	{Code: IncidentClosed, Status: 409, Title: "Инцидент закрыт", Detail: "Инцидент {incident_id} закрыт — область риска и выводы больше не меняются", UIKey: "errors.generic", Quarantine: false, Severity: "error", Guard: true, Aliases: nil},
	{Code: IncidentExplanationRequired, Status: 422, Title: "Нужно письменное объяснение работника", Detail: "Ошибку исполнителя подтверждает только уполномоченный после письменного объяснения работника (ТК РФ ст. 247); сначала — incident.operator_error.confirmed", UIKey: "errors.generic", Quarantine: false, Severity: "error", Guard: true, Aliases: nil},
	{Code: IncidentItemNotInScope, Status: 409, Title: "Изделия нет в области риска", Detail: "Изделие {item_id} не входит в текущую версию области риска инцидента {incident_id} (или уже исключено)", UIKey: "errors.generic", Quarantine: false, Severity: "error", Guard: true, Aliases: nil},
	{Code: IngestBatchTooLarge, Status: 413, Title: "Слишком большая пачка", Detail: "В пачке {count} сообщений, допустимо {limit}", UIKey: "errors.generic", Quarantine: false, Severity: "error", Guard: false, Aliases: nil},
	{Code: IngestCanonicalFormViolation, Status: 422, Title: "Подписанные байты не в каноническом виде", Detail: "{reason}: повторяющиеся ключи, целые вне ±(2^53−1), строки не в NFC или идентификатор не ASCII", UIKey: "errors.ingest.signatureInvalid", Quarantine: true, Severity: "error", Guard: false, Aliases: nil},
	{Code: IngestDuplicateConflict, Status: 409, Title: "Тот же номер события, другое содержимое", Detail: "{source_id}/{event_id}: содержимое отличается — конфликт целостности записан в журнал критических действий", UIKey: "errors.ingest.duplicateConflict", Quarantine: false, Severity: "error", Guard: false, Aliases: []string{"E_ID_CONFLICT"}},
	{Code: IngestMissingRequiredField, Status: 422, Title: "Нет обязательного поля", Detail: "Нет обязательного поля «{field}» — сообщение в карантине", UIKey: "errors.ingest.missingRequiredField", Quarantine: true, Severity: "error", Guard: false, Aliases: []string{"E_MISSING_FIELD"}},
	{Code: IngestRevokedKey, Status: 403, Title: "Ключ источника отозван", Detail: "Ключ {key_ref} отозван — сообщение отклонено и попало на шину безопасности", UIKey: "errors.ingest.revokedKey", Quarantine: true, Severity: "error", Guard: false, Aliases: nil},
	{Code: IngestSchemaViolation, Status: 422, Title: "Сообщение не соответствует схеме", Detail: "{event_type} v{version}: {reason} — несовместимое изменение возможно только новой мажорной версией", UIKey: "errors.ingest.incompatibleChange", Quarantine: true, Severity: "error", Guard: false, Aliases: nil},
	{Code: IngestSignatureInvalid, Status: 422, Title: "Подпись сообщения недействительна", Detail: "Ключ {key_ref}: {reason} — сообщение отклонено, событие безопасности записано", UIKey: "errors.ingest.signatureInvalid", Quarantine: true, Severity: "error", Guard: false, Aliases: nil},
	{Code: IngestUnknownEnumValue, Status: 202, Title: "Неизвестное значение перечисления — принято с пометкой", Detail: "Поле «{field}»: значение «{value}» сохранено как UNKNOWN({value}) с флагом", UIKey: "errors.ingest.unknownEnumValueAccepted", Quarantine: false, Severity: "warning", Guard: false, Aliases: []string{"E_UNKNOWN_ENUM"}},
	{Code: IngestUnknownEnumValueCritical, Status: 422, Title: "Неизвестное значение в поле, важном для безопасности", Detail: "Поле «{field}»: значение «{value}» неизвестно — сообщение в карантине", UIKey: "errors.ingest.unknownEnumValueQuarantined", Quarantine: true, Severity: "error", Guard: false, Aliases: nil},
	{Code: IngestUnknownEventType, Status: 422, Title: "Неизвестный тип события", Detail: "Тип «{event_type}» не объявлен в каталоге — сообщение в карантине", UIKey: "errors.ingest.incompatibleChange", Quarantine: true, Severity: "error", Guard: false, Aliases: nil},
	{Code: IngestUnknownSchemaVersion, Status: 422, Title: "Неизвестная версия контракта", Detail: "Тип {event_type}: версия {version} неизвестна — сообщение в карантине до появления повышателя", UIKey: "errors.ingest.unknownSchemaVersion", Quarantine: true, Severity: "error", Guard: false, Aliases: []string{"E_UNSUPPORTED_VERSION"}},
	{Code: IngestUnknownSource, Status: 403, Title: "Источник не зарегистрирован", Detail: "Источник «{source_id}» не зарегистрирован — сообщение отклонено", UIKey: "errors.ingest.unknownSource", Quarantine: true, Severity: "error", Guard: false, Aliases: nil},
	{Code: ItemAlreadyRegistered, Status: 409, Title: "Изделие уже зарегистрировано", Detail: "Изделие {item_id} уже зарегистрировано: ID рождается один раз", UIKey: "errors.generic", Quarantine: false, Severity: "error", Guard: true, Aliases: nil},
	{Code: ItemAlreadyReleased, Status: 409, Title: "Изделие уже выпущено", Detail: "Изделие {item_id} уже сдано на склад выпуска", UIKey: "errors.generic", Quarantine: false, Severity: "error", Guard: true, Aliases: nil},
	{Code: ItemAssemblyCycle, Status: 409, Title: "Сборка образует цикл", Detail: "Изделие {component_item_id} уже содержит {item_id}: цикл в дереве сборки невозможен", UIKey: "errors.generic", Quarantine: false, Severity: "error", Guard: true, Aliases: nil},
	{Code: ItemBindingSubjectUnknown, Status: 404, Title: "Привязываемое событие не найдено", Detail: "Событие {subject_event_id} не найдено среди событий без изделия", UIKey: "errors.generic", Quarantine: false, Severity: "error", Guard: true, Aliases: nil},
	{Code: ItemCarrierInUse, Status: 409, Title: "Носитель уже действует у другого изделия", Detail: "Носитель {carrier_ref} действует у изделия {other_item_id}: сначала снимите его там", UIKey: "errors.generic", Quarantine: false, Severity: "error", Guard: true, Aliases: nil},
	{Code: ItemCarrierNotActive, Status: 409, Title: "Носитель не нанесён", Detail: "У изделия нет действующего носителя {carrier_ref}", UIKey: "errors.generic", Quarantine: false, Severity: "error", Guard: true, Aliases: nil},
	{Code: ItemComponentAlreadyAssembled, Status: 409, Title: "Компонент уже в другой сборке", Detail: "Компонент {component_item_id} уже установлен в {assembly_item_id}", UIKey: "errors.generic", Quarantine: false, Severity: "error", Guard: true, Aliases: nil},
	{Code: ItemGroupInvalid, Status: 422, Title: "Группа изделий составлена неверно", Detail: "{reason}", UIKey: "errors.generic", Quarantine: false, Severity: "error", Guard: true, Aliases: nil},
	{Code: ItemGroupNotActive, Status: 409, Title: "Группа не действует", Detail: "Группа {group_id} не сформирована или уже расформирована", UIKey: "errors.generic", Quarantine: false, Severity: "error", Guard: true, Aliases: nil},
	{Code: ItemIdentificationNotQuestioned, Status: 409, Title: "Идентификация не под сомнением", Detail: "Подтверждать нечего: запись {questioned_event_id} не ставила идентификацию под сомнение или уже снята", UIKey: "errors.generic", Quarantine: false, Severity: "error", Guard: true, Aliases: nil},
	{Code: ItemIdentificationQuestioned, Status: 409, Title: "Идентификация изделия под сомнением", Detail: "Изделие изолировано до повторной идентификации человеком с подписью", UIKey: "errors.generic", Quarantine: false, Severity: "error", Guard: true, Aliases: nil},
	{Code: ItemInterventionNotOpen, Status: 409, Title: "Вмешательство не открыто", Detail: "Вмешательство {intervention_id} не открыто или уже закрыто", UIKey: "errors.generic", Quarantine: false, Severity: "error", Guard: true, Aliases: nil},
	{Code: ItemLotAlreadyRegistered, Status: 409, Title: "Партия уже зарегистрирована", Detail: "Партия {lot_id} уже зарегистрирована", UIKey: "errors.generic", Quarantine: false, Severity: "error", Guard: true, Aliases: nil},
	{Code: ItemLotNotAccepted, Status: 409, Title: "Партия не принята", Detail: "Партия {lot_id} в состоянии «{status}»: выдача в производство — только принятой партии", UIKey: "errors.generic", Quarantine: false, Severity: "error", Guard: true, Aliases: nil},
	{Code: ItemNotRegistered, Status: 409, Title: "Изделие не зарегистрировано", Detail: "Изделие {item_id} не зарегистрировано — сначала регистрация", UIKey: "errors.generic", Quarantine: false, Severity: "error", Guard: true, Aliases: nil},
	{Code: ItemZoneUnknown, Status: 422, Title: "Зона не описана в КД", Detail: "Зона {zone_id} не описана для типа изделия {item_type_id}", UIKey: "errors.generic", Quarantine: false, Severity: "error", Guard: true, Aliases: nil},
	{Code: JournalAppendOnly, Status: 405, Title: "Журнал только на дописывание", Detail: "Изменение и удаление записей журнала невозможны — исправление только новой записью", UIKey: "errors.generic", Quarantine: false, Severity: "error", Guard: false, Aliases: nil},
	{Code: JournalConcessionExhausted, Status: 409, Title: "Лимит разрешения на отклонение исчерпан", Detail: "Разрешение {concession_id}: остаток {remaining} из {limit}", UIKey: "errors.decision.concessionRequired", Quarantine: false, Severity: "error", Guard: true, Aliases: nil},
	{Code: JournalDuplicate, Status: 409, Title: "Запись уже есть в журнале", Detail: "Запись с этим event_id уже записана — повтор не записывается", UIKey: "errors.generic", Quarantine: false, Severity: "error", Guard: false, Aliases: nil},
	{Code: JournalFenced, Status: 503, Title: "Запись отвергнута: аренда партиции утрачена", Detail: "Эпоха аренды партиции {partition} устарела — копия больше не пишет", UIKey: "errors.generic", Quarantine: false, Severity: "error", Guard: false, Aliases: nil},
	{Code: JournalStalePolicy, Status: 409, Title: "Политика доступа изменилась", Detail: "Политика изменилась после seq {policy_seq} — повторите действие", UIKey: "errors.staleState", Quarantine: false, Severity: "error", Guard: false, Aliases: nil},
	{Code: JournalStaleState, Status: 409, Title: "Состояние изменилось после проверки", Detail: "В потоке {stream} после seq {basis_seq} есть новые записи — обновите и проверьте ещё раз", UIKey: "errors.staleState", Quarantine: false, Severity: "error", Guard: false, Aliases: nil},
	{Code: JournalTimeRegression, Status: 500, Title: "Убывание времени записи", Detail: "committed_at или recorded_at убывает по seq — запись отвергнута", UIKey: "errors.generic", Quarantine: false, Severity: "error", Guard: false, Aliases: nil},
	{Code: MesUnavailable, Status: 503, Title: "MES недоступна", Detail: "MES недоступна — блок изделия не передан, повтор", UIKey: "errors.integration.mesUnavailable", Quarantine: false, Severity: "error", Guard: false, Aliases: nil},
	{Code: NonconformityApprovalsMissing, Status: 409, Title: "Не хватает подписей", Detail: "Не хватает подписей: {who} — решение не исполняется", UIKey: "errors.decision.approvalsMissing", Quarantine: false, Severity: "error", Guard: true, Aliases: nil},
	{Code: NonconformityConcessionNotApplicable, Status: 422, Title: "Разрешение на отклонение не применимо", Detail: "Разрешение {concession_id}: {reason} (истёк срок, отозвано, изделие вне области)", UIKey: "errors.decision.concessionRequired", Quarantine: false, Severity: "error", Guard: true, Aliases: nil},
	{Code: NonconformityConcessionRequired, Status: 422, Title: "Нужно действующее разрешение на отклонение", Detail: "«{decision}» без действующего разрешения на отклонение не подписывается", UIKey: "errors.decision.concessionRequired", Quarantine: false, Severity: "error", Guard: true, Aliases: []string{"E_PERMIT_REQUIRED"}},
	{Code: NonconformityGateWithoutSignature, Status: 403, Title: "Точка предъявления без подписи", Detail: "Без подписи {role} изделие не проходит точку предъявления — попытка записана в журнал критических действий", UIKey: "errors.decision.gateWithoutSignature", Quarantine: false, Severity: "error", Guard: true, Aliases: nil},
	{Code: NonconformityInterventionOpen, Status: 409, Title: "Открыто вмешательство", Detail: "Открыта запись вмешательства — приёмка и отгрузка запрещены", UIKey: "errors.decision.interventionOpen", Quarantine: false, Severity: "error", Guard: true, Aliases: nil},
	{Code: NonconformityInvalidTransition, Status: 409, Title: "Решение недопустимо в этом состоянии", Detail: "«{action}» недопустимо: несоответствие {nc_id} в состоянии «{status}»", UIKey: "errors.generic", Quarantine: false, Severity: "error", Guard: true, Aliases: nil},
	{Code: NonconformityItemBlocked, Status: 409, Title: "Изделие заблокировано", Detail: "Изделие заблокировано — операция запрещена до решения", UIKey: "errors.decision.itemBlocked", Quarantine: false, Severity: "error", Guard: true, Aliases: nil},
	{Code: NonconformityMethodResultMissing, Status: 409, Title: "Нет результата метода контроля", Detail: "Нельзя принять: нет результата {method} на {inspection_point} — «нет данных» ≠ «годно»", UIKey: "empty.inspectionMissing", Quarantine: false, Severity: "error", Guard: true, Aliases: nil},
	{Code: NonconformityProcessHoldNotActive, Status: 409, Title: "Остановка точки процесса не действует", Detail: "Остановка {hold_id} не найдена или уже снята", UIKey: "errors.generic", Quarantine: false, Severity: "error", Guard: true, Aliases: nil},
	{Code: NonconformityRejectReasonRequired, Status: 422, Title: "Нужна причина отклонения", Detail: "Укажите, почему сигнал отклонён", UIKey: "errors.decision.rejectReasonRequired", Quarantine: false, Severity: "error", Guard: true, Aliases: nil},
	{Code: NonconformityReturnOnlyUnprocessed, Status: 422, Title: "Вернуть поставщику можно только необработанное", Detail: "Изделие {item_id} уже обрабатывалось — «вернуть поставщику» недопустимо", UIKey: "errors.decision.returnOnlyUnprocessed", Quarantine: false, Severity: "error", Guard: true, Aliases: nil},
	{Code: ProcessClosingPathWithoutHuman, Status: 422, Title: "Закрывающий путь без контроля человеком", Detail: "Закрывающий путь без контроля человеком: {element}", UIKey: "errors.process.closingPathWithoutHuman", Quarantine: false, Severity: "error", Guard: false, Aliases: nil},
	{Code: ProcessConditionInvalid, Status: 422, Title: "Условие на стрелке не по языку условий", Detail: "Стрелка {element}: {reason}", UIKey: "errors.process.schemaViolation", Quarantine: false, Severity: "error", Guard: false, Aliases: nil},
	{Code: ProcessImplicitMerge, Status: 422, Title: "Неявное слияние стрелок без шлюза", Detail: "У элемента {element} несколько входящих стрелок без шлюза — поставьте явный шлюз слияния", UIKey: "errors.process.schemaViolation", Quarantine: false, Severity: "error", Guard: false, Aliases: nil},
	{Code: ProcessInspectionWithoutRequirement, Status: 200, Title: "Контроль без ссылки на требование КД", Detail: "Предупреждение: контроль без ссылки на требование КД — {element}", UIKey: "errors.process.inspectionWithoutRequirement", Quarantine: false, Severity: "warning", Guard: false, Aliases: nil},
	{Code: ProcessPreconditionFailed, Status: 409, Title: "Не выполнено предусловие операции", Detail: "Не выполнено предусловие: {condition}", UIKey: "errors.decision.preconditionFailed", Quarantine: false, Severity: "error", Guard: true, Aliases: nil},
	{Code: ProcessPresentationPointWithoutRole, Status: 422, Title: "Точка предъявления без роли или полномочия", Detail: "Точка предъявления без роли или полномочия: {element}", UIKey: "errors.process.presentationPointWithoutRole", Quarantine: false, Severity: "error", Guard: false, Aliases: nil},
	{Code: ProcessQualificationExpired, Status: 409, Title: "Квалификация исполнителя истекла", Detail: "Квалификация исполнителя {performer} истекла {date} — операция заблокирована", UIKey: "errors.decision.qualificationExpired", Quarantine: false, Severity: "error", Guard: true, Aliases: nil},
	{Code: ProcessQuorumIncomplete, Status: 409, Title: "Не хватает подписей кворума", Detail: "Не хватает подписей кворума: {who}", UIKey: "errors.process.quorumIncomplete", Quarantine: false, Severity: "error", Guard: false, Aliases: nil},
	{Code: ProcessReworkLimitExceeded, Status: 422, Title: "Лимит доработок зоны исчерпан", Detail: "Лимит доработок зоны {zone} исчерпан ({used} из {limit}) — нужно отдельное разрешение уполномоченного", UIKey: "errors.decision.reworkLimitReached", Quarantine: false, Severity: "error", Guard: true, Aliases: []string{"E_REWORK_LIMIT"}},
	{Code: ProcessSchemaViolation, Status: 422, Title: "Нарушение схемы расширения", Detail: "Нарушение схемы расширения: {element} — {detail}", UIKey: "errors.process.schemaViolation", Quarantine: false, Severity: "error", Guard: false, Aliases: nil},
	{Code: ProcessStatusExpired, Status: 409, Title: "Истёк срок статуса", Detail: "Истёк срок статуса «{status}» — нужна повторная обработка", UIKey: "errors.decision.statusExpired", Quarantine: false, Severity: "error", Guard: true, Aliases: nil},
	{Code: ProcessStepKeyMissing, Status: 422, Title: "У элемента нет step_key", Detail: "У элемента {element} нет ant:properties/@stepKey", UIKey: "errors.process.schemaViolation", Quarantine: false, Severity: "error", Guard: false, Aliases: nil},
	{Code: ProcessUnreachableNode, Status: 422, Title: "Недостижимый узел", Detail: "Недостижимый узел: {element}", UIKey: "errors.process.unreachableNode", Quarantine: false, Severity: "error", Guard: false, Aliases: nil},
	{Code: ProcessUnsupportedElement, Status: 422, Title: "Неподдерживаемый элемент BPMN", Detail: "Неподдерживаемый элемент BPMN: {element}", UIKey: "errors.process.unsupportedElement", Quarantine: false, Severity: "error", Guard: false, Aliases: nil},
	{Code: ProcessVersionTampered, Status: 409, Title: "Содержимое действующей версии изменено", Detail: "Хеш версии {version_id} не совпадает с подписанным — версия не исполняется", UIKey: "errors.process.versionTampered", Quarantine: false, Severity: "error", Guard: false, Aliases: nil},
	{Code: ProcessVersionUnknown, Status: 409, Title: "Версия процесса изделия не найдена", Detail: "Версия процесса с хешем {hash}, закреплённая за изделием, не найдена — изделие не исполняется", UIKey: "errors.process.versionTampered", Quarantine: false, Severity: "error", Guard: false, Aliases: nil},
	{Code: ProcessZoneCheckRequired, Status: 409, Title: "Сначала проверка зоны", Detail: "Операция закрывает доступ к зоне {zone} — сначала завершите её проверку", UIKey: "errors.decision.zoneCheckRequired", Quarantine: false, Severity: "error", Guard: true, Aliases: nil},
	{Code: ReferenceNotFound, Status: 422, Title: "Запись справочника не найдена", Detail: "Не найдена запись справочника: {field} — в том числе ответ 1С «в справочнике не найдена запись»", UIKey: "errors.integration.refNotFound", Quarantine: false, Severity: "error", Guard: false, Aliases: []string{"E_REF_NOT_FOUND"}},
	{Code: SigningAgentNotFound, Status: 424, Title: "Агент токена не найден", Detail: "Агент токена не отвечает — подпишите на бумаге с заверением", UIKey: "errors.signing.agentNotFound", Quarantine: false, Severity: "error", Guard: false, Aliases: nil},
	{Code: SigningAttesterIsSigner, Status: 422, Title: "Заверитель совпадает с подписантом", Detail: "Бумажную подпись заверяет второй человек — заверитель ≠ подписант", UIKey: "errors.signing.attesterIsSigner", Quarantine: false, Severity: "error", Guard: true, Aliases: nil},
	{Code: SigningDocumentChanged, Status: 409, Title: "Документ изменён после подписи", Detail: "Отпечаток документа {doc_id} изменился — подпись недействительна, нужна новая версия", UIKey: "errors.signing.documentChanged", Quarantine: false, Severity: "error", Guard: false, Aliases: nil},
	{Code: SigningForeignKey, Status: 403, Title: "Чужой ключ", Detail: "Пользователь сеанса не совпадает с субъектом ключа {key_ref} — тревога записана", UIKey: "errors.access.forbidden", Quarantine: false, Severity: "error", Guard: false, Aliases: nil},
	{Code: SigningKeyRevoked, Status: 422, Title: "Ключ отозван", Detail: "Ключ {key_ref} отозван — подпись этим ключом не принимается", UIKey: "errors.signing.certRevoked", Quarantine: false, Severity: "error", Guard: false, Aliases: nil},
	{Code: SigningKeyUnavailable, Status: 422, Title: "Ключ недоступен — проверить подпись нельзя", Detail: "Ключ {key_ref} недоступен: статус «не проверяемо», а не «подпись действительна»", UIKey: "errors.signing.keyUnavailable", Quarantine: false, Severity: "warning", Guard: false, Aliases: nil},
	{Code: SigningLevelNotAllowed, Status: 422, Title: "Уровень подписи не допускается", Detail: "Действие {action_id} требует уровня {required}; агент отклонил уровень {actual}", UIKey: "errors.generic", Quarantine: false, Severity: "error", Guard: false, Aliases: nil},
	{Code: SigningNoSignaturePath, Status: 422, Title: "Нет пути подписи", Detail: "Нет ни агента токена, ни подписи на бумаге — закрывающее решение не подписывается", UIKey: "errors.signing.noSignaturePath", Quarantine: false, Severity: "error", Guard: false, Aliases: nil},
	{Code: SigningPackageTampered, Status: 422, Title: "Пакет изменён", Detail: "Подпись не сходится с содержимым пакета — отклонён", UIKey: "errors.signing.packageTampered", Quarantine: false, Severity: "error", Guard: false, Aliases: nil},
	{Code: SigningPaperForbidden, Status: 422, Title: "Бумага на этом этапе запрещена", Detail: "Этап {stage} маршрута не допускает подпись на бумаге или заверитель не задан", UIKey: "errors.signing.paperForbidden", Quarantine: false, Severity: "error", Guard: true, Aliases: nil},
	{Code: SigningPinWrong, Status: 424, Title: "Неверный ПИН-код", Detail: "Неверный ПИН-код", UIKey: "errors.signing.pinWrong", Quarantine: false, Severity: "error", Guard: false, Aliases: nil},
	{Code: SigningProfileDowngrade, Status: 422, Title: "Понижение криптопрофиля", Detail: "Для {object_class} на момент подписи обязателен профиль {required}, а подписано {actual}", UIKey: "errors.signing.packageTampered", Quarantine: false, Severity: "error", Guard: false, Aliases: nil},
	{Code: SigningQrMismatch, Status: 422, Title: "QR-отпечаток на скане не совпадает с документом", Detail: "Скан с QR {qr_digest} не относится к документу {doc_digest} — скан не принят", UIKey: "errors.signing.qrMismatch", Quarantine: false, Severity: "error", Guard: false, Aliases: nil},
	{Code: SigningTokenMissing, Status: 424, Title: "Токен не вставлен", Detail: "Токен не вставлен", UIKey: "errors.signing.tokenMissing", Quarantine: false, Severity: "error", Guard: false, Aliases: nil},
	{Code: SigningUnknownDocFormat, Status: 422, Title: "Неизвестная версия формата документа", Detail: "doc_format_version {version} агенту неизвестен — подпись не выполнена", UIKey: "errors.generic", Quarantine: false, Severity: "error", Guard: false, Aliases: nil},
	{Code: SimulationRunNotFound, Status: 404, Title: "Прогон не найден", Detail: "Прогон {run_id} не найден", UIKey: "empty.scenarioNotStarted", Quarantine: false, Severity: "error", Guard: false, Aliases: nil},
	{Code: SimulationScenarioKeysInProd, Status: 500, Title: "Ключи сценариев в профиле prod", Detail: "В реестре есть ключи класса scenario или в составе есть demo-signer — профиль prod не стартует", UIKey: "errors.generic", Quarantine: false, Severity: "error", Guard: false, Aliases: nil},
}

// Lookup возвращает строку каталога для кода.
func Lookup(c Code) (Info, bool) {
	lo, hi := 0, len(codes)
	for lo < hi {
		m := (lo + hi) / 2
		if codes[m].Code < c {
			lo = m + 1
		} else {
			hi = m
		}
	}
	if lo < len(codes) && codes[lo].Code == c {
		return codes[lo], true
	}
	return Info{}, false
}

// All возвращает все коды, отсортированные по коду.
func All() []Info { return codes[:] }
